### ISSUE TITLE
Empty segment files in brca study (provisional)

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/datahub#10]
Hi,

Segment data for the brca study is missing. There are files for it, `brca_tcga_data_cna_hg19.seg` and `brca_tcga_meta_cna_hg19_seg.txt` but the `.seq` file seems to be emtpy. This segment data is available on cbioportal.org for this study, but just not in this download file.

Kind regards,
Sander

**Comment by sandertan** [comment]
This appears to be similar to this issue:

https://github.com/cBioPortal/cbioportal/issues/1576

**Comment by sandertan** [comment]
Will be fixed https://github.com/cBioPortal/datahub/pull/11

**Comment by sandertan** [comment]
Is fixed in #11

**Comment by zheins** [comment]
@sandertan can we close this issue? #11 was merged.
