### ISSUE TITLE
Investigate if there are more studies we can curate for the Fusion tab

### ISSUE THREAD

**Issue by inodb** [cBioPortal/datahub#1039]
https://deploy-preview-3023--cbioportalfrontend.netlify.com/results/fusions?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=msk_impact_2017&case_set_id=msk_impact_2017_cnaseq&data_priority=0&gene_list=TP53&geneset_list=%20&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=msk_impact_2017_cna&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=msk_impact_2017_mutations&profileFilter=0&tab_index=tab_visualize

- would be great if we can find TCGA studies

**Comment by jjgao** [comment]
Pancaner Atlas dataset has fusions: https://github.com/cBioPortal/datahub/issues/241#issuecomment-499976460

There are only break points and fusion annotation without exons. We will need to find a way to annotate them.
