### ISSUE TITLE
Mixed cancer types should not fall under CUP

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/datahub#104]
We should change the cancer type hierarchy for `mixed` types. Currently, pan cancer studies such as MSK-IMPACT and CCLE fall under `mixed`. And `mixed` falls under `CUP`, which is carcinomas of unknown primary. This is not necessarily true. 

An improvement would be to move `mixed` to root of the tree and name it `Mixed Cancer Types` or `Pan-Cancer Studies` in the UI. CCLE could even be called `Cell Lines`, just like on cbioportal.org

**Comment by sandertan** [comment]
We can implement this when we release a new seed database, for example when we switch to 2.4.0

**Comment by jjgao** [comment]
@sandertan this is a good point.

Maybe we could hard code it that `mixed` is moved to root?

cc'ing @schultzn

**Comment by schultzn** [comment]
Agreed... MIXED is good as a separate category

**Comment by jjgao** [comment]
@sandertan would you have the bandwidth to take this? Or should I assign it to @alisman ?

**Comment by sandertan** [comment]
@jjgao If you'd like to hardcode it, please assign it to @alisman . 

Question out of interest: Why not change the oncotree? My understanding of a CUP is that it is a tumor caused by metastasized cells that originate from the unknown primary site. Some of the other branches under CUP, such as `Adenocarcinoma` and `Neuroendocrine Carcinoma` seem out of place as well, because they can be a primary site, right?:

<img width="1092" alt="screen shot 2017-10-10 at 09 46 58" src="https://user-images.githubusercontent.com/9624990/31375101-b920c952-ada0-11e7-8937-9de9d3270127.png">

**Comment by jjgao** [comment]
@sandertan  `Adenocarcinoma` and `Neuroendocrine Carcinoma` do not define the primary sites.

@schultzn maybe we can move `mixed` (and maybe some other nodes) under `other`?

**Comment by schultzn** [comment]
I like that idea.

**Comment by jjgao** [comment]
Adding @sheridancbio.

@sheridancbio we would like to move `mixed` under `other` in oncotree. Could you help?

**Comment by jjgao** [comment]
@ritikakundra please see comments above. Can we move `mixed` under `other` in oncotree?

**Comment by sandertan** [comment]
I think you should move `mixed` under `tissue` in oncotree. This is still an open issue.

**Comment by ritikakundra** [comment]
@jjgao @schultzn Does this look good:
http://oncotree.mskcc.org/#/home?version=oncotree_development

**Comment by jjgao** [comment]
Looks good to me. Thanks!

![image](https://user-images.githubusercontent.com/840895/76138229-de649400-6013-11ea-9dda-ad92ef76f038.png)
