### ISSUE TITLE
calculate msi

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#1043]
It would be very useful if we can calculate msi scores of all samples, e.g. using [msi-sensor](https://github.com/ding-lab/msisensor)

The MSI Sensor score for TCGA is available here: https://www.sciencedirect.com/science/article/pii/S0092867418303131#mmc5

**Comment by jjgao** [comment]
Running msisensor requires BAM file and therefore would not be trivial...

**Comment by jjgao** [comment]
We can also consider other scores, such as MANTIS. [This paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5972025/) has the MANTIS score of TCGA samples.

**Comment by jjgao** [comment]
We will release msi data for msk_impact_2017: https://github.com/cBioPortal/datahub/issues/1057

**Comment by jjgao** [comment]
MSIsensor-pro scores are available for CRC, STAD, and UCEC: https://github.com/xjtu-omics/msisensor-pro/issues/3#issuecomment-601143403

**Comment by wddeng** [comment]
> We will release msi data for msk_impact_2017: #1057

That's great! Have you released the msi data? I cannot find them in the msk_impact_2017. Thanks!

**Comment by jjgao** [comment]
@wddeng not yet, we are still working on it. We'll update in #1057

**Comment by wddeng** [comment]
@jjgao  Hi Jianjiong, thank you for your reply! What does "#1057" mean? Really appreciated for your help!

**Comment by jjgao** [comment]
It's captured in another issue https://github.com/cBioPortal/datahub/issues/1057. You should be able to click the link.

**Comment by wddeng** [comment]
> It's captured in another issue #1057. You should be able to click the link.

Yes, but after I clicked the link, it did not mention about when it would be posted. Thanks again for your reply!

**Comment by jjgao** [comment]
@wddeng we don't really have a date. We will update that issue after we release the data.
