### ISSUE TITLE
hnsc_tcga: invalid values in Validation_Status 

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/datahub#105]
Column contains `---`

```
ERROR: data_mutations_extended.txt: lines [526, 527, 528, (5507 more)]: column 26: Value in column 'Validation_Status' is invalid; value encountered: '---'
```

These are the allowed values:
`'untested', 'inconclusive', 'valid', 'invalid', 'na', 'redacted', 'unknown'`

**Comment by yichaoS** [comment]
included in issue https://github.com/cBioPortal/datahub/issues/120
