### ISSUE TITLE
improvements to mixed_cfdna_msk_2019

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#1070]
- [x] Can we change mixed_cfdna_msk_2019 to cfdna_msk_2019? (it would be great if we can aviod using `mixed` in study ID going forward as mentioned in #256 
- [ ] It would be great to get the time of specimen.
- [x] Should we just remove the Tumor Type attribute given that we have Caner Type? The Tumor Type for all NSCLC is NA.

![image](https://user-images.githubusercontent.com/840895/76919720-11264c00-68a0-11ea-95ea-4e6610e3a9d7.png)

**Comment by ritikakundra** [comment]
@rmadupuri @yichaoS Maybe its time to email Pedram for the timeline?

**Comment by ritikakundra** [comment]
@rmadupuri @yichaoS Maybe its time to email Pedram for the timeline?
