### ISSUE TITLE
Wrong or missing metadata in studies

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/datahub#109]
Found some examples of wrong metadata:

1- weight in kilograms, ranging from 5 to 1760 !?

![image](https://user-images.githubusercontent.com/2900303/31880388-a3ba8f7c-b7e0-11e7-872e-1e57aeae90b5.png)

2- missing metadata description info regarding "Fraction genome altered":

![image](https://user-images.githubusercontent.com/2900303/31880447-cc54dc44-b7e0-11e7-9656-b7697938d35c.png)

3- "longest dimension" ... of what? Missing description:

![image](https://user-images.githubusercontent.com/2900303/31880499-09ce19a0-b7e1-11e7-8055-52b61bbb002c.png)

etc.

I think these highlighted issues are actually found in multiple studies. Can you please review and update the metadata/description fields of the clinical attributes?

**Comment by pieterlukasse** [comment]
assigning also to @priti88 since she is following up on https://groups.google.com/forum/#!topic/cbioportal/qF9QasoEz2E

**Comment by n1zea144** [comment]
For 1) I've determined that INITIAL_WEIGHT in the study is the sample weight, not the patient weight (it comes from the biospecimen-sample file, which I cannot find on the legacy site.

[Clinical files in biotab format for BRCA on GDC legacy](https://portal.gdc.cancer.gov/legacy-archive/search/f?filters=%7B%22op%22:%22and%22,%22content%22:%5B%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22files.data_category%22,%22value%22:%5B%22Clinical%22%5D%7D%7D,%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22files.data_format%22,%22value%22:%5B%22Biotab%22%5D%7D%7D,%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22cases.project.project_id%22,%22value%22:%5B%22TCGA-BRCA%22%5D%7D%7D,%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22files.data_type%22,%22value%22:%5B%22Clinical%20data%22%5D%7D%7D,%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22files.platform%22,%22value%22:%5B%22Clinical%22%5D%7D%7D%5D%7D)

I can find versions of these files in the GDC site in the XML format, but for individual cases, e.g.,

[biospecimen-sample file in XML format ](https://portal.gdc.cancer.gov/files/6b66a673-22e2-4771-afa9-14ff40f01520)

For completeness, here is the general query

[query for biospecimen-sample files in xml](https://portal.gdc.cancer.gov/query?filters=~%28op~%27and~content~%28~%28op~%27and~content~%28~%28op~%27in~content~%28field~%27cases.project.project_id~value~%28~%27TCGA-BRCA%29%29%29~%28op~%27in~content~%28field~%27files.data_type~value~%28~%27Biospecimen%2A20Supplement%29%29%29%29%29%29%29&query=cases.project.project_id%20in%20%5B%22TCGA-BRCA%22%5D%20and%20files.data_type%20in%20%5B%22Biospecimen%20Supplement%22%5D)

Interestingly, this attribute appears in the data_bcr_clinical_data_sample.txt file for the tcga-brca study, but the metadata, like display name, is incorrect.  @ritikakundra I think we need to do the following:

1. Assess all the studies in datahub that have this attribute present (you can search the clinical_attribute_meta table for this information) and update the Display name in the data_bcr_clinical_data_sample.txt file accordingly.  You may need to introduce a new sample level attribute for this.

2. Update clinical_attribute_meta table in the cBioPortal with the proper attribute and attribute metadata.

**Comment by pieterlukasse** [comment]
@n1zea144 @ritikakundra any updates on this one?

**Comment by jjgao** [comment]
It's mostly fixed: https://github.com/cBioPortal/datahub/issues/505

There is still "initial patient weight" in published TCGA studies.

**Comment by jjgao** [comment]
@cBioPortal/curation could you try to reproduce the issue and see how many are standing issues?

**Comment by yichaoS** [comment]
@jjgao 

- 1st issue "initial patient weight" -> " sample weight" : There are two studies (prad_cpcg_2017, blca_tcga_pub_2017)still with attribute `Initial Patient Weight` and the number doesn't look right to me (see screenshot). Should these also be sample weight (in grams)? 
<img width="344" alt="Screen Shot 2020-09-15 at 3 43 26 PM" src="https://user-images.githubusercontent.com/5973438/93256885-0a529600-f76a-11ea-857f-810416f53f1f.png">

- 2nd issue: This attribute is automatically generated when importing. And meta data is being pulled from CDD. Therefore all public studies (163) were affected by this. We can update the description for this attribute in CDD and directly update the description in DB for these studies to avoid re-importing. 

- 3rd issue "longest dimension": We still only have "longest dimension" as description for this clinical attribute. Have to go into the publication to find the proper description. Studies affected are all 32 provisional studies, `prad_cpcg_2017`, `kich_tcga_pub`

**Comment by jjgao** [comment]
@yichaoS

For 1, I think most likely it's sample weight, but it would be good if you can find another source to confirm (e.g. gdc).

For 2, your plan sounds good.

For 3, maybe dgc has some descriptions?

**Comment by rmadupuri** [comment]
Hi @jjgao @yichaoS 
For 1, confirmed from gdc its sample weight.
For 3, from gdc, the description for `longest dimension` is `Longest dimension of the sample measured in millimeters`.

**Comment by jjgao** [comment]
@rmadupuri thanks! Please update them - code and meta data.
