### ISSUE TITLE
Microbiome data for TCGA 

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#1095]
It would be very interesting if we can integrate the microbiome from [this study](https://www.nature.com/articles/s41586-020-2095-1).

We can use generic assay to host the data.

We may need to contact the authors to get he matrix of sample vs species.

**Comment by rmadupuri** [comment]
@jjgao @ritikakundra @yichaoS : seems like the microbiome data in matrix format (sample vs species) is available at 
1. ftp://ftp.microbio.me/pub/cancer_microbiome_analysis/TCGA  **(or)**
2. https://drive.google.com/drive/folders/18V2ON-Go5AeEtZLe1f9EeJToWOhg81ab

There's also a website associated: http://cancermicrobiome.ucsd.edu/CancerMicrobiome_DataBrowser/

Should we use the file `Kraken-TCGA-Voom-SNM-All-Putative-Contaminants-Removed-Data.csv` from the TCGA/Kraken/ folder on the ftp site, as the source of our normalized microbiome data? Could you confirm if this is right? 

The sample IDs in the microbiome data file has to be mapped to actual TCGA sample ids. There is no direct mapping specified but we can use any of the cols (filename, case_uuid, sample_uuid) from the meta file: ftp://ftp.microbio.me/pub/cancer_microbiome_analysis/TCGA/Kraken/Metadata-TCGA-Kraken-17625-Samples.csv file to map the samples to TCGA sample IDs? 

- filename seems to contain the sample ID but not all samples are mappable.
- case_uuid is mappable to Other_Patient_ID from the TCGA studies on portal. (not sure if all the pancan studies have Other_Patient_ID attribute?)
- Do we have Other_Sample_ID attribute for pancan studies? (that should map to `sample_uuid` from the Kraken meta file. 

If it's not possible to map the IDs, we will have to reach out to the authors for the mapping. Thank you!

**Comment by jjgao** [comment]
@rmadupuri thanks for looking into this. We should be able to map UUID to barcode: https://seandavi.github.io/post/2017-12-29-genomicdatacommons-id-mapping/

I am not sure which file to use. Do you find any clue based on their paper and website?

**Comment by jjgao** [comment]
Let's also get @dippindots's input on data format.

**Comment by dippindots** [comment]
I will take a look! Are we going to use this file as the source: `Kraken-TCGA-Voom-SNM-All-Putative-Contaminants-Removed-Data.csv`?

**Comment by jjgao** [comment]
@rmadupuri @dippindots I looked at the site a little more, I think "Kraken-TCGA-Voom-SNM-All-Putative-Contaminants-Removed-Data.csv" seems like the right file we need.

**Comment by rmadupuri** [comment]
Thanks for confirming @jjgao. The paper doesn't mention which file to use but I understood `Kraken-TCGA-Voom-SNM-All-Putative-Contaminants-Removed-Data.csv` is the best file use based on Methods section (summarized below): 
1. Kraken pipeline was used on sample BAM files.
2. BWA was used to filter false positives from the output of Kraken.
3. Output of Kraken was re-analyzed by SHOTGUN (missing viral genomes in the reference database. So output doesn't contain viral genes.)
4. Normalized data to log-cpm using Voom, performed supervised normalization (SNM).

**Comment by rmadupuri** [comment]
**STEPS TO ADD MICROBIOME DATA:**

**1. Data file format:**
- [ ] Define the cbioportal file format to host Microbiome data.

**2. Raw files to be downloaded:**
- [ ] Microbiome data file: `ftp://ftp.microbio.me/pub/cancer_microbiome_analysis/TCGA/Kraken/Kraken-TCGA-Voom-SNM-All-Putative-Contaminants-Removed-Data.csv from the TCGA/Kraken/`
- [ ] Corresponding Metadata file: `ftp://ftp.microbio.me/pub/cancer_microbiome_analysis/TCGA/Metadata-TCGA-All-18116-Samples.csv`

**3. Mapping to TCGA barcodes:** The sample IDs in the Microbiome data file has to be mapped to TCGA barcodes.
- [ ] Join the `disease_type` and `sample_uuid` cols from `Metadata-TCGA-All-18116-Samples.csv` file to Microbiome data file based on the sampleid (first column)
- [ ] Map the `sample_uuid`'s to TCGA Barcodes using: https://seandavi.github.io/post/2017-12-29-genomicdatacommons-id-mapping/

**4. Split the file:**
- [ ] Split the mapped Microbiome data file from Step 3 to the corresponding cancer types based on `disease_type` col. 
- [ ] Do not include sampleid and disease_type cols in the split output. The output files here will be a 2D matrix with TCGA Barcode per row and microbiome entity per column.
- [ ] Transpose the 2D matrix to contain microbiome entity per row and TCGA sample ID per col to follow generic assay data file format.

**5. Add files to pancan studies:**
- [ ]  Create meta files and move the split transformed files to corresponding pancan studies.
- [ ] Import studies to portal.

**Comment by rmadupuri** [comment]
@jjgao @dippindots are we using the generic assay format to host the microbiome data?

**Comment by dippindots** [comment]
@rmadupuri I think generic assay format can hold those data, the only thing I need to fix is this issue: https://github.com/cBioPortal/cbioportal/issues/7448. The current generic assay endpoint is slow, and the microbiome data has lots of entities, that would be problematic, do you know when would we need this feature ready? I need to fix this issue before that.

**Comment by rmadupuri** [comment]
@jjgao we have the microbiome data ready. On testing import to triage we realized the length of the entity id is limited to 45 characters (fails import). But the ids that we have includes complete taxonomic nomenclature. See below. 

![Screen Shot 2020-06-05 at 1 32 46 PM](https://user-images.githubusercontent.com/34350829/83924236-1cc43900-a752-11ea-94d8-fa4c1b0e56be.png)

Is it okay to use just the Genus name as the entity_stable_id? (We can probably have the complete name under NAME col? Is there a character limit for the NAME? @dippindots?)

**Comment by dippindots** [comment]
@rmadupuri The character limit for `NAME` is: 
``VALUE` varchar(5000) NOT NULL`.
So I think there would be no problem to use the `NAME` column to contain those data.
