### ISSUE TITLE
Validator: Priority flexibility

### ISSUE THREAD

**Issue by ritikakundra** [cBioPortal/datahub#110]
Currently, the validator fails on some priority values. In this screenshot
![screen shot 2017-11-01 at 11 55 52 am](https://user-images.githubusercontent.com/12007862/32283920-11cf70fa-befc-11e7-8596-9eb06608cfe6.png)
 it fails on value 0

**Comment by sandertan** [comment]
Fixed by @pieterlukasse in https://github.com/cBioPortal/cbioportal/pull/3079. @ritikakundra can you confirm it works with version `1.8.3` or higher?
