### ISSUE TITLE
Re-curate survival data for ntrk_msk_2019

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#1106]
https://www.cbioportal.org/study/summary?id=ntrk_msk_2019

![image](https://user-images.githubusercontent.com/840895/80233518-967de880-8624-11ea-8076-cdaed43b57a9.png)

**Comment by ritikakundra** [comment]
@jjgao These are computed from DOB, so how do we recurate it?

**Comment by jjgao** [comment]
It should be possible to create survival data from these columns:

![image](https://user-images.githubusercontent.com/840895/80262969-23449880-865d-11ea-877d-fc8b3420791d.png)

The problem is that they round it to integers. I am wondering if we can get the original data?

**Comment by sbabyanusha** [comment]
@jjgao Looked into this issue and couldn't get the source data for this study to re-curate the survival data.
