### ISSUE TITLE
Validator: if there is a duplicate sample in case_list file, validator does not fail

### ISSUE THREAD

**Issue by ritikakundra** [cBioPortal/datahub#111]
![screen shot 2017-11-01 at 12 02 05 pm](https://user-images.githubusercontent.com/12007862/32284089-82ada814-befc-11e7-81d0-6a292ef5cb9d.png)

For this mock study, I duplicated a sample in the sequenced case_list.
[bone_msk_2017.zip](https://github.com/cBioPortal/datahub/files/1434745/bone_msk_2017.zip)

**Comment by sandertan** [comment]
I created a PR to fix add validation for this.

**Comment by yichaoS** [comment]
Checked with @ritikakundra.
We could see this warning showing up when a case is duplicated.

**Comment by sandertan** [comment]
I'll close it when PR is merged.
