### ISSUE TITLE
Missing data archives in datahub/public

### ISSUE THREAD

**Issue by guv** [cBioPortal/datahub#113]
I ran a script against the cbioportal Web API and `cBioPortal/datahub/public`.
The studies listed below have no data archive.
Is it possible to add those data archives to this repository?

- ~[[ampca_bcm_2016] Ampullary Carcinoma (Baylor College of Medicine, Cell Reports 2016)](https://github.com/cBioPortal/datahub/raw/master/public/ampca_bcm_2016.tar.gz)~
- ~[[brca_mbcproject_wagle_2017] The Metastatic Breast Cancer Project (Provisional, October 2017)](https://github.com/cBioPortal/datahub/raw/master/public/brca_mbcproject_wagle_2017.tar.gz)~
- [[egc_msk_2017] Targeted Sequencing of 341 samples from metastatic esophagogastric cancer patients (MSK,Cancer Discovery 2017)](https://github.com/cBioPortal/datahub/raw/master/public/egc_msk_2017.tar.gz)
- ~[[gct_msk_2016] Genomic Profile of Patients with Advanced Germ Cell Tumors (MSK, JCO 2016).](https://github.com/cBioPortal/datahub/raw/master/public/gct_msk_2016.tar.gz)~
- ~[[mbl_sickkids_2016] Medulloblastoma (Sickkids, Nature 2016)](https://github.com/cBioPortal/datahub/raw/master/public/mbl_sickkids_2016.tar.gz)~
- [[mel_cell_2016] Melanoma Pembrolizumab and Nivolumab treatment (Roger 2016)](https://github.com/cBioPortal/datahub/raw/master/public/mel_cell_2016.tar.gz)
- ~[[nepc_wcm_2016] Neuroendocrine Prostate Cancer (Trento/Cornell/Broad 2016)](https://github.com/cBioPortal/datahub/raw/master/public/nepc_wcm_2016.tar.gz)~
- ~[[nsclc_unito_2016] Genetic Characterization of NSCLC young adult patients ( University of Turin, Lung Cancer 2016)](https://github.com/cBioPortal/datahub/raw/master/public/nsclc_unito_2016.tar.gz)~
- ~[[pact_jhu_2011] Cystic Tumor of the Pancreas (Johns Hopkins, PNAS 2011](https://github.com/cBioPortal/datahub/raw/master/public/pact_jhu_2011.tar.gz)~
- ~[[panet_arcnet_2017] Whole-Genome Sequencing of Pancreatic Neuroendocrine Tumors (Nature, 2017)](https://github.com/cBioPortal/datahub/raw/master/public/panet_arcnet_2017.tar.gz)~
- ~[[past_dkfz_heidelberg_2013] Whole-genome sequencing of pilocytic astrocytomasatic (Nat Genetics, 2013)](https://github.com/cBioPortal/datahub/raw/master/public/past_dkfz_heidelberg_2013.tar.gz)~

Update: added studies struck out

**Comment by yichaoS** [comment]
Studies added in https://github.com/cBioPortal/datahub/pull/115
- ampca_bcm_2016
- brca_mbcproject_wagle_2017
- gct_msk_2016
- mbl_sickkids_2016
- nepc_wcm_2016
- nsclc_unito_2016
- pact_jhu_2011
- panet_arcnet_2017
- past_dkfz_heidelberg_2013
