### ISSUE TITLE
Adding a section of Immunogenomics Studies in query page

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#1133]
It would be useful to easily search for immunogenomics studies. We would 1) use tags; 2) add "immunogenomics" in description; 3) create a section of these studies.

For 3), There is a list of immunogenomics studies we curated: https://github.com/cBioPortal/datahub/issues?q=label%3Aimmunotherapy+

@cBioPortal/curation would you please compile a list of immunogenomics studies and comment here?

**Comment by ritikakundra** [comment]
Sure @jjgao

**Comment by yichaoS** [comment]
@jjgao @ritikakundra

Going through the cbioportal News page and issue list @jjgao linked, here are the studies we already curated and published: 
- https://www.cbioportal.org/study/summary?id=gbm_columbia_2019 
- https://www.cbioportal.org/study/summary?id=skcm_dfci_2015 
- https://www.cbioportal.org/study/summary?id=skcm_mskcc_2014
- https://www.cbioportal.org/study/summary?id=mel_ucla_2016
- https://www.cbioportal.org/study/summary?id=nsclc_mskcc_2018
- https://www.cbioportal.org/study/summary?id=nsclc_mskcc_2015

Sort of related (indicator/association et al.)
- https://www.cbioportal.org/study/summary?id=coad_cptac_2019
- https://www.cbioportal.org/study/summary?id=ntrk_msk_2019
- https://www.cbioportal.org/study/summary?id=ccrcc_dfci_2019

In progress: 
- mel_dfci_2019: still in review? https://github.com/cBioPortal/datahub/pull/1085

Question
- related?? https://www.cbioportal.org/study/summary?id=nsclc_tracerx_2017 vs. https://github.com/cBioPortal/datahub/issues/732

@jjgao @ritikakundra Could you please review this list above? And what are the next steps to take (tags, query section?)

**Comment by jjgao** [comment]
Not sure if coad_cptac_2019 and ntrk_msk_2019 count as immunogenomics studies. Is there any immuno data in them? Other studies look good.

And also add the TMB study: https://www.cbioportal.org/study/summary?id=tmb_mskcc_2018

Let's just create a query section below peds studies for now?

**Comment by yichaoS** [comment]
@jjgao `coad_cptac_2019` and `ntrk_msk_2019` doesn't have immuno data in it. They are just suggesting genomic patterns / clinical profiles as possible indicators for immuno-therapies. Updated the list above. Should we try following the format and update the `cbioportal_spring_boot.yaml` for this new section?

**Comment by jjgao** [comment]
@yichaoS yes, thanks!
