### ISSUE TITLE
more data for sclc_ucologne_2015

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#1134]
https://www.cbioportal.org/study/summary?id=sclc_ucologne_2015

https://www.nature.com/articles/nature14664#Sec35

- [x] fusion (Suppl_Table4)
- [ ] cna (Suppl_Table8?)
- [x] expression (Suppl_Table10)
- [ ] sv (Suppl_Table14) - we should keep this data and annotate it when we have our sv annotator.

**Comment by yichaoS** [comment]
@jjgao Both this issue and the previous issue of adding expression data (https://github.com/cBioPortal/datahub/issues/1113) is being addressed by @sbabyanusha  in this PR: https://github.com/cBioPortal/datahub/pull/1126

Me and @sbabyanusha had a discussion about the cna data. Seems like the gistic data given was only for 2 genes. And the cna seg data given doesn't have mean calculated. 

Will look into the SV data also.
