### ISSUE TITLE
missing z-score profile

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#117]
![image](https://user-images.githubusercontent.com/840895/32963523-427e6fd6-cb9e-11e7-83d9-4a2ee6e9add7.png)

**Comment by ritikakundra** [comment]
@jjgao This dataset was brought up before on this issue:
https://github.com/cBioPortal/datahub/issues/64

We noticed these are not Z scores. So we converted the metafile format to continuous. You can see them in plots and co-expression

**Comment by jjgao** [comment]
@ritikakundra let's create a z-score profile for this study?
