### ISSUE TITLE
allele frequency missing for msk_impact_2017

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#118]
It looks like we the read count info is missing in the msk_impact_2017 study. @ritikakundra do you know if we never received that? We should try to add that data.

**Comment by ritikakundra** [comment]
@jjgao Yes, this is on my radar. Should be out on Wednesday.

**Comment by jjgao** [comment]
Great. Thanks! @ritikakundra

**Comment by jjgao** [comment]
@ritikakundra any update?

**Comment by ritikakundra** [comment]
@jjgao: This is fixed:
http://www.cbioportal.org/case.do?#/patient?sampleId=P-0000004-T01-IM3&studyId=msk_impact_2017
