### ISSUE TITLE
Metastatic Prostate Adenocarcinoma (SU2C/PCF Dream Team, PNAS 2019) does have RNAseq data

### ISSUE THREAD

**Issue by rocanja** [cBioPortal/datahub#1189]
On the 'Data Sets' page, project 'Metastatic Prostate Adenocarcinoma (SU2C/PCF Dream Team, PNAS 2019)' - Abida et al PNAS 2019 is listed as having 0 RNAseq samples, when in fact it does contain 266 mRNAseq and 208 captureRNAseq data.

**Comment by jjgao** [comment]
@cBioPortal/curation rnaseq case lists are missing.

**Comment by rmadupuri** [comment]
case lists are added. 
<img width="906" alt="Screen Shot 2020-08-19 at 8 16 40 AM" src="https://user-images.githubusercontent.com/34350829/90639514-628e8a80-e1f4-11ea-8ab1-cbe5da34de01.png">
