### ISSUE TITLE
Metastatic Prostate Adenocarcinoma (MCTP, Nature 2012) is missing microarray data

### ISSUE THREAD

**Issue by rocanja** [cBioPortal/datahub#1190]
On the 'Data Sets' page, project 'Metastatic Prostate Adenocarcinoma (MCTP, Nature 2012)' - Grasso et al Nature 2012 is listed as having 94 tumor mRNA microarray data associated with it, however, when querying the data set, no expression data comes up in the 'Select Genomic Profiles' field ... possibly related to issue [#1791](https://github.com/cBioPortal/cbioportal/issues/1791).

**Comment by jjgao** [comment]
@cBioPortal/curation this was due to the mrna case list created in the study, but there is not mRNA profile. Please double check - if there should be no mrna profiles, please remove the case list as well.

![image](https://user-images.githubusercontent.com/840895/88483518-69e4b000-cf36-11ea-8e42-090132f391b8.png)

**Comment by yichaoS** [comment]
@jjgao Question with this issue: We did not have the mRNA expression file for this study, but we somehow have the zscore file. I searched through history seems like there's no mRNA expression data ever added. The mRNA case list displayed is actually for the z-score file. But my understanding is (please correct me if I'm wrong!), since we don't have the exp file itself, the data is not displayed in results. Please let me know what we should do here?

**Comment by yichaoS** [comment]
@jjgao Was looking into the publication, the expression data wasn't provided there. It is mentioned that the data is in https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE35988.

In supplemental info: 
"Gene Expression Microarray Analysis .... The final data set (including benign prostate,
localized prostate cancer and CRPC) was uploaded into a custom instance of Oncomine for
automated analysis. In Oncomine, the dataset was median centered (per array) prior to indicated
analyses. Copy number and gene expression data is also available from GEO (GSE35988). "

**Comment by rocanja** [comment]
Thank you so much for looking into this, it's greatly appreciated.

If there is time and resources, it would be fantastic if the gene
expression data from the GEO (GSE35988) entry could be added into
cBioportal, since the Grasso et al 2012 data set is one of the 'gold
standard' data sets in the field of prostate cancer research. And combined
with the great mining, analysis and visualisation tools of cBioportal,
mining this data set will be much easier for a broader audience as compared
to the GEO data base, which 'only' provides the data set itself.

However, I do appreciate that this will require some work and thus, as an
alternative, if you could just correct the entry in the 'Datasets' view,
which currently indicates that there is microarray data from 94 samples
available, so it's not misleading to users. Or, if you do have the
z-score data in a format that is easy to implement into cBioportal, if you
could at least provide this data, I am sure it will be greatly appreciated
by the prostate cancer research community.

Kind regards,
Anja

Anja Rockstroh | Post-Doctoral Research Fellow | Queensland University of
Technology (QUT) | Australian Prostate Cancer Research Centre – Queensland
(APCRC-Q) |Institute of Health and Biomedical Innovation (IHBI) | Princess
Alexandra Hospital (PAH) | Translational Research Institute (TRI) |
Brisbane, QLD , Australia | anja.rockstroh@qut.edu.au | P 07 3443 7277 | M
0449 131 711

[image: image.png]


[image: image.png]

__________________________________________________________________________________________________

**Comment by yichaoS** [comment]
@rocanja Thanks for your comments! We temporarily removed the mRNA case list as you suggested since it's misleading. We will try to add the mRNA data with our best effort. This follow up is captured and can be tracked in this new issue here:  https://github.com/cBioPortal/datahub/issues/1227
