### ISSUE TITLE
Contributing without downloading all first

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/datahub#12]
Would be good to document the --skip-smudge option to help people that just want to upload a new file (without having to download all first)

--skip-smudge : https://github.com/github/git-lfs/blob/master/docs/man/git-lfs-install.1.ronn

**Comment by pieterlukasse** [comment]
And if you want to change an individual file, you can download just that one. E.g. 
```
git lfs fetch -I public/uvm_tcga.tar.gz
```

**Comment by pieterlukasse** [comment]
@zheins

**Comment by sandertan** [comment]
This is explained in the README.md
