### ISSUE TITLE
Mutation file contains invalid Validation_Status

### ISSUE THREAD

**Issue by dionnezaal** [cBioPortal/datahub#120]
When loading TCGA provisional studies hnsc_tcga, luad_tcga, lusc_tcga, prad_tcga, skcm_tcga, thca_tcga and ucs_tcga I encountered an invalid value for the validation status which is "---". 
This validation status is not described in the official [MAF documentation](https://wiki.nci.nih.gov/display/TCGA/Mutation+Annotation+Format+(MAF)+Specification#MutationAnnotationFormat(MAF)Specification-SomaticMAFvs.ProtectedMAF) and therefore probably not loaded correctly (show "---" instead of another validation status symbol).

<img width="1211" alt="screen shot 2017-11-22 at 3 57 40 pm" src="https://user-images.githubusercontent.com/1343609/33133718-ecf2b546-cf9d-11e7-9d8b-b786cdf225e3.png">

**Comment by pieterlukasse** [comment]
@dionnezaal please update the study to the valid empty value code (e.g. "NA" or just empty "") and make a PR to datahub. Thanks.

**Comment by n1zea144** [comment]
Yes, it sounds like an issue with the data as it came out of firehose.

**Comment by sandertan** [comment]
@n1zea144 Could you check if we can fix the firehose output? I already solved this a while back in https://github.com/cBioPortal/datahub/pull/39 for `skcm_tcga` but it seems this was overwritten.

**Comment by dionnezaal** [comment]
When continuing loading the TCGA provisional studies also encountered Validation Status with value "---" in pcpg_tcga. In coadread_tcga a Validation status with value "Wildtype" was encountered.

**Comment by pieterlukasse** [comment]
Decisions:
- @sandertan: make a warning for validation status "Wildtype" (or other invalid values)
- @yichaoS : clean-up the "---" cases (fix not only the data by also the firehose script? )

**Comment by ritikakundra** [comment]
coadread_tcga.tar.gz
hnsc_tcga.tar.gz
luad_tcga.tar.gz
lusc_tcga.tar.gz
meso_tcga.tar.gz
pcpg_tcga.tar.gz
prad_tcga.tar.gz
skcm_tcga.tar.gz
thca_tcga.tar.gz
ucs_tcga.tar.gz

**Comment by yichaoS** [comment]
@ritikakundra @pieterlukasse @jjgao @dionnezaal Should "mixed" "SNP" be allowed as well?

**Comment by pieterlukasse** [comment]
@yichaoS do you mean `mixed` and `SNP` as `Validation_Status` values?

**Comment by yichaoS** [comment]
Yes, and this is all the values we have right now in public studies
![screen shot 2017-12-18 at 3 24 23 pm](https://user-images.githubusercontent.com/5973438/34126470-a845c662-e407-11e7-8560-519beb9b1233.png)

**Comment by dionnezaal** [comment]
Solved by PR #143
