### ISSUE TITLE
Curated non-redundant studies list contains a study thats not available in public portal

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/datahub#1211]
Seems that skcm_ucla_2016 is in the curated non-redundant studies list in public portal, but it's also not accessible in the public portal.

**Comment by jjgao** [comment]
I think the study was renamed: https://www.cbioportal.org/study/summary?id=mel_ucla_2016. 

@cBioPortal/curation would you please confirm and update the default study list?

**Comment by rmadupuri** [comment]
Was fixed in https://github.com/knowledgesystems/knowledgesystems-k8s-deployment/pull/86
