### ISSUE TITLE
Provisional TCGA study ov_tcga unpacks in ov_tcga instead of ov/tcga

### ISSUE THREAD

**Issue by dionnezaal** [cBioPortal/datahub#122]
All TCGA provisional studies unpack after downloaded from datahub in [study]/tcga except for one study ov_tcga which unpacks as ov_tcga folder. For automation purposes it would be nice if all TCGA provisional studies unpack in the same way.

**Comment by pieterlukasse** [comment]
This will be solved by @yichaoS when she reorganises all the studies again as plain folders.

**Comment by dionnezaal** [comment]
Solved in PR #143. All tcga provisional studies now unpack as: `[study]_tcga`.
