### ISSUE TITLE
Add CPTAC data to PanCancer Atlas studies

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#1235]
Let's copy the CPTAC mass spec data to the PanCancer Atlas studies for ov, coadread, and brca.

**Comment by rmadupuri** [comment]
**Data source:**

Proteome and Phosphoproteome Site Level expression data from CPTAC (for TCGA brca, coadread and ov) are available in  linkedomics -  http://linkedomics.org/login.php

BRCA: http://linkedomics.org/data_download/TCGA-BRCA/
COADREAD: http://linkedomics.org/data_download/TCGA-COADREAD/
OV: http://linkedomics.org/data_download/TCGA-OV/

**Proteome:** files used
brca and coadread - Proteome (Gene level) 
ov - Proteome (JHU, Gene level)

**Phosphoproteome:**
brca and ov - Phosphoproteome (Site level) - data added in generic assay format.
