### ISSUE TITLE
Validator Issue: Allow CNA file to have cytoband column

### ISSUE THREAD

**Issue by ritikakundra** [cBioPortal/datahub#124]
The validator should not fail if cytoband is mentioned in the CNA file. Currently, validator treats it as a sample ID and fails since it can't find it in the clinical file. 
![screen shot 2017-11-28 at 2 37 07 pm](https://user-images.githubusercontent.com/12007862/33340431-1226b8e8-d44a-11e7-83d5-1813887cb663.png)

**Comment by yichaoS** [comment]
I'll remove all the cytoband columns in CNA and expression files as discussed today.
