### ISSUE TITLE
questions on acyc_mskcc_2013 mutation data

### ISSUE THREAD

**Issue by jcgu** [cBioPortal/datahub#1240]
Hi MSKCC team,

I'm interested in using the acyc_mskcc_2013 mutation data, specially the data_mutations_extended.txt file [here](https://github.com/cBioPortal/datahub/commits/master/public/acyc_mskcc_2013/data_mutations_extended.txt)

The data was initially committed on July 16, 2018. Then two changes were made in 2018 and 2019 by rmadupuri. Could you point me to documentations on what changes were made and why?

Thank you,
Jason

Please keep this checklist for curation of a new study.

- [ ] [create an issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [ ] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [ ] Document the curation process, e.g. how and by whom the data was transformed
- [ ] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [ ] Create a pull request to datahub once the data is curated
- [ ] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update the default quick select study list see https://github.com/cBioPortal/cbioportal/issues/5831 (only for studies that are not overlapping with existing ones; only for human tumors, not cell lines)
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

**Comment by jjgao** [comment]
@jcgu I think they are for re-annotating the files with our annotation pipeline and sync up with our internal data repo.
