### ISSUE TITLE
why do we have mutations outside of gene panel for msk_impact_2017

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#125]
http://www.cbioportal.org/index.do?session_id=59a9a467498e5df2e294bee3

![image](https://user-images.githubusercontent.com/840895/33357388-cdf8fc58-d48f-11e7-8b08-ecdbb7690010.png)

**Comment by jjgao** [comment]
might be related to https://github.com/cBioPortal/cbioportal/issues/3458

**Comment by ritikakundra** [comment]
This is fixed now:
http://www.cbioportal.org/index.do?session_id=59a9a467498e5df2e294bee3&show_samples=false&
