### ISSUE TITLE
Migrate timeline STATUS data

### ISSUE THREAD

**Issue by inodb** [cBioPortal/datahub#1262]
We are planning to remove the frontend feature to automatically put OS_MONTHS from a patient as a black dot in the STATUS channel. Instead, it is required now to add this to the treatment data before import. That is, it has to be added to the `data_timeline_status.txt` file. The value can be set to `DECEASED`. This will require the following studies to be updated:

- [ ] `lgg_ucsf_2014`
- [ ] `gbm_columbia_2019`
- [ ] `thyroid_mskcc_2016`
- [ ] `mel_tsam_liang_2017`
- [ ] `sclc_cancercell_gardner_2017`

See also code here: https://github.com/cBioPortal/cbioportal-frontend/blob/4ca7d23d6879509cadfa9ca5102508e33ebe02e3/src/pages/patientView/timeline/legacy.js#L225-L246. Originally we multiplied OS_MONTHS by `30.4`, so we can do the same for the data files

**Comment by sbabyanusha** [comment]
@inodb should we start migrating the timeline status data for the above listed studies?

**Comment by inodb** [comment]
@sbabyanusha yes please - the current production timeline for e.g. https://www.cbioportal.org/patient?studyId=lgg_ucsf_2014&caseId=P04 is no longer showing deceased status. Thanks!

**Comment by sbabyanusha** [comment]
Sure @inodb . Will incorporate this in our coming scrum.
