### ISSUE TITLE
MSK-IMPACT gene panel genes missing in data file

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/datahub#127]
1. ABRAXAS1 is missing from the genes in `data_gene_panel_impact341.txt` and `data_gene_panel_impact410`. AMER1 also seems to be missing. I have not checked the other genes.

<img width="1277" alt="screen shot 2017-12-01 at 10 06 49" src="https://user-images.githubusercontent.com/9624990/33476607-dc09b2b6-d682-11e7-9b6f-1fe7f7776b99.png">

2. FAT3 is not in the gene panel list, and therefore listed as 'not sequenced', but it has a fusion with EED. Is this caused by FAT3 not being on the panel but sequenced because it is fused to EED?

<img width="896" alt="screen shot 2017-12-01 at 10 29 52" src="https://user-images.githubusercontent.com/9624990/33476594-d187bbd0-d682-11e7-81eb-9a0072bed657.png">

ABL1 not showing up in the list of genes contained in the gene panel seems a code issue. This is reported in https://github.com/cBioPortal/cbioportal/issues/3485

**Comment by ritikakundra** [comment]
@sandertan Regarding the first two missing genes:
FAM175A is an alias for ABRAXAS1 and
FAM123B is an alias for AMER1 
Both are in 341 and 410 files.

FAT3 is not part of any panel and is only a partner for this fusion. 

You are right ABL1 is in data files.

**Comment by jjgao** [comment]
@adamabeshouse could you try to found out why ABL1 is not showing up?

**Comment by adamabeshouse** [comment]
I'm pretty sure its an HTML issue which I fixed in the refactor, let me confirm and fix it in legacy.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal/pull/3492
