### ISSUE TITLE
Merge `CDKN2AP14ARF` and `CDKN2AP16INK4A` into `CDKN2A`

### ISSUE THREAD

**Issue by yichaoS** [cBioPortal/datahub#1274]
Part of `gene table clean up` issue: https://github.com/cBioPortal/datahub/issues/540

Merge `CDKN2AP14ARF` and `CDKN2AP16INK4A` into `CDKN2A`
For all impact studies in all profiles.(If detected in other studies as well, further confirmation needed)

Certain rules maybe applied if values are different between records e.g. 'amp' over 'diploid'; Might need further discussion for ambiguous cases)

cc' @ritikakundra

**Comment by ritikakundra** [comment]
We have a script for this merge. Maybe @yichaoS we need to check how many studies are affected by this issue and just run the script on them?

**Comment by yichaoS** [comment]
@ritikakundra This merge is part of the data files cleaning up for us updating the gene tables. I think we can close this issue - it will be resolved automatically once we updated the gene tables & data files.
