### ISSUE TITLE
RNASeq data

### ISSUE THREAD

**Issue by MustafaKarabulut** [cBioPortal/datahub#1282]
Hi,
I've downloaded and imported the MySQL dump file into my local database instance.

I've been exploring the data for a while to understand how the data is stored across multiple tables.

So far, I am able to understand how most of the data is stored within tables and relationships between those (e.g., patients, samples, clinical data, mutations, CNAs)

However, I could not find where RNASeq data is stored (e.g., expression levels, z-scores etc). This information is available through cBioPortal website. I assume it is stored in the database.

I've inspected the database diagram provided over https://docs.cbioportal.org/4.-development/cbioportal-er-diagram as well as actual data in the tables. No luck so far.

Can anyone help me or point me to right direction?

**Comment by jjgao** [comment]
@MustafaKarabulut the expression data is stored in the `genetic_alteration` & `genetic_profile_samples` tables.

![image](https://user-images.githubusercontent.com/840895/94855130-09716380-03fc-11eb-80e0-95ee6b7a7835.png)
