### ISSUE TITLE
missing survival data for acc_tcga

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#129]
http://www.cbioportal.org/study?id=acc_tcga#summary

**Comment by ritikakundra** [comment]
@jjgao The clinical file is empty for OS_MONTHS and DFS_MONTHS
Is it ok to use:

DAYS_TO_DEATH And | DAYS_LAST_FOLLOWUP for OS computing (both calculated from Initial Pathologic Diagnosis)

**Comment by jjgao** [comment]
Yes. Not sure why they were not converted? @angelicaochoa

**Comment by jjgao** [comment]
related to https://github.com/cBioPortal/datahub/issues/130

**Comment by ritikakundra** [comment]
Study has survival data
