### ISSUE TITLE
issue with gbm_tcga_pub

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#1290]
I was not able to load https://www.cbioportal.org/study/summary?id=gbm_tcga_pub

The API was not able to find the study:
![image](https://user-images.githubusercontent.com/840895/95094396-db3f9c80-06f7-11eb-9446-763350e6b92c.png)

When trying to query the study, I got the errors below:
![image](https://user-images.githubusercontent.com/840895/95094324-c6fb9f80-06f7-11eb-8472-836454cba019.png)

**Comment by rmadupuri** [comment]
The study is back online @jjgao.
