### ISSUE TITLE
missing OS_MONTHS

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#130]
In https://github.com/cBioPortal/cbioportal/issues/3503, we noticed that three samples (TCGA-04-1357, TCGA-04-1360 and TCGA-24-0968) in ov_tcga have OS_STATUS but no OS_MONTHS.

I did an SQL query in public portal and found more cases like that include `msk_impact_2017`. @yichaoS @ritikakundra Is this known? 

```sql
select cs.`CANCER_STUDY_IDENTIFIER`, count(distinct p.`INTERNAL_ID`) as `patients`
from clinical_patient cp, patient p, cancer_study cs
where attr_id='os_status'
and cp.`INTERNAL_ID`=p.`INTERNAL_ID`
and p.`CANCER_STUDY_ID`=cs.`CANCER_STUDY_ID`
and cp.internal_id not in (
	select internal_id
	from clinical_patient
	where attr_id='os_months'
)
group by cs.`CANCER_STUDY_ID`
order by patients desc
```

```
msk_impact_2017	2761
crc_msk_2017	978
gct_msk_2016	180
pcpg_tcga	178
acc_tcga	91
meso_tcga	86
thca_tcga_pub	77
coadread_mskcc	69
stad_tcga_pub	65
ucs_tcga	56
npc_nusingapore	50
blca_mskcc_solit_2012	45
urcc_mskcc_2016	39
mbl_pcgp	37
gbc_shanghai_2014	32
es_dfarber_broad_2014	24
stad_uhongkong	22
mbl_icgc	22
luad_tcga_pub	20
nsclc_tcga_broad_2016	19
laml_tcga	14
acbc_mskcc_2015	12
prad_mich	11
uvm_tcga	11
kich_tcga_pub	11
skcm_tcga	9
luad_tcga	9
stad_tcga	8
lusc_tcga	6
ov_tcga	3
kirc_tcga_pub	3
brca_tcga	2
chol_tcga	2
ov_tcga_pub	2
brca_tcga_pub2015	2
egc_tmucih_2015	2
blca_tcga	2
coadread_tcga	2
gbm_tcga_pub	2
hnsc_tcga	2
kirp_tcga	1
gbm_tcga	1
sclc_ucologne_2015	1
thym_tcga	1
ucec_tcga	1
blca_plasmacytoid_mskcc_2016	1
mbl_sickkids_2016	1
lgg_tcga	1
kich_tcga	1
skcm_ucla_2016	1
```

**Comment by ersinciftci** [comment]
Same thing applies also to `DFS_MONTHS` and `DFS_STATUS`.

**Comment by sbabyanusha** [comment]
Updated list of studies missing OS_MONTHS in public portal

msk_impact_2017	2761
all_phase2_target_2018_pub	180
gct_msk_2016	180
pcpg_tcga	179
crc_msk_2017	118
meso_tcga	87
thca_tcga_pub	77
stad_tcga_pub	65
ucs_tcga	57
blca_mskcc_solit_2012	45
urcc_mskcc_2016	39
mbl_pcgp	37
gbc_shanghai_2014	32
nsclc_tcga_broad_2016	28
es_dfarber_broad_2014	24
mbl_icgc	22
luad_tcga_pub	20
laml_tcga	14
laml_tcga_pan_can_atlas_2018	14
uvm_tcga	12
prad_mich	11
utuc_mskcc_2015	11
luad_tcga	9
luad_tcga_pan_can_atlas_2018	9
skcm_tcga	9
aml_ohsu_2018	8
kich_tcga_pub	8
skcm_tcga_pan_can_atlas_2018	8
stad_tcga	8
lusc_tcga	6
lusc_tcga_pan_can_atlas_2018	6
skcm_tcga_pub_2015	6
stad_tcga_pan_can_atlas_2018	5
blca_msk_tcga_2020	3
kirc_tcga_pub	3
ov_tcga	3
ov_tcga_pan_can_atlas_2018	3
blca_tcga	2
blca_tcga_pub_2017	2
brca_tcga	2
brca_tcga_pub2015	2
chol_tcga	2
coadread_tcga	2
egc_tmucih_2015	2
hnsc_tcga	2
luad_oncosg_2020	2
ov_tcga_pub	2
acc_2019	1
blca_plasmacytoid_mskcc_2016	1
blca_tcga_pan_can_atlas_2018	1
brca_tcga_pan_can_atlas_2018	1
coadread_tcga_pan_can_atlas_2018	1
cscc_hgsc_bcm_2014	1
gbm_tcga	1
hnsc_tcga_pan_can_atlas_2018	1
kich_tcga	1
kirp_tcga	1
kirp_tcga_pan_can_atlas_2018	1
lgg_tcga	1
lgg_tcga_pan_can_atlas_2018	1
lihc_tcga	1
lihc_tcga_pan_can_atlas_2018	1
mbl_sickkids_2016	1
mel_ucla_2016	1
meso_tcga_pan_can_atlas_2018	1
rt_target_2018_pub	1
sclc_ucologne_2015	1
thym_tcga	1
thym_tcga_pan_can_atlas_2018	1
ucec_tcga	1
ucec_tcga_pan_can_atlas_2018	1

**Comment by sbabyanusha** [comment]
Looked into this issue but couldn't find any os_months data for those samples.

**Comment by jjgao** [comment]
@sbabyanusha I am wondering if we have the time of last followup for the patients with os_status living? If so, os_months should be same as the followup time.
