### ISSUE TITLE
wrong description of the rna-seq profile for mel_ucla_2016?

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#1304]
In [mel_ucla_2016_all](https://www.cbioportal.org/results/plots?Action=Submit&cancer_study_list=mel_ucla_2016&case_set_id=mel_ucla_2016_all&gene_list=PCLO%250ALRP1B&tab_index=tab_visualize), the description of the RNA-seq profile says it was FPKM but the data looks more like read counts (all integers).

![image](https://user-images.githubusercontent.com/840895/96639428-b4848700-12ef-11eb-8c19-f837e349085b.png)

related thread: https://groups.google.com/g/cbioportal/c/3XwAL32c0B0

**Comment by sentisci** [comment]
This issue is true for multiple studies that I have downloaded. For example Melanoma_Snyder_et_al, Melanoma_Vanallen_et_al

**Comment by jjgao** [comment]
Thanks, @sentisci. 

@rmadupuri it may be a good idea to query the database for cases like this.
