### ISSUE TITLE
Source of CCLE treatment response

### ISSUE THREAD

**Issue by bynjh007** [cBioPortal/datahub#1309]
Hi,

I am using CCLE data  (Broad 2019) deposited in cBioPortal to associate genomic feature with treatment response.

Maybe I missed it, but I cannot find the information how treatment responses (AUC, IC50, ZScore) for CCLE cell lines has been obtained. It is said the data was downloaded from CCLE database but I cannot find that information in the database (https://portals.broadinstitute.org/ccle/data)

Braod drug response data was generated by CTRPv2 most recently, but the list of the drug is not matched to CCLE ones, so I would like to know more about the treatment response data that I am using now.

Best

**Comment by Sjoerd-van-Hagen** [comment]
@SRodenburg Sander, can you answer the question above?

Perhaps we can also update the documentation for this study.

**Comment by SRodenburg** [comment]
@pvannierop Handed me this data in person when I first joined last year.

**Comment by pvannierop** [comment]
I remember that at the time of me working with this data, there were simply datafiles for each AUC, IC50, etc. I do not remember how the values that are currently in the study (2019 version) have been extracted. Perhaps @ritikakundra knows.

**Comment by SRodenburg** [comment]
I think it was Ritika asking this question in the cbioportal slack.

**Comment by Sjoerd-van-Hagen** [comment]
I am guessing Pim downloaded the files from the CCLE website then.

--

E.   sjoerd@thehyve.nl

T.   +31(0)30 700 9713

W.  www.thehyve.nl

**Comment by pvannierop** [comment]
@Sjoerd-van-Hagen @bynjh007 @SRodenburg I case you missed this update of the previous message:

**Comment by SRodenburg** [comment]
https://data.broadinstitute.org/ccle_legacy_data/pharmacological_profiling/
