### ISSUE TITLE
issue with methylation data for tcga_ov

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#1313]
The [TCGA Ov Firehose Legacy study](https://www.cbioportal.org/study/summary?id=ov_tcga) only has 10 samples with methylation date, but in [Firehose](http://firebrowse.org/?cohort=OV#), 594 ov samples have methylation data.

![image](https://user-images.githubusercontent.com/840895/97584800-cb516a80-19ce-11eb-9ba3-815a7f430aeb.png)

**Comment by yichaoS** [comment]
@jjgao After looking into the files on firehose, it turns out that for hm27 they have ~550 samples, and for hm450, which is the profile we currently have, it is actually 10 samples only. 
Could you please let us know if we want to include the hm27 in `ov_tcga`?
