### ISSUE TITLE
cBioPortalData function call cBioDataPack() error message

### ISSUE THREAD

**Issue by ryao-mdanderson** [cBioPortal/datahub#1338]
Hello,

I uses R/4.0.0 with Bioconductor verison 3.11, 
R
> packageVersion("cBioPortalData")
[1] ‘2.0.10’
> cbio <- cBioPortal()
> laml <- cBioDataPack("laml_tcga")
Study file in cache: laml_tcga
Working on: /tmp/RtmpCBSQek/136c70be6467_laml_tcga/data_cna_hg19.seg
........
See spec(...) for full column specifications.
Parsed with column specification:
cols(
  .default = col_character()
)
See spec(...) for full column specifications.
Error in .local(x, ...) : strand values must be in '+' '-' '*'
In addition: Warning messages:
1: In .find_seqnames_col(df_colnames0, seqnames.field0, xfix) :
  cannnot determine seqnames column unambiguously
2: In .find_seqnames_col(df_colnames0, seqnames.field0, xfix) :
  cannnot determine seqnames column unambiguously
3: In .find_seqnames_col(df_colnames0, seqnames.field0, xfix) :
  cannnot determine seqnames column unambiguously

May you please advise what can be the reason causing the error?

Thank you !
Rong

**Comment by jjgao** [comment]
@SRodenburg would you please contact our support email at cbioportal@googlegroups.com? Thanks.
