### ISSUE TITLE
Discrepancy FireBrowse, cBioPortal and ICGC

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/datahub#135]
I noticed there's a difference in the TCGA BLCA study between FireBrowse, cBioPortal and ICGC. @n1zea144 could the data we have in cBioPortal and on Datahub receive an update or is additional processing the reason there are less mutations in cBioPortal?

I couldn't find any info on processing of TCGA -> ICGC data, but I guess there are some filters there.

### Firebrowse
196 of 388 samples (51%)
![screen shot 2017-12-12 at 10 36 06](https://user-images.githubusercontent.com/9624990/33878215-0a20756c-df2b-11e7-987f-1d44975e4a47.png)

### cBioPortal
64 of 238 samples (27%) 
![screen shot 2017-12-12 at 10 46 01](https://user-images.githubusercontent.com/9624990/33878230-1997d18e-df2b-11e7-8a69-f536f69bce52.png)

### ICGC
12 / 133 samples (9%)
![screen shot 2017-12-12 at 10 34 23](https://user-images.githubusercontent.com/9624990/33878086-b8741b2e-df2a-11e7-93a7-e114cb647559.png)

**Comment by pieterlukasse** [comment]
@jjgao @schultzn any ideas why such big differences?

**Comment by schultzn** [comment]
Is there possibly something wrong with the case list for sequenced cases? If I go to grace.broadinstitute.org, from where we got the MAF, I see 130 sequenced cases. It is this file:
http://gdac.broadinstitute.org/runs/stddata__2016_01_28/data/BLCA/20160128/gdac.broadinstitute.org_BLCA.Mutation_Packager_Calls.Level_3.2016012800.0.0.tar.gz <http://gdac.broadinstitute.org/runs/stddata__2016_01_28/data/BLCA/20160128/gdac.broadinstitute.org_BLCA.Mutation_Packager_Calls.Level_3.2016012800.0.0.tar.gz>

**Comment by jjgao** [comment]
@ritikakundra and @angelicaochoa: could you look into @schultzn's questions? Thanks.

**Comment by ritikakundra** [comment]
This has been fixed
