### ISSUE TITLE
Migrate pipeline software to pipelines2

### ISSUE THREAD

**Issue by n1zea144** [cBioPortal/datahub#1354]
The following software resides on pipelines that need to move to pipelines2:

https://docs.google.com/spreadsheets/d/1r-maKjTkMcMo2KUns1wDF_m40Ai8a5BbcuIDjmNTKr0/edit#gid=978000492

**Comment by sheridancbio** [comment]
This issue was created erroneously in the datahub repo. A replacement has been created here: https://github.com/knowledgesystems/pipelines-scrum/issues/482
