### ISSUE TITLE
MEL_DFCI_2019 study has incomplete RNA expression data

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/datahub#1397]
Reported by Danny 
"Khalil, Danny N./Medicine" <khalild@mskcc.org>

 It looks like there is an issue with the RNA-Seq data: The underlying expression matrix only includes genes starting with the letters A-S (SLC26A5 is the last gene included alphabetically), so it looks like this got truncated somehow.

**Comment by sbabyanusha** [comment]
The changes has been updated in this PR- https://github.com/cBioPortal/datahub/pull/1399 and it will soon be merged into public.
