### ISSUE TITLE
TCGA PanCancer Atlas expression - is endometrial cancer properly normalized?

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/datahub#1400]
Endometrial cancer samples seem to consistently have lower expression of many genes than other cancer types. Is this real or potentially a normalization flaw in the data?

See this example:
https://www.cbioportal.org/results/plots?cancer_study_list=laml_tcga_pan_can_atlas_201[…]logScale%22%3A%22true%22%7D&plots_coloring_selection=%7B%7D

**Comment by ritikakundra** [comment]
@schultzn The link is not loading, can you reshare the link?
