### ISSUE TITLE
Release of arm-level CNA data

### ISSUE THREAD

**Issue by dippindots** [cBioPortal/datahub#1401]
- [x] Review and merge plots tab implementation: cBioPortal/cbioportal-frontend#3694
- [x] Update data based on the product team feedback
- [x] Remove arm-level cna data from clinical file: `data_clinical_sample.txt`
- [x] Release (Update news?)

**Comment by ritikakundra** [comment]
@dippindots @BabyASatravada Should we expand this to all TCGA studies now? I think this is just for ACC (right @BabyASatravada ?)

**Comment by sbabyanusha** [comment]
@ritikakundra yes, I have created test datafile just for ACC as of now.

**Comment by dippindots** [comment]
Just asked JJ about `Should we expand this to all TCGA studies?`.
@ritikakundra @BabyASatravada If expanding to all TCGA studies not too difficult(hopefully...), maybe we can wait until we finished the second task in the issue description. I think we are expecting some text change requests.
