### ISSUE TITLE
cancer type inconsistency

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/datahub#1405]
user reported: https://groups.google.com/g/cbioportal/c/fzBbU7pkSfQ

User queried CDH1 in all curated non-redundant studies and found some confusing results in terms of the number of samples with 'Bladder Urothelial Carcinoma' when viewing the Cancer Types Summary tab by 'Cancer Type' vs 'Cancer Type Detailed'.

Here are those same CDH1 altered samples in Study View: https://www.cbioportal.org/study?id=6081ee0ae4b0242bd5d49de0
Filter to Cancer Type Detailed = Bladder Urothelial Carcinoma (47 samples)

![image](https://user-images.githubusercontent.com/10508276/115789042-7ea18780-a392-11eb-94b1-2e39b77d6cdb.png)

This results in 2 Cancer Types. Cancer Type=Bladder Urothelial Carcinoma is from blca_tcga_pan_can_atlas_2018 while Cancer Type = Bladder Cancer is all those other studies.

I had always thought Cancer Type was the OncoTree Main Type. If so, shouldn't the PanCan data have Cancer Type = Bladder Cancer ?

**Comment by ritikakundra** [comment]
In addition to this issue, we should also query the database to find cancer type and cancer type detailed pairs and identify detailed tumor types that map to multiple cancer type and fix that
