### ISSUE TITLE
TCGA PanCancer Atlas: Ancestry data

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#1426]
https://www.cell.com/cancer-cell/fulltext/S1535-6108(18)30379-9

add as generic assay?

Test Study: https://triage.cbioportal.mskcc.org/study/summary?id=acc_tcga_pan_can_atlas_2018

**Comment by sbabyanusha** [comment]
@jjgao I found a more recent [paper](https://www.sciencedirect.com/science/article/pii/S1535610820302117?via%3Dihub#mmc2) for genetic ancestry. The data is readily available in the [GDC portal](https://gdc.cancer.gov/about-data/publications/CCG-AIM-2020). We were wondering if we can use the data from this paper. Or any other source that you prefer us to look into?
