### ISSUE TITLE
Loading data from normal sample data of Datahub studies breaks portal

### ISSUE THREAD

**Issue by pvannierop** [cBioPortal/datahub#1440]
# Problem
Data related to 'normal samples' part of public studies breaks the portal with an API error.

#  Steps to reproduce
- Set up portal v 3.6.19
- Download and load [https://cbioportal-datahub.s3.amazonaws.com/brca_tcga_pan_can_atlas_2018.tar.gz](https://cbioportal-datahub.s3.amazonaws.com/brca_tcga_pan_can_atlas_2018.tar.gz)
- Open [Results View with TP53 gene as query](/results/oncoprint?genetic_profile_ids_PROFILE_MUTATION_EXTENDED=brca_tcga_pan_can_atlas_2018_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=brca_tcga_pan_can_atlas_2018_gistic&cancer_study_list=brca_tcga_pan_can_atlas_2018&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&profileFilter=0&case_set_id=brca_tcga_pan_can_atlas_2018_cnaseq&gene_list=TP53&geneset_list=%20&tab_index=tab_visualize&Action=Submit)

# Proposed change
Prevent study importer to load normal samples for now.

**Comment by pvannierop** [comment]
@yichaoS For the link go to your portal domain (e.g. http://localhost:8080) and add:

```
/results/oncoprint?genetic_profile_ids_PROFILE_MUTATION_EXTENDED=brca_tcga_pan_can_atlas_2018_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=brca_tcga_pan_can_atlas_2018_gistic&cancer_study_list=brca_tcga_pan_can_atlas_2018&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&profileFilter=0&case_set_id=brca_tcga_pan_can_atlas_2018_cnaseq&gene_list=TP53&geneset_list=%20&tab_index=tab_visualize&Action=Submit
```

**Comment by yichaoS** [comment]
@pvannierop This query result loaded currently on our public portal here (the study is imported to public DB with the latest datahub data)
```
https://www.cbioportal.org/results/oncoprint?genetic_profile_ids_PROFILE_MUTATION_EXTENDED=brca_tcga_pan_can_atlas_2018_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=brca_tcga_pan_can_atlas_2018_gistic&cancer_study_list=brca_tcga_pan_can_atlas_2018&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&profileFilter=0&case_set_id=brca_tcga_pan_can_atlas_2018_cnaseq&gene_list=TP53&geneset_list=%20&tab_index=tab_visualize&Action=Submit
``` 
What do you refer as `study loader` exactly? 

I can confirm the data files themselves are correct and validator is update to date and all our studies passed validation (we do this weekly)
```
https://app.circleci.com/pipelines/github/cBioPortal/datahub/1644/workflows/2f7f8be5-18cc-4c91-8f06-939afb3c2172/jobs/6794
```
We don't run the validator within the importer itself when importing a study to our database - but our importer skips importing of the `_normals.txt` files as well. (cc' @sheridancbio )
Could this be a versioning issue of the front-end/backend code? @n1zea144 @inodb

**Comment by pvannierop** [comment]
@yichaoS We import our studies with the _metaImport.py_ script.

> but our importer skips importing of the _normals.txt files as well.

Yes, but _metaImport.py_ does not, hence these files break portals provisioned with the _metaImport.py_ importer. This is almost every portal, since _metaImport.py_ is the only importer referenced in the documentation (as far as I am aware).

I guess my solution would be to update the _metaImport.py_ importer to skip __normals_ files, like you do with 'your' importer.

**Comment by n1zea144** [comment]
If its true that the presence of normal data is causing this api error, then it should be relatively easy to update the metaImport.py script to ignore normal data (assuming the filename or stable id indicates normal data).  Having said that, is skipping the import of normal samples the correct thing to do?  As far as I remember we are not ready to properly present normal data on the frontend..is this still the case?  cc: @jjgao

**Comment by yichaoS** [comment]
We moved all the normal files as @n1zea144 suggested, to a subfolder named "normals". For example: https://github.com/cBioPortal/datahub/tree/rename_files/public/brca_tcga_pan_can_atlas_2018/normals

This change is part of this PR:  https://github.com/cBioPortal/datahub/pull/1448.
Once the PR is merged, could you please do a test importing/loading of the broken studies? @PichaiRaman @oplantalech

Thanks

**Comment by yichaoS** [comment]
related changes switched to https://github.com/cBioPortal/datahub/pull/1496

**Comment by Sjoerd-van-Hagen** [comment]
This was fixed.
