### ISSUE TITLE
different sample numbers from query vs study view

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/datahub#1444]
If I query all samples in these two studies, the sample count is 1134:
![image](https://user-images.githubusercontent.com/10508276/119373233-31ad1b80-bc86-11eb-8365-d84210dddc11.png)

If I instead go to study view for those same studies, the sample count is 1149:
![image](https://user-images.githubusercontent.com/10508276/119373438-6a4cf500-bc86-11eb-8533-8a1ddd821ad4.png)

Why are those not the same number?

**Comment by yichaoS** [comment]
@kalletlak Yea, the samples in gbm_tcga cases_all is imcomplete. Regenerated the case list and will reimport gbm_tcga tonight.

**Comment by yichaoS** [comment]
@kalletlak @jjgao  I've updated the case list of gbm_tcga (cases_all has 619 samples) and the lgg_tcga case lists (530 samples) have been correct - yet the sum of sample count is still different in the `case set` selection box (1134 vs. 1149 in study view).  This reminds me of a similar issue we discussed a few weeks ago with @alisman @inodb - Could you take a look?

**Comment by kalletlak** [comment]
@yichaoS counts are matching.
