### ISSUE TITLE
Expression Data Issues....

### ISSUE THREAD

**Issue by ashraf123456789** [cBioPortal/datahub#146]
Hello,

I'm having issues uploading expression from a personal data set. My sample attributes loaded easily but my mRNA expression file didn't appear on my inhouse site. Attached is my meta expression file and a picture of the site to see what's displaying....my data set information needs to be kept private....but formatting the file has not been the issue since I followed the formatting procedures and passed through the validator...I keep getting this:

WARNING: Expression.txt: line 1: The recommended column Entrez_Gene_Id was not found. Using Hugo_Symbol for all gene parsing.
WARNING: Expression.txt: lines [5, 6, 9, (8556 more)]: Duplicate line for a previously listed feature/gene, this line will be ignored.; values encountered: ['A1CF (already defined on line 4)', 'A2BP1 (already defined on line 8)', 'A3GALT2 (already defined on line 15)', '(5716 more)']

<img width="1277" alt="screen shot 2018-01-08 at 3 34 30 pm" src="https://user-images.githubusercontent.com/33638846/34693871-cc79de40-f48a-11e7-9c1a-637951e04f3d.png">

[meta_OV_expression.txt](https://github.com/cBioPortal/datahub/files/1613149/meta_OV_expression.txt)

**Comment by sandertan** [comment]
Hi Ashraf,

`WARNING: Expression.txt: lines [5, 6, 9, (8556 more)]: Duplicate line for a previously listed feature/gene, this line will be ignored.; values encountered: ['A1CF (already defined on line 4)', 'A2BP1 (already defined on line 8)', 'A3GALT2 (already defined on line 15)', '(5716 more)']`
Can you check the data why duplicate lines are detected?

Common practice is to not display mRNA data on the Query page and OncoPrint unless it is z-scored. Also, the Study Summary view does not display a graph for it. However, it is viewable on the Plots tab. Can you query a gene for which you are sure gene expression is loaded, and check the Plots tab?

Best,
Sander

**Comment by ashraf123456789** [comment]
Thank you! What you mentioned did work. Is there a way to get the z-score from the expression file without any CNA data...?

**Comment by sandertan** [comment]
Do you have normal samples? You have to compare tumor expression values to
normal values. Else you’re comparing within the tumor set. Using z-scores
without normal values is not recommended. Z-score normalization can make
small differences show as large differences for samples with low gene
expression.

If you know what you’re doing, you can calculate such scores with any
statistical software or programming language.

**Comment by ashraf123456789** [comment]
[meta_zscore.txt](https://github.com/cBioPortal/datahub/files/1627583/meta_zscore.txt)
I preformed the z-score transform on the expression data..... and the oncoprint tab still isn't functioning, is there anything wrong with the metafile?
<img width="1258" alt="screen shot 2018-01-12 at 3 46 16 pm" src="https://user-images.githubusercontent.com/33638846/34896547-d737f858-f7af-11e7-899b-0a35b0857e2b.png">

**Comment by sandertan** [comment]
Hi @ashraf123456789 . This looks like a different problem. Did you already successfully load a TCGA study?

**Comment by ashraf123456789** [comment]
I did....I loaded a sample file, expression file, and a z-scored transformtion file, and respective meta files required...is there more data that needs to be uploaded for to get more detailed assessment on the expression data?

**Comment by sandertan** [comment]
I don't think so.

Could you open the developer console in Chrome (View -> Developer -> Developer Tools -> Console (tab), and make a screenshot of any Error (in red)?

Also, can you verify your data, to make sure everything is correct? So for the queried genes, that there are z-score values for the selected samples.

Could you send a screenshot of the validation report? If you have sensitive data/samples names in there, you could black them out with an image editor.

**Comment by ashraf123456789** [comment]
[myReport.html.zip](https://github.com/cBioPortal/datahub/files/1636150/myReport.html.zip)

<img width="1280" alt="screen shot 2018-01-16 at 11 14 16 am" src="https://user-images.githubusercontent.com/33638846/35002657-fa214f60-faaf-11e7-80b8-accd47ea0067.png">
Hi Sander,

Here you go!
<img width="1280" alt="screen shot 2018-01-16 at 11 14 04 am" src="https://user-images.githubusercontent.com/33638846/35002650-f5e0113e-faaf-11e7-8847-1beb67b909fb.png">

**Comment by ashraf123456789** [comment]
<img width="1280" alt="screen shot 2018-01-16 at 11 14 16 am" src="https://user-images.githubusercontent.com/33638846/35002760-47741af4-fab0-11e7-8bfe-f46b1132a0e0.png">


<img width="1280" alt="screen shot 2018-01-16 at 11 14 04 am" src="https://user-images.githubusercontent.com/33638846/35002749-431112fa-fab0-11e7-8d58-460f2d8543b2.png">

[myReport.html.zip](https://github.com/cBioPortal/datahub/files/1636163/myReport.html.zip)


Hi Sander...Here you go!

**Comment by sandertan** [comment]
Hmm the validation report looks fine, but the 500-error shouldn't happen. Did the import run successfully without errors? Also, make sure to restart Tomcat after each time you've loaded a study.

I noticed the validation report contains many duplicate lines. Could you try to load a small sample of the data without duplicate genes? For example, 2 samples in the clinical file, and for those 2 samples 2 genes in the expression and z-scored expression file. So 4 values in total per table. Then we can find out if this data related or a bug in the cBioPortal loader.

**Comment by ashraf123456789** [comment]
So I tried everything you did mention on here....if there's any errors the study won't load at all. There was no errors. I did what you asked about doing a minimal amount of samples with no duplicates....same results in regards to Oncoprint...refreshing hasn't worked as well unfortunately, is my issues the first of its kind?

**Comment by sandertan** [comment]
Would it be possible for you to share this minimal test study? Perhaps replace all variables names and values with some fake data. Then I can take a closer look.

**Comment by ashraf123456789** [comment]
Will do

**Comment by ashraf123456789** [comment]
Hi Sander,

I updated cbioportal and now oncoprint is working, but I can't update new studies because I'm receiving this error:

Checked DB schema version: (expected: 0) (found: 2.4.0)
Error, probably due to this version of the portal being out of sync with the database. Run the database migration script located at PORTAL_HOME/core/src/main/scripts/migrate_db.py before continuing.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Error occurred during data loading step. Please fix the problem and run this again to make sure study is completely loaded.
Traceback (most recent call last):
  File "./metaImport.py", line 118, in <module>
    cbioportalImporter.main(args)
  File "/Users/shaba033/Downloads/cbioportal-master/core/src/main/scripts/importer/cbioportalImporter.py", line 419, in main
    check_version(jvm_args)
  File "/Users/shaba033/Downloads/cbioportal-master/core/src/main/scripts/importer/cbioportalImporter.py", line 152, in check_version
    run_java(*args)
  File "/Users/shaba033/Downloads/cbioportal-master/core/src/main/scripts/importer/cbioportal_common.py", line 799, in run_java
    raise RuntimeError('Aborting due to error while executing step.')
RuntimeError: Aborting due to error while executing step.
shaba033$
 
how do I get my expected and found database schemas to match?

**Comment by sandertan** [comment]
Can you check if `portal.properties` contains the new properties introduced in the updated version of cBioPortal? You'll find them in `portal.properties.EXAMPLE`. You have to rebuild after that.
