### ISSUE TITLE
Newman et al. Genomes for Kids: The scope of pathogenic mutations in pediatric cancer revealed by comprehensive DNA and RNA sequencing. Cancer Discovery 2021

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#1466]
https://cancerdiscovery.aacrjournals.org/content/early/2021/07/21/2159-8290.CD-20-1631

- [ ] [create an issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [ ] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [ ] Document the curation process, e.g. how and by whom the data was transformed
- [ ] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [ ] Create a pull request to datahub once the data is curated
- [ ] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update the default quick select study list see https://github.com/cBioPortal/cbioportal/issues/5831 (only for studies that are not overlapping with existing ones; only for human tumors, not cell lines)
- [ ] **Add to Pediatric studies section**
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

**Comment by yichaoS** [comment]
Data availability:
- clinical data: supplemental S1, S10, S11
- maf (whole genome (WGS), exome): can be downloaded form here: https://www.ncbi.nlm.nih.gov/clinvar/?LinkName=orgtrack_clinvar&from_uid=506672 (ask for germline!)
- CNA: supplemental S4
- Mutation Signatures: S5
