### ISSUE TITLE
sample discrepancies for coad_cptac_2019

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#1488]
There are 110 samples but some samples have no associated profiles.

https://www.cbioportal.org/study/summary?id=coad_cptac_2019

**Comment by rmadupuri** [comment]
@jjgao 3 samples (05CO004, 13CO001, 14CO001) were not analyzed in any of the genomic profiles. They only exist in the clinical  as seen here - http://linkedomics.org/cptac-colon/ and the sample counts/case lists for the profiles match. We have corrected the study description (will be updated in db soon). Have not removed the 3 samples - for the study to match the paper.
