### ISSUE TITLE
Import Documentation for "public"

### ISSUE THREAD

**Issue by serverhorror** [cBioPortal/datahub#149]
There seems to be a kind of import documentation missing.

Is there any link as to where to go and what to do? I know this is somehow supposed to work with cBioportal but there is no README.md in that folder and no mention of how one would do this in the README.md of the project root.

**Comment by sandertan** [comment]
Hi @serverhorror, you can find documentation how to import these studies in the cBioPortal documentation:
https://github.com/cBioPortal/cbioportal/blob/master/docs/Data-Loading.md
