### ISSUE TITLE
Zhang et al. Genomic and evolutionary classification of lung cancer in never smokers. Nat Genet 2021

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#1499]
https://pubmed.ncbi.nlm.nih.gov/34493867/

- [ ] [create an issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [ ] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [ ] Document the curation process, e.g. how and by whom the data was transformed
- [ ] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [ ] Create a pull request to datahub once the data is curated
- [ ] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update the default quick select study list see https://github.com/cBioPortal/cbioportal/issues/5831 (only for studies that are not overlapping with existing ones; only for human tumors, not cell lines)
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

**Comment by rmadupuri** [comment]
Reached out to the author (Maria Teresa Landi - landim@mail.nih.gov) for the missing arm level copy number data, RNA-Seq, mutational signatures (sample based contribution or p-value).  

Response : We are planning a release of a much larger dataset in the hopefully near future, including all the data you requested. Please give us a bit more time.  _(they will keep us in the loop for the larger release)_

**Comment by ritikakundra** [comment]
- Can histology be used to add CTD?

- Results say: Among genes in the receptor tyrosine kinase–Ras (RTK–Ras) pathway, EGFR was the most frequently altered (30.6%), followed by KRAS (7.3%), ALK (6.0%), MET (4.3%), ERBB2 (3.9%, all indels), ROS1 (2.6%) and RET (1.3%).
Our mutation table shows:
EGFR 28.4%
KRAS 7.3%
ALK 0.4%
MET 3.0%
ERBB2 3.9%
ROS1 0.4%
RET 0.4%

This discrepancy needs to be looked into, especially for ALK and ROS1

- I don't see any SV data.

**Comment by yichaoS** [comment]
@ritikakundra 
The percentage of the alteration was calculated including "SNVs/indels, SCNAs, structural variants", if we include SV/fusion data, the numbers match exactly in oncoprint vs in paper. For example, ALK has 5.6% fusions in figure 2 (https://www.nature.com/articles/s41588-021-00920-0/figures/2) section 3, plus 0.4% the SNV as you saw before, in total is 6%. Same for other genes queried in above comments (see screenshot).  I added in a few more genes (RBM10, PIK3CA) from figure 2  and the numbers match exactly as well.
<img width="1152" alt="Screen Shot 2022-04-19 at 10 10 48 PM" src="https://user-images.githubusercontent.com/5973438/164154908-b38060ca-ca4c-4f44-8782-bc9f7d407950.png">
Query in triage: https://bit.ly/3KT8pAB
