### ISSUE TITLE
tcga_pub studies cannot be loaded

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/datahub#15]
Currently none of the 16 _tcga_pub studies can be loaded. @pulyakhina and I have validated them all, and these are the most common errors:

- [ ] Clinical data files in old format: `data_clinical.txt`  instead of `_data_patient.txt` and `_data_sample.txt`
- [ ] Stable ids in meta files are in an invalid format: `stable_id: blca_tcga_pub_gistic` instead of `stable_id: gistic`
- [ ] For .seg and multiple meta files, file type cannot be determined. `Could not determine the file type. Please check your meta files for correct configuration. genetic_alteration_type: PROTEIN_LEVEL, datatype: CONTINUOUS`

Error reports:
[Reports_tcga_pub.zip](https://github.com/cBioPortal/datahub/files/571604/Reports_tcga_pub.zip)

Affected studies:

1. blca_tcga_pub
2. brca_tcga_pub
3. coadread_tcga_pub
4. gbm_tcga_pub
5. hnsc_tcga_pub
6. kich_tcga_pub
7. kirc_tcga_pub
8. laml_tcga_pub
9. lgggbm_tcga_pub
10. luad_tcga_pub
11. lusc_tcga_pub
12. ov_tcga_pub
13. prad_tcga_pub
14. stad_tcga_pub
15. thca_tcga_pub
16. ucec_tcga_pub

**Comment by chenh4** [comment]
I fixed the three major errors listed in the 16 _tcga_pub studies and pushed the updated data out to the repository in mercurial, but there are several errors in genomic data and case_lists. These common errors include:

1. Sample ID not defined in the clinical file: *_data_cna_hg19.seg, data_mutations_extended.txt, data_rppa.txt, case_lists, meta_expression_merged_median_Zscores.txt, data_expression_miRNA.txt, data_linear_CNA.txt, data_methylation_hm450.txt, data_CNA_RAE.txt, data_CNA_consensus.txt, data_expression_median.txt, data_expression_miRNA.txt, data_mRNA_median_Zscores.txt   

2. Entrez gene identifier is non-positive: data_CNA.txt, data_linear_CNA.txt

3. meta_fusions.txt -> stable_id: mutations (need to correct from validator)

**Comment by n1zea144** [comment]
@sandertan @chenh4 Is referring to a legacy internal mercurial server that is still in use at MSK.  Once the remaining errors are addressed, we will push the data from our mercurial server into the datahub.

**Comment by sandertan** [comment]
Thanks for the update, will gladly test it when ready.

**Comment by ritikakundra** [comment]
- [ ] - [ ] blca_tcga_pub
- [ ] brca_tcga_pub
- [ ] coadread_tcga_pub
- [ ] gbm_tcga_pub
- [ ] hnsc_tcga_pub
- [ ] kich_tcga_pub
- [ ] kirc_tcga_pub
- [ ] laml_tcga_pub
- [ ] lgggbm_tcga_pub
- [ ] luad_tcga_pub
- [ ] lusc_tcga_pub
- [ ] ov_tcga_pub
- [ ] prad_tcga_pub
- [ ] stad_tcga_pub
- [ ] thca_tcga_pub
- [ ] ucec_tcga_pub

**Comment by pieterlukasse** [comment]
We got a question regarding one of these studies (`lusc_tcga_pub`): https://groups.google.com/forum/#!topic/cbioportal/dgFlwlittVY 

Furthermore, when I try to validate the `lusc_tcga_pub` study, almost all of the meta files fail:

![image](https://user-images.githubusercontent.com/2900303/28366135-aa3783aa-6c8b-11e7-8e49-af231da6e4d5.png)

Main error seems to be regarding `stable_id` still containing the study id. This one should be easy to fix. And the problem mentioned in the google groups topic is also detected by the validator as an error :smile: :+1: 

![image](https://user-images.githubusercontent.com/2900303/28366200-fc871f80-6c8b-11e7-9043-357baf1879b4.png)

This one should be easy to fix (if the data is correct and it is just a label problem in the meta file - which is what @jjgao states in the google groups reply).

**Comment by sophie2046** [comment]
Hi there, I am wondering whether the above problem mentioned has been fixed and when they will be pushed to this datahub? It seems to be another 6 months since the last post.

**Comment by pieterlukasse** [comment]
hi @sophie2046, a lot has happened since then (see https://github.com/cBioPortal/datahub/pulls?q=is%3Apr+is%3Aclosed), but we haven't been updating the tickets. Thanks for the reminder. There is also a new PR with many more fixes and improvements (https://github.com/cBioPortal/datahub/pull/164). @sandertan could you please update this ticket? Maybe it can be closed?

**Comment by sandertan** [comment]
The "_pub" studies can still not be loaded. Fixing the TCGA provisional studies (the ones without "_pub") will be updated first, I assume the "_pub" will be fixed some time after that. I'll leave this ticket open.

**Comment by sophie2046** [comment]
@pieterlukasse  @sandertan  Thank you for the reply. Can you point to me a loadable version now for TCGA BRCA data? I tried the brca_tcga.tar.gz which doesn't have a _pub tag and updated 3 months ago. It still failed exactly the same reasons during validation (protein level data type, and the normal samples in the CNV_seg data were not in clinical data) . I am using cbioportal v1.11.2.

**Comment by sandertan** [comment]
Hi @sophie2046 The TCGA studies are getting fixed in this Pull Request: https://github.com/cBioPortal/datahub/pull/164. You can track this PR to see the progress.

The latest version of brca_tcga can be found in the branch associated with this Pull Request, located here:
https://github.com/cBioPortal/datahub/tree/cleanup/public/brca_tcga
Unfortunately this is not a zip file yet, so you could download the files separately, or use a tool described [here](https://stackoverflow.com/questions/7106012/download-a-single-folder-or-directory-from-a-github-repo) to download the complete folder.

The validation report for this version of brca_tcga can be found here: https://circleci.com/gh/cBioPortal/datahub/17#artifacts/containers/0
