### ISSUE TITLE
genomic profiles samples count is wrong for fusions

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/datahub#1515]
GENIE is showing 100% of samples with fusion data, but I know that's not true.

![image](https://user-images.githubusercontent.com/10508276/128921387-7d7aec43-1df7-4604-8ee2-f8534df5dae5.png)

In speaking with @Luke-Sikina this sounds like it may be a code problem and not a data problem. Which also means it may impact studies beyond GENIE.

@jjgao @ritikakundra is this something that's been discussed for GENIE previously?

**Comment by tmazor** [comment]
@ritikakundra @jjgao I'm still seeing this issue in the public v11 release. Is there any progress on getting those case lists for GENIE?

**Comment by ritikakundra** [comment]
@tmazor Yes, I need to reimport the study, should schedule it in a day or two.

**Comment by tmazor** [comment]
This is still an issue in current GENIE v12 release

**Comment by ritikakundra** [comment]
@tmazor hmm I fixed it looks like reimport from Sage caused it to come back

**Comment by tmazor** [comment]
@ritikakundra hmmm ok - can you re-do for this latest version? and what is the fix? we'll need to do it for genie in our internal portal also.

**Comment by ritikakundra** [comment]
@tmazor ya doing it for all recent studies. We did ask Sage to add the caselists in, I think they have not yet added it in. Am meeting them on Thursday so I will reiterate it.
