### ISSUE TITLE
Load pedriatric CPTAC study

### ISSUE THREAD

**Issue by SRodenburg** [cBioPortal/datahub#1525]
Merged in https://github.com/cBioPortal/datahub/pull/1431, but study is based on hg38.

@yichaoS mentioned hg38 studies are soon to be allowed in public cBioPortal. Or would it be more efficient to do a liftover? Perhaps we can explore the viability of a liftover, for another recently merged CPTAC study that data loss was minimal.

**Comment by yichaoS** [comment]
@SRodenburg @egarcialara Yea, please do a lift over for this pediatric brain CPTAC study as well, as the plan for conversion to hg38 database on our side is postponed for the time being.
