### ISSUE TITLE
how can I find the SVS pathology images of mskcc tsv clinical dataset?

### ISSUE THREAD

**Issue by monajalal** [cBioPortal/datahub#1541]
I would like to know how I can download the pathology images related to the following tsv file in SVS format?

https://www.cbioportal.org/study/clinicalData?id=tmb_mskcc_2018

Thanks a lot

Please keep this checklist for curation of a new study.

- [ ] [create an issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [ ] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [ ] Document the curation process, e.g. how and by whom the data was transformed
- [ ] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [ ] Create a pull request to datahub once the data is curated
- [ ] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update the default quick select study list see https://github.com/cBioPortal/cbioportal/issues/5831 (only for studies that are not overlapping with existing ones; only for human tumors, not cell lines)
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

**Comment by rmadupuri** [comment]
Hey @monajalal, the pathology images are not publicly available.
