### ISSUE TITLE
public/angs_painter_2020/data_clinical_sample.txt

### ISSUE THREAD

**Issue by zhangguy** [cBioPortal/datahub#1562]
Hi, 

It seems that public/angs_painter_2020/data_clinical_sample.txt uses Carriage Return '\r' as the line break symbol. Thought all of the files are SQL dumps, and it is weird that they are not in a uniform format.

Thanks.

**Comment by sbabyanusha** [comment]
@zhangguy Thanks for bringing this to our attention. The issue has been taken care of.
