### ISSUE TITLE
error in public/skcm_tcga_pan_can_atlas_2018/data_mutations.txt

### ISSUE THREAD

**Issue by bosmont** [cBioPortal/datahub#1564]
When 'git clone https://github.com/cBioPortal/datahub.git", I got the following message:

Cloning into 'datahub'...
remote: Enumerating objects: 58545, done.
remote: Counting objects: 100% (11687/11687), done.
remote: Compressing objects: 100% (3902/3902), done.
remote: Total 58545 (delta 8461), reused 10469 (delta 7774), pack-reused 46858
Receiving objects: 100% (58545/58545), 947.71 MiB | 11.34 MiB/s, done.
Resolving deltas: 100% (26705/26705), done.
Updating files: 100% (8165/8165), done.
Encountered 1 file(s) that should have been pointers, but weren't:
	public/skcm_tcga_pan_can_atlas_2018/data_mutations.txt

As a results, when "git lfs pull -I public/skcm_tcga_pan_can_atlas_2018", the mutation data were not pulled.  

Please help.  Really appreciated.

**Comment by sbabyanusha** [comment]
@bosmont The issue has been resolved.
