### ISSUE TITLE
Multiple validation reports per study

### ISSUE THREAD

**Issue by dionnezaal** [cBioPortal/datahub#158]
In the current master branch some studies contain multiple validation report files. For example, study hnsc_tcga contains hnsc_tcga.html and validation_report.html. The validation reports also do not seem to validate the same data and/or use different validators. For example, meta_mutsig.txt and data_mutsig.txt are validated in validation_report.html and not in hnsc_tcga.html.

**Comment by dionnezaal** [comment]
Will report a list soon which studies have multiple validation reports

**Comment by yichaoS** [comment]
I checked on mercurial that those files were checked by Angelica 4 months ago.
We should just discard those.

**Comment by dionnezaal** [comment]
@yichaoS Studies containing two validation reports are: kirc_tcga, hnsc_tcga and lihc_tcga

**Comment by yichaoS** [comment]
@dionnezaal I've added a card to our next week sprint. Will get this resolved before our next meeting.

**Comment by yichaoS** [comment]
solved in rc.
