### ISSUE TITLE
Gene Symbols in cBioPortal are out of date

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/datahub#1581]
For example, HIST1H1C is now H1-2
https://www.ncbi.nlm.nih.gov/gene/3006

**Comment by yichaoS** [comment]
@schultzn we do suppose both symbols. `H1-2` is the main symbol and `HIST1H1C` is its alias.

We included all the "previous symbols" and "alias" in HGNC database, as "alias" in cBioPortal so the gene table is backwards-compatible with older data files (just in case, altho we've updated all the data files in datahub to using newer symbols).  

 cc' @ritikakundra

**Comment by schultzn** [comment]
Thanks. I think we should try to keep the gene tables up to date.

**Comment by ritikakundra** [comment]
@schultzn would it make sense to update our tables twice a year? Or should it be more often?

**Comment by yichaoS** [comment]
closing this issue - Have decided to update twice a year. And a standard procedure defined.
