### ISSUE TITLE
Error in format of public/sclc_ucologne_2015/data_mrna_seq_rpkm_zscores_ref_all_samples.txt

### ISSUE THREAD

**Issue by pavlosant** [cBioPortal/datahub#1600]
There is a format error on the following line, there is an additional string sclc_ucologne_2015_S00833:
grep  '0.5409sclc_ucologne_2015_S00833' data_mrna_seq_rpkm_zscores_ref_all_samples.txt 
MARCH10         -0.5409 -0.5409 -0.2613 0.0276  -0.5409 -0.5409sclc_ucologne_2015_S00833        -0.5409 -0.5409 -0.5409 -0.5395 -0.5409 -0.5408 -0.5409 -0.5409 -0.5409 1.445   -0.5409 -0.5409 0.5526     -0.5409 0.656   -0.5409 -0.5409 -0.5409 -0.5409 -0.5409 -0.5409 -0.5409 -0.5409 -0.5408 -0.5409 -0.5409 -0.5409 -0.5409 0.9919  -0.5409 -0.5409 -0.3368 -0.5409 -0.5409 1.7329  -0.5409 -0.5409    -0.5407 0.0207  -0.5409 -0.5408 -0.5409 -0.5409 -0.3506 -0.5409 -0.5409 0.7195  -0.3612 -0.5409 0.0256  -0.5409 -0.2394 -0.5409 0.8861  0.179   -0.5409 1.5105  -0.5399 1.0349  -0.2564 -0.5409    -0.5409 -0.5409 -0.5409 -0.5409 -0.5409 -0.5409 -0.5409 -0.5409 -0.5409 0.0054  -0.5409 5.2602  -0.5409 0.8179

**Comment by rmadupuri** [comment]
Hi @pavlosant, thanks for bringing this to our attention! We have updated the file.
