### ISSUE TITLE
Kwanghee New Cohort

### ISSUE THREAD

**Issue by ritikakundra** [cBioPortal/datahub#1614]
Hi Ritika,
 
Please see the attached list and let me know if you have any questions.
-There are samples from the same patient but sequenced in DMP and iGO so having two different Patient ID.
-Column F has tissue information
-IMPACT for 2 samples: UCC_RNAseq5_36T, UCC_RNAseq5_36B pending

**Comment by rmadupuri** [comment]
Issue moved to [knowledgesystems/curation-scrum #1207](https://github.com/knowledgesystems/curation-scrum/issues/1207) via [**ZenHub**](https://www.zenhub.com/)
