### ISSUE TITLE
gene table update

### ISSUE THREAD

**Issue by yichaoS** [cBioPortal/datahub#1619]
last week
- [x] clarifying 2 genes missing from import
- [x] import miRNA
- [x] create seedDB mysql dump and upload to datahub
- [x] update seedDB doc (new release section PR) https://github.com/cBioPortal/datahub/pull/1613

this week
- [x] update gene table related doc (delete gencode, PDB step) https://github.com/cBioPortal/cbioportal/pull/9357
- [ ] create seedDB hg38 version
- [ ] seedDB PR validation fix
- [ ] import studies on EKS 
- [x] data file migration (PR?)

**Comment by rmadupuri** [comment]
Issue moved to [knowledgesystems/curation-scrum #1213](https://github.com/knowledgesystems/curation-scrum/issues/1213) via [**ZenHub**](https://www.zenhub.com/)
