### ISSUE TITLE
HG38 version of datahub

### ISSUE THREAD

**Issue by cheanney** [cBioPortal/datahub#1627]
Hi, 

First of all, I would like to say thank you for this wonderful resources. It really is a great resource for the cancer research community. 

Now to my question.

Are there HG38 release of data_mutations.txt files of the studies in cbioportal?
If not, is there a plan to have the HG38 release soon?
 
Thanks,
 
Anney

**Comment by yichaoS** [comment]
Hi @cheanney. We don't currently have hg38 release of MAF yet, altho we do plan to have hg38 release in the near future. I think for now we don't have a specific timeline tho. cc' @n1zea144  @ritikakundra @jjgao 

For future questions, please post to our user group here instead: https://groups.google.com/g/cbioportal. Thanks!
