### ISSUE TITLE
latest dumps are largely empty

### ISSUE THREAD

**Issue by ghost** [cBioPortal/datahub#1643]
since upgrading to v2.12.12, files are almost empty
http://download.cbioportal.org/mysql-snapshots/mysql-snapshots-toc.html

**Comment by rmadupuri** [comment]
Hey @ghost! I double checked the latest dump and the tables are populated. Do you still see this issue?

**Comment by rmadupuri** [comment]
Closing this. Please re-open if you still notice the issue.
