### ISSUE TITLE
Labrecque et al. Molecular profiling stratifies diverse phenotypes of treatment-refractory metastatic castration-resistant prostate cancer

### ISSUE THREAD

**Issue by SRodenburg** [cBioPortal/datahub#1657]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6763249/

Study with 98 PDX tumors, includes clinical data, RNA-Seq.

- [x] [create an issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [ ] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [ ] Document the curation process, e.g. how and by whom the data was transformed
- [ ] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [ ] Create a pull request to datahub once the data is curated
- [ ] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update the default quick select study list see https://github.com/cBioPortal/cbioportal/issues/5831 (only for studies that are not overlapping with existing ones; only for human tumors, not cell lines)
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

**Comment by egarcialara** [comment]
**Data Available:**

- RNA-seq for 98 CRPC metastasis samples (hg38) - GEO at GSE126078 ([https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE126078](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE126078))

**Data Missing:**

- Clinical/survival data

**Comment by egarcialara** [comment]
Minimal clinical data available under Characterstics for each sample in GEO (GSE126078).

**Comment by sbabyanusha** [comment]
This issue is being closed as we couldn't get a response from the author.
