### ISSUE TITLE
Quigley et al. - Genomic Hallmarks and Structural Variation in Metastatic Prostate Cancer

### ISSUE THREAD

**Issue by SRodenburg** [cBioPortal/datahub#1658]
https://pubmed.ncbi.nlm.nih.gov/30033370/

Study (n=101) with focus on SVs, includes RNA-Seq and clinical data. We will need to request data to the authors.
Mutation data is on hg38 so liftover required.

- [x] [create an issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [ ] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [ ] Document the curation process, e.g. how and by whom the data was transformed
- [ ] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [ ] Create a pull request to datahub once the data is curated
- [ ] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update the default quick select study list see https://github.com/cBioPortal/cbioportal/issues/5831 (only for studies that are not overlapping with existing ones; only for human tumors, not cell lines)
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

**Comment by rmadupuri** [comment]
**Data Available:**
- Table S1: Clinical
- Table S3: SV (only key genes)
- Table S4: MAF (only key genes)

**Data Missing:**
- Request whole genome MAF(hg38 ref), RNA-seq, SV, CNA

**Comment by sbabyanusha** [comment]
This issue is being closed as we couldn't get a response from the author.
