### ISSUE TITLE
Alumkal et al. - Transcriptional profiling identifies an androgen receptor activity-low, stemness program associated with enzalutamide resistance

### ISSUE THREAD

**Issue by SRodenburg** [cBioPortal/datahub#1659]
https://www.pnas.org/doi/10.1073/pnas.1922207117

Phase II trial - study on castration-resistant prostate cancer (CRPC) (n=36). Targeted DNA-sequencing on 26 of 36 biopsies, and RNA-Seq was performed on 25 of 36 biopsies.

We will need to ask the authors to release the sequencing data.

- [x] [create an issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [ ] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [ ] Document the curation process, e.g. how and by whom the data was transformed
- [ ] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [ ] Create a pull request to datahub once the data is curated
- [ ] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update the default quick select study list see https://github.com/cBioPortal/cbioportal/issues/5831 (only for studies that are not overlapping with existing ones; only for human tumors, not cell lines)
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

**Comment by sbabyanusha** [comment]
This issue is being closed as we couldn't get a response from the author.
