### ISSUE TITLE
Validator Issue: Duplicate samples in data_gene_matrix.txt does not fail

### ISSUE THREAD

**Issue by ritikakundra** [cBioPortal/datahub#166]
The Validator does not fail when there is a duplicate sample in the gene matrix file with the same panel information. This does fail import though.

**Comment by dionnezaal** [comment]
PR made with validator check for duplicate sample IDs: [#3918](https://github.com/cBioPortal/cbioportal/pull/3918)

**Comment by sandertan** [comment]
Done!
