### ISSUE TITLE
Stelloo et al. - Integrative epigenetic taxonomy of primary prostate cancer

### ISSUE THREAD

**Issue by SRodenburg** [cBioPortal/datahub#1661]
https://www.nature.com/articles/s41467-018-07270-2

Epigenetic study (n=100), includes ChIP-Seq and RNA-Seq. Clinical data needs to be requested at the authors.

- [x] [create an issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [ ] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [ ] Document the curation process, e.g. how and by whom the data was transformed
- [ ] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [ ] Create a pull request to datahub once the data is curated
- [ ] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update the default quick select study list see https://github.com/cBioPortal/cbioportal/issues/5831 (only for studies that are not overlapping with existing ones; only for human tumors, not cell lines)
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

**Comment by sbabyanusha** [comment]
Missing Data:
- Clinical Data
- RNA-Seq
- Mutations
- SV
- CNA
