### ISSUE TITLE
some datasets are missing references

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#168]
@tmazor commented on [Thu Feb 15 2018](https://github.com/cBioPortal/cbioportal/issues/3888)

There are a bunch of studies that sound like they relate to a publication (everything in the list below that isn't a TCGA Provisional study), but don't have a listed reference:

![image](https://user-images.githubusercontent.com/10508276/36264420-ae5c7d3c-123a-11e8-92c8-3009c07a0986.png)

**Comment by jjgao** [comment]
@rmadupuri could you help look into this? http://www.cbioportal.org/datasets

None provisional studies should all have a reference. If it's missing on this page, it could miss either `pmid` or `citation`.

**Comment by rmadupuri** [comment]
Detailed list of meta data : https://docs.google.com/spreadsheets/d/10e07j1WhNEBTVqBqN86vtKdXDFUqMGUjSv5d7_Sv87g/edit?usp=sharing
