### ISSUE TITLE
Update SV data for prostate_dkfz_2018

### ISSUE THREAD

**Issue by rmadupuri** [cBioPortal/datahub#1712]
The study has SV data - https://github.com/cBioPortal/datahub/blob/master/public/prostate_dkfz_2018/data_sv.txt

- Needs to be converted to the new SV format. 
- Missing Gene IDs but has coordinates.
- Missing meta file & SV case list

**Comment by sbabyanusha** [comment]
Couldn't find the hugo symbols from authors.
