### ISSUE TITLE
MSK 2022 Sarcoma study is missing the pubmed ID

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/datahub#1723]
https://www.cbioportal.org/study/summary?id=sarcoma_mskcc_2022
PMID: 35705560
https://pubmed.ncbi.nlm.nih.gov/35705560/

The description also has a typo:
Targeted Sequencing of 2138 Sarcoma sample and matched normals via MSK-IMPACT.
-->
Targeted Sequencing of 2138 sarcoma samples and matched normals via MSK-IMPACT.

**Comment by rmadupuri** [comment]
@schultzn the study is updated now.
