### ISSUE TITLE
Backfill all PMIDs and citations

### ISSUE THREAD

**Issue by ritikakundra** [cBioPortal/datahub#1724]
A number of studies are missing PMIDs or citations. 
https://docs.google.com/spreadsheets/d/1H_8GlVfY_5UmgCwQ9sucIgavlsD0F6vw4Grhe6HMOLM/edit#gid=0

**Comment by ritikakundra** [comment]
https://www.cbioportal.org/study/summary?id=crc_dd_2022
Has weird characters in meta study

**Comment by sbabyanusha** [comment]
This issue is fixed.
