### ISSUE TITLE
METABRIC please fix inconsistent meta data

### ISSUE THREAD

**Issue by rocanja** [cBioPortal/datahub#1729]
Re the METABRIC **mRNA expression** data in cBioPortal:

1. On the '**Data Sets**' page, the METABRIC data set is still listed as having 1904 **RNAseq** AND 1904 **microarray** samples as previously mentioned in issue #695, which was supposedly fixed ... METABRIC has only microarray samples for gene expression in cBioPortal as far as I am aware, or has this changed?  
2. On the '**Query**' page under '**Select Genomic Profiles**' it says '**Illumina** Human v3 microarray' while in the '**Select Patient/Case Set**' it says '**Agilent** microarray' ... according to the original METABRIC publication Curtis et al 2012, an **Illumina HT-12 v3 (Illumina_Human_WG-v3)** microarray was used for the study, thus, the 'Agilent' label is misleading  
3. What **database and version is the gene name annotation** (RefSeq, Ensembl, Gencode?) of the METABRIC microarray based on? I could only find in the FAQs that the public cBioPortal is currently using the hg19/GRCh37 genome as reference and in another forum entry that [genome nexus](https://docs.genomenexus.org/annotation-sources#versions) is used to manage the annotation in cBioportal ... but that doesn't specify what reference was used with which data set (genome nexus provides RefSeq, Gencode and Ensembl annotations).  Could this info please be included into the meta data of the data set? 
**EDIT**: in the downloaded data file, the column headers are **'Hugo_Symbol'** and **'Entrez_Gene_Id'** but the version is not indicated and a lot of the gene names don't actually seem to match Hugo symbols!?
**EDIT 07/12/22** after a lot of digging it looks like the authors of the original METABRIC publication (Curtis et al 2012) have used the **illuminaHumanv3SYMBOLREANNOTATED** annotation table from the ‘illuminaHumanv3.db’ package, but it is still not completely clear which database(s) and version(s) this annotation table is based on and whether the data provided in cBioPortal reflects this original data set or whether it may have been reannotated according to cBioPortal specific pipelines?    

_Thank you for providing this great resource and I can appreciate how hard it is to keep all the details for all the data sets up to date!_

**Comment by rocanja** [comment]
Thanks for updating/fixing points 1 and 2! I just noticed that the following data files still have 'agilent' in their filenames, which may have to be changed to 'illumina' in the next update as well:

- [data_mrna_agilent_microarray.txt](https://github.com/cBioPortal/datahub/blob/master/public/brca_metabric/data_mrna_agilent_microarray.txt)
- [data_mrna_agilent_microarray_zscores_ref_all_samples.txt](https://github.com/cBioPortal/datahub/blob/master/public/brca_metabric/data_mrna_agilent_microarray_zscores_ref_all_samples.txt)
- [meta_mrna_agilent_microarray.txt](https://github.com/cBioPortal/datahub/blob/master/public/brca_metabric/meta_mrna_agilent_microarray.txt)
- [meta_mrna_agilent_microarray_zscores_ref_all_samples.txt](https://github.com/cBioPortal/datahub/blob/master/public/brca_metabric/meta_mrna_agilent_microarray_zscores_ref_all_samples.txt)

**Comment by ritikakundra** [comment]
@rmadupuri Can you confirm is this was addressed?

**Comment by rmadupuri** [comment]
@rocanja sorry missed this and thanks for bringing it to our notice. The file name are updated. 

As per the point 3, the data available in cBioPortal reflects the original dataset although we have updated a few outdated gene symbols to the new ones.

**Comment by rocanja** [comment]
Thank you!
