### ISSUE TITLE
Allele Issues w/ provisional studies 

### ISSUE THREAD

**Issue by yichaoS** [cBioPortal/datahub#173]
- [ ] coadread_tcga: line 25096. When Validation_Status is valid and Mutation_Status is Somatic, the Match_Norm_Validation_Allele columns should be equal to the Reference Allele and one of the Tumor_Validation_Allele columns should not be. Values encountered: (G, -, G, G)
- [x] laml_tcga: line 676, 768, 1022, (5 more). When Validation_Status is valid and Mutation_Status is Somatic, the Match_Norm_Validation_Allele columns should be equal to the Reference Allele and one of the Tumor_Validation_Allele columns should not be. Value encountered: (TCGAGGTATA, -, TCGAGGTATA, TCGAGGTATA), (CA, -, CA, CA), (AG, -, AG, AG), (3 more)
- [ ] laml_tcga: line 176, 458, 915, (5 more). Variant_Type indicates an insertion, but Reference_Allele does not equal -. Values encountered: G, A, T 
- [ ] laml_tcga: line 497, 1940. Variant type indicates deletion but all allele columns same length and not -. Values encountered: (A, A, C), (G, G, A)
- [x] lusc_tcga: line 1819, 1837, 2019, (14 more). Allele Based column Tumor_Seq_Allele2 contains invalid character. Values encountered: ANA, TNT, ANT, (8 more)
- [x] ov_tcga: line 155, 158, 160, (22 more). When Validation_Status is valid and Mutation_Status is Somatic, the Match_Norm_Validation_Allele columns should be equal to the Reference Allele and one of the Tumor_Validation_Allele columns should not be. Values encountered: (G, C, G, G), (A, A, T, T), (A, A, C, C), (16 more)
- [ ] ov_tcga: line 1340. Validation Status is valid, but Validation Allele columns are empty. Values encountered: -
- [x] ov_tcga: line 16344. Allele Based column Tumor_Seq_Allele2 contains invalid character. Values encountered: CNT
- [x] ov_tcga: line 18360. All Values in columns Reference_Allele, Tumor_Seq_Allele1 and Tumor_Seq_Allele2 are equal. Values encountered: (A, A, A)
- [ ] brca_tcga: line 98274. Allele Based column Tumor_Seq_Allele2 contains invalid character. Values encountered: CNN

See full list of warnings: 
https://docs.google.com/spreadsheets/d/172m_Nj70tHQCQj3a_TvlRXfkoJDO3xyelfAMhhCA41k/edit?usp=sharing

**Comment by ritikakundra** [comment]
**OV_TCGA** (TCGA firehose is still build 36:
1. A,A,A is coming from the firehose link-http://gdac.broadinstitute.org/runs/stddata__2016_01_28/data/OV/20160128/
2. CNT is also coming from TCGA link. This is a widely used annotation from iupac for any base (https://www.bioinformatics.org/sms/iupac.html)
3.  ov_tcga: line 340: I can't find it on this line. Can @dionnezaal extract some examples?
4. Compared lines 155,158 and 160 between our MAF and firehose. They have it the same way.

**Comment by ritikakundra** [comment]
**LUSC_TCGA:**
This seems wrong. The firehose does not have any N for base change

**Comment by ritikakundra** [comment]
**LAML_TCGA (TCGA Firehose is 36):**

1. Checked firehose MAF which is in sync with datahub/cleanup for laml_tcga: line 676, 768, 1022,
2. laml_tcga: line 176, 458, 915, (5 more): issue seems weird. It is right in firehose but incorrect in the cleanup files. Seems all are MT variants.

**Comment by dionnezaal** [comment]
@ritikakundra **OV_TCGA** point 3 is line 1340: sample TCGA-13-0885-01, BRCA2, p.E1407Vfs*5

**Comment by dionnezaal** [comment]
Issues are resolved in PR #164
