### ISSUE TITLE
Can't access data over LFS due to data quota limit

### ISSUE THREAD

**Issue by mjsteinbaugh** [cBioPortal/datahub#1738]
Seeing this error message when attempting to use LFS:

```
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
```

Best,
Mike

**Comment by ritikakundra** [comment]
@mjsteinbaugh 
An account receives 1GB of free storage and 1GB of free bandwidth per month.  If that quota is exceeded, you either have to purchase additional data packs to increase your quota or wait until the next month when the quota gets reset.
You can find more information here:
https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-storage-and-bandwidth-usage
https://cbioportal.slack.com/archives/G55LK2SRF/p1671574576384049?thread_ts=1671567289.754479&cid=G55LK2SRF
https://docs.github.com/en/billing/managing-billing-for-git-large-file-storage/upgrading-git-large-file-storage

**Comment by mjsteinbaugh** [comment]
Oh was it my account affected? I didnt think of that haha
