### ISSUE TITLE
Inconsistent Ages in msk_met_2021

### ISSUE THREAD

**Issue by HigginsD3b** [cBioPortal/datahub#1739]
[A user in the Google group](https://groups.google.com/g/cbioportal/c/3rJN3pQTv58/m/9Hr7zn_jCgAJ) identified identified inconsistencies with the numerous age-related clinical data fields in [the msk_met_2021 study](https://www.cbioportal.org/study/clinicalData?id=msk_met_2021).

To try to calculate age at initial diagnoses, they are trying to infer by subtracting overall survival from age at death. However, this typically yields "age at sequencing", which is more recent than "age at first mets dx" and presumably the original dx.

**Comment by ritikakundra** [comment]
@HigginsD3b as Niki mentioned, OS MONTHS in this data set refers to the time since sequencing, not initial diagnosis, data is correct. We will update the description to say so.

**Comment by sbabyanusha** [comment]
The OS_MONTHS description has been updated.
