### ISSUE TITLE
Discrepancies of BRCA mutational data between cBioPortal and Firehose

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#174]
A user noticed ATM mutations on [three TCGA BRCA samples](http://www.cbioportal.org/case.do#/patient?caseId=TCGA-A2-A0T7&navCaseIds=TCGA-A2-A0T7%2CTCGA-AO-A1KT%2CTCGA-GM-A2DH&studyId=brca_tcga) were not included in [Firehose](http://gdac.broadinstitute.org/runs/stddata__2016_01_28/data/BRCA/20160128/gdac.broadinstitute.org_BRCA.Mutation_Packager_Calls.Level_3.2016012800.0.0.tar.gz).

I compared the Firehose file and our file on datahub and found that our file contains mutations called by unc and wustl while the firehose one only have wustl calls. Does anyone know where we got the unc calls?

**Comment by dionnezaal** [comment]
Fixed in PR #164 where only the mutation file described in the meta_study file is used.
