### ISSUE TITLE
The gene `FKBP5` is missing in gene expression file "data_mrna_agilent_microarray.txt"

### ISSUE THREAD

**Issue by snijesh** [cBioPortal/datahub#1743]
when I search FKBP5 in cBioPortal with metabric study they are diaplyed and shows the characteristcs of that gene. But when search the same gene in the file downloaded from [metabric](https://github.com/cBioPortal/datahub/blob/master/public/brca_metabric/data_mrna_agilent_microarray.txt) does not show their existence.

I tried all possible way of querying with synonyms as well as entrez id. Nothing got matched. 
Synonyms : `P54; AIG6; FKBP51; FKBP54; PPIase; Ptg-10`
EntrezID: `2289`
Please fix this  issue as this gene is found important for various studies.

**Comment by sbabyanusha** [comment]
@snijesh I am able to see the FKBP5 gene in the data_mrna_agilent_microarray.txt. Can you try downloading the file using the download link in the cbioportal summary page https://www.cbioportal.org/study/summary?id=brca_metabric.
