### ISSUE TITLE
CCLE_Broad_2019: undefined property when using the search bar on structural variant data

### ISSUE THREAD

**Issue by TJMKuijpers** [cBioPortal/datahub#1780]
Typing any text or letters in the search bar for structural variants causes cBioPortal to return an error. The error is likely to be specific to the ccle_broad_2019 study since the search bar works for other studies with structural variant data (for example,  the brca_tcga_pan_can_atlas_2018  study).  

```
{"type":"ErrorBoundary","log":"TypeError: Cannot read properties of undefined (reading 'indexOf')","url":"https://www.cbioportal.org/patient?sampleId=KYSE450_OESOPHAGUS&studyId=ccle_broad_2019"}
```

The original error is reported in the google forums: https://groups.google.com/g/cbioportal/c/TJYwNoqecjk

**Comment by sbabyanusha** [comment]
this is fixed.
