### ISSUE TITLE
Remove cna data from Breast BCCRC Xenograft

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#179]
Per @schultzn's request since there seem to be too many copy number events.

e.g. http://www.cbioportal.org/index.do?session_id=5ab962b8498eb8b3d56561c7

- [ ] remove profile `brca_bccrc_xenograft_2014_gistic`
- [ ] update case lists, e.g. remove case list _cna and _cnaseq

**Comment by jjgao** [comment]
a request from user: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/cbioportal/tvoMFTXDgXk/NHkQYQSBCwAJ

@ritikakundra: could you prioritize this issue?

**Comment by jjgao** [comment]
Only the profile `Putative copy-number alterations` needs to be removed.

**Comment by ritikakundra** [comment]
This has been addressed. Download also skips CNA files.
