### ISSUE TITLE
Knisbacher et al. Molecular map of chronic lymphocytic leukemia and its impact on outcome. Nat Genet. 2022

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#1823]
https://pubmed.ncbi.nlm.nih.gov/35927489/

- [x] [create an issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [x] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [x] Document the curation process, e.g. how and by whom the data was transformed
- [x] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [x] Create a pull request to datahub once the data is curated
- [x] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update the default quick select study list see https://github.com/cBioPortal/cbioportal/issues/5831 (only for studies that are not overlapping with existing ones; only for human tumors, not cell lines)
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

**Comment by sbabyanusha** [comment]
The paper has been curated. Here is the link :https://www.cbioportal.org/study/summary?id=cll_broad_2022
