### ISSUE TITLE
Discrepancies in Survival data across IMPACT LUNG studies.

### ISSUE THREAD

**Issue by rmadupuri** [cBioPortal/datahub#1841]
Reported by a User:
The same patient is deceased and living at the later date in two studies. There might be other similar patients.

**Comment by ritikakundra** [comment]
User reported these studies: as examples
In cbioportal, LUAD data from MSKCC. Here is just some of them
[https://www.cbioportal.org/study/summary?id=msk_impact_2017](https://urldefense.com/v3/__https:/www.cbioportal.org/study/summary?id=msk_impact_2017__;!!KVWo1iE!SaCpXqnt3X9fQPRp06kCVxAS70fBcz7iI7RlMAsLzvzETWMgyL4GraCbaC1o19v3LdffW6JOrIfhLskU62WPwA$)
[https://www.cbioportal.org/study/summary?id=msk_met_2021](https://urldefense.com/v3/__https:/www.cbioportal.org/study/summary?id=msk_met_2021__;!!KVWo1iE!SaCpXqnt3X9fQPRp06kCVxAS70fBcz7iI7RlMAsLzvzETWMgyL4GraCbaC1o19v3LdffW6JOrIfhLsnj8vSofw$)
[https://www.cbioportal.org/study/summary?id=luad_mskimpact_2021](https://urldefense.com/v3/__https:/www.cbioportal.org/study/summary?id=luad_mskimpact_2021__;!!KVWo1iE!SaCpXqnt3X9fQPRp06kCVxAS70fBcz7iI7RlMAsLzvzETWMgyL4GraCbaC1o19v3LdffW6JOrIfhLsl7rx8_sQ$)
[https://www.cbioportal.org/study/summary?id=nsclc_ctdx_msk_2022](https://urldefense.com/v3/__https:/www.cbioportal.org/study/summary?id=nsclc_ctdx_msk_2022__;!!KVWo1iE!SaCpXqnt3X9fQPRp06kCVxAS70fBcz7iI7RlMAsLzvzETWMgyL4GraCbaC1o19v3LdffW6JOrIfhLskwe8K9aQ$)
[https://www.cbioportal.org/study/summary?id=luad_msk_npjpo_2021](https://urldefense.com/v3/__https:/www.cbioportal.org/study/summary?id=luad_msk_npjpo_2021__;!!KVWo1iE!SaCpXqnt3X9fQPRp06kCVxAS70fBcz7iI7RlMAsLzvzETWMgyL4GraCbaC1o19v3LdffW6JOrIfhLslpi4BgBQ$)
[https://www.cbioportal.org/study/summary?id=luad_mskcc_2023_met_organotropism](https://urldefense.com/v3/__https:/www.cbioportal.org/study/summary?id=luad_mskcc_2023_met_organotropism__;!!KVWo1iE!SaCpXqnt3X9fQPRp06kCVxAS70fBcz7iI7RlMAsLzvzETWMgyL4GraCbaC1o19v3LdffW6JOrIfhLsmBaQlfGw$)

**Comment by rmadupuri** [comment]
The MSK lung studies have different reference points for measuring the survival data

STUDY_ID | OS_ANCHOR_DATE
-- | --
luad_mskcc_2020 | Since surgery
luad_mskcc_2023_met_organotropism | Sample acquisition
luad_mskimpact_2021 | Since date of sequencing
mixed_impact_subset_2022 | Since date of sequencing
msk_access_2021 | Since date of sequencing
msk_impact_2017 | Date of sample collection
msk_met_2021 | Since date of sequencing
nsclc_ctdx_msk_2022 | Measured time from diagnosis of stage IV or recurrent NSCLC
paired_bladder_2022 | Since date of sequencing
tmb_mskcc_2018 | Overall survival was measured from the date of first ICI treatment to time of death or most recent follow-up

Survival status/times will vary between studies due to differences in when the measurements were taken, freeze dates, and the focus on specific aspects like metastatic samples or particular treatments. 

Below is an example of a patient reported as deceased in one study and living at a later date in an another study.

PATIENT_ID | STUDY_ID | OS_STATUS | OS_MONTHS | ANCHOR_DATE
-- | -- | -- | -- | --
P-0000689 | luad_mskcc_2023_met_organotropism | 1:DECEASED | 19.29841865 | Sample collection
P-0000689 | msk_impact_2017 | 0:LIVING | 27.58 | Sample collection

It is to be noted that "luad_mskcc_2023_met_organotropism" study focuses on the time from sample collection until the occurrence of metastases whereas the "msk_impact_2017" study is measuring the time from sample collection to either death or the most recent follow-up.
