### ISSUE TITLE
Discrepancies in the mutation frequencies of 5 genes in BEAT AML2 dataset

### ISSUE THREAD

**Issue by rmadupuri** [cBioPortal/datahub#1843]
The frequency of mutations of FLT3 (ITD), NPM1, RUNX1, ASXL1 and TP53 genes is altered between the papers description (figure 1) and cBioPortal. For example, FLT3 frequency in cBioportal is reported at 9.5% occurrence and in the article it comes to approximately 27% frequency.

These 5 genes were also classified based on a clinical approach and we currently show the consensus mutation status in the clinical table. 

Can the consensus calls be transformed to the MAF file? There currently is no genomic coordinates or alleles.

**Comment by Rima-Waleed** [comment]
MAF files for the consensus calls of FLT3 (ITD), NPM1, RUNX1, ASXL1 and TP53 genes were found to be deposited in Vizome database, where the data was curated for each gene, annotated, then added to the existing MAF file to fix the mutation frequency and ensure it matches the paper.
