### ISSUE TITLE
Confusion regarding prad_su2c_2019 study

### ISSUE THREAD

**Issue by Irfanwustl** [cBioPortal/datahub#1857]
I am working with [this prostate cancer data](https://github.com/cBioPortal/datahub/tree/master/public/prad_su2c_2019). However,  I am a little confused between [data_mrna_seq_fpkm_polya_zscores_ref_all_samples.txt](https://github.com/cBioPortal/datahub/blob/master/public/prad_su2c_2019/data_mrna_seq_fpkm_polya_zscores_ref_all_samples.txt) and [data_mrna_seq_fpkm_polya_zscores_ref_diploid_samples.txt](https://github.com/cBioPortal/datahub/blob/master/public/prad_su2c_2019/data_mrna_seq_fpkm_polya_zscores_ref_diploid_samples.txt). Though there are corresponding metadata files, I am not sure what is the difference between these two data files. Will you please explain it a little more?

Thanks,
Irfan

**Comment by rmadupuri** [comment]
Hi @Irfanwustl, thanks for your interest in the prad_su2c_2019 study. We calculated z-scores using two different base populations.

The `data_mrna_seq_fpkm_polya_zscores_ref_all_samples.txt` contains z-scores where the reference population includes all the samples that were profiled for gene expression.

The `data_mrna_seq_fpkm_polya_zscores_ref_diploid_samples.txt` contains z-scores where the reference population only includes samples where the gene of interest was in its non-altered state (diploid). However, this approach is discontinued now.

More details on the two approaches are described [here](https://docs.cbioportal.org/user-guide/faq/#what-are-mrna-and-microrna-z-scores).

**Comment by Irfanwustl** [comment]
Thank you so much.
