### ISSUE TITLE
genomic coordinate issue

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#1863]
reported by [a user](https://groups.google.com/g/cbioportal/c/WQcWgsHz1e4/m/c-TfVDQVCwAJ)

In [this patient](https://www.cbioportal.org/patient/summary?sampleId=CD08&studyId=ucec_ccr_cfdna_msk_2022), the genomic coordinates seem incorrect.

![image](https://github.com/cBioPortal/datahub/assets/840895/b7d14d13-1984-46e7-844e-3659ef886b8a)

**Comment by jjgao** [comment]
The same user spotted more issues.

The end position of SNPs of lusc_cptac_2021 were all assigned wrongly. 

https://www.cbioportal.org/patient?sampleId=C3N-01020&studyId=lusc_cptac_2021

<img width="903" alt="image" src="https://github.com/cBioPortal/datahub/assets/840895/64827b39-37a0-4a94-a61e-ab87aa2676c6">

**Comment by jjgao** [comment]
It would be great if these can be added to validator.

**Comment by sbabyanusha** [comment]
This is fixed.

**Comment by jjgao** [comment]
Thanks, @sbabyanusha . The user identified more cases in other studies: https://groups.google.com/g/cbioportal/c/WQcWgsHz1e4/m/w4Bq2LygDQAJ.
