### ISSUE TITLE
isoform issue

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#1864]
Reported by user: "This 1 variant in DICER1 has a protein change 'K1789R' that is not on the canonical transcript, so curious how this was determined because this affects the OncoKB annotation of the variant. If querying with protein change, OncoKB annotation is missense K1789R with 'Unknown' oncogenicity vs querying with the genomic change of the same variant, OncoKB annotation is X1843_splice,  'Likely oncogenic' variant. (https://www.cbioportal.org/patient?sampleId=E-H-100144-T1-1-D1-1&studyId=mds_iwg_2022)"

**Comment by ritikakundra** [comment]
Portal is now showing the right transcript.
