### ISSUE TITLE
normalize IDs

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#192]
I remember we had some discussions earlier but couldn't find the issue...

We should add some rules for IDs (study, profile, patient, samples, etc). I would propose support only the characters below. Thoughts?

- A-Z
- a-z
- 0-9
- .
- _
- \-

regex: `[^A-Za-z0-9\._-]`

The query below would be useful to find out IDs that do not meet this rule.
```
select *
from patient
where stable_id regexp ".+[^A-Za-z0-9\._-].+"
```

The above query will return one patient `RS4;11` in `cellline_ccle_broad`.

Similar, you can query for sample IDs and other IDs.

**Comment by yichaoS** [comment]
@jj I did the query and these studies are affected with special characters in stable ID:

Patient ID: 
- acyc_fmi_morris_2017
- skcm_mskcc_2015_chant
- cellline_ccle_broad
- accrf_merged
- prad_tcga_su2c_impact_2015
- ov_jhu_velculesculab_2015

Sample ID:
- accrf_merged
- acyc_fmi_morris_2017
- cgci_htmcp_lc_2017

**Comment by ritikakundra** [comment]
@yichaoS @jjgao I suggest changing all special characters to -

**Comment by jjgao** [comment]
@ritikakundra @yichaoS: yes, we can change all special characters in sample/patient IDs to hyphen.

Hopefully we don't have any special ones in study IDs. If we do, we can change them to underscore.

I think we should also add this to validator. @sandertan @pieterlukasse

**Comment by yichaoS** [comment]
@jj I just checked gdac DB, the study IDs are fine.

**Comment by jjgao** [comment]
@pieterlukasse do you think you can add this rule in the validator?

**Comment by pieterlukasse** [comment]
@oplantalech can you please add this regex, replacing what was done in https://github.com/cBioPortal/cbioportal/pull/2099?
