### ISSUE TITLE
Public release Review

### ISSUE THREAD

**Issue by sbabyanusha** [cBioPortal/datahub#1984]
1. https://triage.cbioportal.mskcc.org/study/summary?id=egc_msk_2023 
      - Only MSK-IMPACT sequenced samples were included in the cohort. 

2. https://triage.cbioportal.mskcc.org/study/summary?id=rms_msk_2023
      - They have an MSK internal link in the paper. Requested the author to fix it.
      - The paper talks about 61 samples and we have 24 in our portal. the rest of them were from the Institute of Curie and the author left msk so couldn't get the data.
  
3. https://triage.cbioportal.mskcc.org/study/summary?id=hcc_jcopo_msk_2023
   
4. https://triage.cbioportal.mskcc.org/study/summary?id=sarcoma_msk_2023

**Comment by ritikakundra** [comment]
https://triage.cbioportal.mskcc.org/study/summary?id=egc_msk_2023

- [ ] Is Esophagogastric Cancer the right title if there are other cancers as well?
- [ ] So the MSK cases are 902? Cos I see different numbers in the paper
- [ ] Not able to open the paper.  Is there a way to confirm the genomic matches
- [ ] is survival data from them or IMPACT, can we add from when the survival was computed in the description?

**Comment by ritikakundra** [comment]
https://triage.cbioportal.mskcc.org/study/summary?id=rms_msk_2023

- [ ] Just to be consistent, can we move the extremity to the description rather than the title?
- [ ] Can we also add the 24 cases are MSK cases then?
- [ ] Can't open the paper. Genomic data is synced?
- [ ] Where did we get the age at Dx from? I see ped cases in them?
- [ ] is survival data from them or IMPACT, can we add from when the survival was computed in the description?

**Comment by ritikakundra** [comment]
https://triage.cbioportal.mskcc.org/study/summary?id=hcc_jcopo_msk_2023

- [ ] Hepato be capital in the description? 
- [ ] is survival data from them or IMPACT, can we add from when the survival was computed in the description?
- [ ] No seg data?
- [ ] The description says 90 cfDNA but sample class says 53
- [ ] Do we need other patient ID and patient display name
- [ ] in the paper, " TERT promoter (57%), TP53 (47%), CTNNB1 (37%), ARID1A (18%), and TSC2 (14%)" are these cfDNA numbers? Cos TSC2 is higher than ARID1A in portal.
- [ ] "In total, 37 (73%) patients underwent paired tumor NGS, and concordance was high for mutations observed in patient-matched plasma samples: TERT (83%), TP53 (94%), CTNNB1 (92%), ARID1A (100%), and TSC2 (71%). In 10 (27%) of 37 tumor-plasma samples, alterations were detected by cfDNA analysis that were not detected in the patient-matched tumors. " Are we sure all cfDNA are matched?

**Comment by ritikakundra** [comment]
https://triage.cbioportal.mskcc.org/study/summary?id=sarcoma_msk_2023

- [ ] can we remove radiation associated from the title?
- [ ]  is survival data from them or IMPACT, can we add from when the survival was computed in the description?
- [ ] According to somatic status, 2 are unmatched. Can we confirm from the paper?
- [ ] Are the oncoprints in the paper matching the cohort?
