### ISSUE TITLE
Negative values in Read Counts

### ISSUE THREAD

**Issue by ritikakundra** [cBioPortal/datahub#199]
This issue was reported by a user:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/cbioportal/eER8Y1IzWj0/wga2g53NCAAJ

**Comment by jjgao** [comment]
Issue moved to [cBioPortal/cbioportal #4162](https://github.com/cBioPortal/cbioportal/issues/4162) via [**ZenHub**](https://www.zenhub.com/)
