### ISSUE TITLE
any question for get the genepanel list from  datahub

### ISSUE THREAD

**Issue by Winteric123** [cBioPortal/datahub#2047]
dear contributors of datahub, 
i am a users of cbiopotral,  and i just want to get [gene_panels](https://github.com/cBioPortal/datahub/tree/master/reference_data/gene_panels) from datahub, i has something wrong when i run the code  "git lfs pull -I public/brca_tcga",it suggest the error "batch response::This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access."and i could not download the genepanel list from datahub.i think maybe your LFS do not have enough room for this repository or it is my wrong steps to get the genepanel list from datahub.hope u  can solve my problem quickly!!!

**Comment by steady137** [comment]
This seems to still be a problem. Is there an alternate location to download gene panels in the correct format for importing?

**Comment by rmadupuri** [comment]
Hey @Winteric123, @steady137. Sorry for the inconvenience. Can you give it a try now?

**Comment by steady137** [comment]
Working again, thanks!
`datahub/reference_data/gene_panels on master
❯ git lfs pull -I data_gene_panel_metabric_173.txt 
Downloading LFS objects: 100% (1/1), 1.2 KB | 0 B/s                                                                      `
