### ISSUE TITLE
 Data issue for study: cll_broad_2022

### ISSUE THREAD

**Issue by alexsigaras** [cBioPortal/datahub#2059]
We are trying to import cll_broad_2022 into a private installation of cbioportal and getting this error

```
ERROR: data_clinical_sample.txt: lines [6, 7, 8, (1151 more)]: column 22: Value of numeric attribute is not a real number; values encountered: ['No', 'Yes']
```

Column `22` on `data_clinical_sample.txt` is declared as `NUMBER` in line 3 but all the values are `No` and `Yes` as correctly pointed out. Maybe consider changing to a `STRING`? Let us know if we should open a PR instead?

Thanks,
Alex

**Comment by rmadupuri** [comment]
Hi @alexsigaras, I tried importing the study into a private cBioPortal installation without any issues. The validation succeeded. Column 22 (Expression Cluster Extension Set) in the data_clinical_sample.txt file is correctly set to STRING, with `Yes` or `No` values in both versions downloaded from datahub and cbioportal.org.

Could you confirm if you're using the correct version of the study downloaded from either the datahub or the portal? It’s possible the columns in your files might have become misaligned.

**Comment by alexsigaras** [comment]
Hi @rmadupuri - Confirming that the updates fixed the issue. Closing the issue!
