### ISSUE TITLE
MSK Impact study has two different abdominal wall metastatic site 

### ISSUE THREAD

**Issue by zeynepkaragoz** [cBioPortal/datahub#2076]
"Abdominal wall" and "Abdominal Wall" are loaded as two separate metastatic sites, see screen shot below: 
![image](https://github.com/user-attachments/assets/8ace0ff0-73f1-4f18-82f1-de787e34fb67)

**Comment by Deathnote45** [comment]
hi, Can I work on this issue?

**Comment by sbabyanusha** [comment]
fixed it.
