### ISSUE TITLE
MySQL data dump

### ISSUE THREAD

**Issue by byoo** [cBioPortal/datahub#2085]
Hello,

I would like to download the MySQL export of the latest database, but I could not open this url:
http://download.cbioportal.org/mysql-snapshots/mysql-snapshots-toc.html

Could you advise what I can do to download the MySQL export? Thanks!

**Comment by inodb** [comment]
@byoo thanks for reaching out! @zainasir on our team will take a look at this

**Comment by Wade-Webster** [comment]
@inodb @zainasir

Has there been any progress on this? 

Having the cronjob to automate this process is a solid goal, but the database snapshot has been <ins>unavailable for over a month now</ins>. It would help to have something usable while this other task is completed.

**Comment by zainasir** [comment]
@Wade-Webster The cronjob is in it's final stages. We are going through the standard approval process required to make the database publicly accessible. This should be complete soon.
