### ISSUE TITLE
mutation annotated annotated on a wrong transcript

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#2093]
Reported by [a user](https://groups.google.com/g/cbioportal/c/pN81axm7JN8/m/dAfBKua2AwAJ). [This mutation](https://bit.ly/3NXBE8y) was wrongly annotated. Based [Genome Nexus](https://www.genomenexus.org/variant/3:g.184039136C%3ET), it should be S255L instead of S262L. S266 is on a different isoform.

This happens to most of other mutations in EIF4G1 for [hnsc_tcga_pub](https://bit.ly/3YQgbVk), but they were correctly annotated in [hnsc_tcga_pan_can_atlas_2018](https://bit.ly/3CgRgBo). Would re-annotation by Genome Nexus fix this? I am wondering how often this error happens in production? 

@cBioPortal/curation @inodb @leexgh

**Comment by sbabyanusha** [comment]
@jjgao  Re-annotation fixed the issue. This happened as the MAF was not re-annotated since its upload.
