### ISSUE TITLE
Undefined samples in provisional TCGA studies

### ISSUE THREAD

**Issue by fedde-s** [cBioPortal/datahub#222]
I just tried to load [the current version of the `brca_tcga` study](https://github.com/cBioPortal/datahub/blob/efe0deb4d4fa18a78abd4496884ee751aa90c6be/public/brca_tcga.tar.gz) from the master branch into a cBioPortal v1.12.1 instance, and it failed because many samples had not been explicitly associated with a patient via the sample data file. Is this covered by one of the other issue reports here yet?

**Comment by fedde-s** [comment]
It looked like many, if not all, of the samples were not primary tumour samples; i.e. their IDs were TCGA barcodes that did not have -01 in the sample type position.

**Comment by fedde-s** [comment]
The `gbm_tcga` study has the same issue.

**Comment by yichaoS** [comment]
@fedde-s The data in current "master" branch is not up-to-date, while in current 'RC' branch they are. We do have a plan to merge 'rc' to 'master' very soon, but for now, could you try using the data in 'rc'? The missing sample issue should have been fixed there.

**Comment by fedde-s** [comment]
Thanks! I tried it and it worked, although GitHub wasn't as helpful in downloading a single study folder and I figured out to use [these steps](https://github.com/thehyve/cbioportal-docker/pull/33/files) to get one.

Good luck releasing the rc branch! I think it will help in welcoming people who want to contribute their time to make the software better 😁

Feel free to reuse/extend parts of the notes I just linked if they're any help in documenting how to download studies from the new Datahub release.

**Comment by sandertan** [comment]
@fedde-s Dionne recently documented how to download a single study. Perhaps we can align your and her method? https://github.com/cBioPortal/datahub/pull/190

**Comment by fedde-s** [comment]
Great, yes! I wasn't aware of her patch.

**Comment by sandertan** [comment]
@fedde-s The big RC to Master merge has been done. Can we close this issue?

**Comment by fedde-s** [comment]
Sounds good!
