### ISSUE TITLE
OncoTree code issue

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#225]
It looks many of the oncotree code of many of liquid cancer projects do not have a valid oncotree code. Is it because we have updated the `type_of_cancer` table with the latest oncotree codes but forgot to update `cancer_study` table? If so, we should have a process for updating oncotree in our database and data files.

```
select cancer_study_identifier, type_of_cancer_id
from cancer_study
where type_of_cancer_id not in (
select type_of_cancer_id from type_of_cancer
);
```

in cgds_public:
```
cancer_study_identifier	type_of_cancer_id
ctcl_columbia_2015	ctcl
all_stjude_2013	all
lcll_broad_2013	cll
dlbc_broad_2012	dlbcl
mm_broad	mm
all_stjude_2016	all
cll_iuopa_2015	cll
all_stjude_2015	all
all_phase2_target_2018_pub	all
dlbc_tcga	dlbcl
dlbc_tcga_pan_can_atlas_2018	dlbcl
```

These studies are not displayed in the query page any more.

**Comment by jjgao** [comment]
11 oncotree code were affected in private portal.

all
cll
ctcl
dlbcl
mm

**Comment by jjgao** [comment]
I assume this will also affect oncotree code in clinical data file?

**Comment by yichaoS** [comment]
Just queried public database. This issue is resolved.
