### ISSUE TITLE
change study description for TCGA Pancancer studies

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#240]
Currently, for every study it is "TCGA PanCanAtlas genomic data from 11k cases and all TCGA tumor types (33). The data is expected to be updated.
"

![image](https://user-images.githubusercontent.com/840895/41502978-5b66a78c-7195-11e8-9762-be840c9e8aa3.png)

Can we follow the pattern similar to TCGA provisional studies and change them to: "[TCGA cancer type full name] (from PanCancer Atlas project). Source genomic and clinical data available at https://gdc.cancer.gov/about-data/publications/pancanatlas". (Any suggestions of decription, @schultzn?)

**Comment by yichaoS** [comment]
resolve in https://github.com/cBioPortal/datahub/pull/524
