### ISSUE TITLE
Improving PanCancer Atlas data

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#241]
- [x] survival/followup data - https://pubmed.ncbi.nlm.nih.gov/29625055/
- [ ] clinical data #294
- [x] #1759
- [x] methylation
- [x] rppa
- [x] structural variants
- [ ] miRNA #1220
- [ ] immunologenomics
- [x] microbiome: #1095
- [x] cptac #1235
- [ ] ATACseq: #1158
- [x] rnaseq for normal samples #1221
- [x] msi #1043
- [x] tmb #426
- [x] re-curate arm-level CNA #1308
- [x] ancestry data #1426

**Comment by jjgao** [comment]
@ritikakundra please prioritize this one when you have a chance.

**Comment by yichaoS** [comment]
rppa and miRNA:
https://gdc.cancer.gov/node/977
![image](https://user-images.githubusercontent.com/5973438/59123051-52112d80-892a-11e9-83fa-8420dc57f37a.png)
![image](https://user-images.githubusercontent.com/5973438/59123073-605f4980-892a-11e9-851d-39cb09a99ecd.png)

**Comment by jjgao** [comment]
adding microbiome data https://github.com/cBioPortal/datahub/issues/1095 to the list above.

**Comment by yichaoS** [comment]
@jjgao @ritikakundra An old issue that might still be relative: https://github.com/cBioPortal/datahub/issues/294

**Comment by jjgao** [comment]
discussion related to methylation: https://github.com/cBioPortal/datahub/issues/1210

**Comment by jjgao** [comment]
added msi and tmb to the list

**Comment by jjgao** [comment]
added the cptac data to the list.

**Comment by jjgao** [comment]
added #1385 - re-curate arm-level CNA.

**Comment by jjgao** [comment]
added https://github.com/cBioPortal/datahub/issues/1426 - ancestry data.

**Comment by sbabyanusha** [comment]
This can be followed up in #1796
