### ISSUE TITLE
pancan atlas LGG data shows up under the wrong heading in query selector

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/datahub#244]
PanCancer Atlas LGG shows up under "Encapsulated Glioma" but should appear under "Diffuse Glioma" with all the other LGG datasets.

![image](https://user-images.githubusercontent.com/10508276/41620511-e8fb98c0-73d7-11e8-87c9-c57f5885445b.png)

![image](https://user-images.githubusercontent.com/10508276/41620515-ede31fb6-73d7-11e8-82b1-fc6131dd46ed.png)

**Comment by jjgao** [comment]
@ritikakundra the OV pancan study is not in a wrong position. Could you please check other studies too?

![image](https://user-images.githubusercontent.com/840895/41989059-0ca30efe-7a0c-11e8-9f69-d6c10a933ac6.png)

**Comment by ritikakundra** [comment]
Fixed
