### ISSUE TITLE
mutation_type data issue

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#247]
@jjgao commented on [Wed Apr 12 2017](https://github.com/cBioPortal/cbioportal/issues/2323)

There are some non-standard mutation types in the public portal database: [data-issue.xlsx](https://github.com/cBioPortal/cbioportal/files/917517/data-issue.xlsx) For example, nsclc_tcga_broad_2016 has no genomic locations.

Can we fix the data?

Below is the code to pull out the spreadsheet above.

```
select mutation_type, count(*)
from mutation_event
group by mutation_type;

select gp.stable_id, chr, start_position, end_position, reference_allele, tumor_seq_allele, protein_change, mutation_type
from mutation_event me, mutation m, genetic_profile gp
where me.mutation_event_id = m.mutation_event_id
and m.genetic_profile_id=gp.genetic_profile_id
and me.mutation_type in ('splice','Missense','Indel', 'NA', 'InFrameIns', 'Splice_site_SNP');
```

**Comment by jjgao** [comment]
Here is an updated list:

mutation_type	count(*)
Start_Codon_SNP	1
nonframeshift.deletion	1
vIII deletion	1
Exon skipping	1
exon14skip	1
Splice_Site_SNP	1
COMPLEX_INDEL	1
nonframeshift	1
Essential splice	2
ESSENTIAL_SPLICE_SITE	2
frameshift-deletion	2
frameshift_deletion	2
lincRNA	3
nonframeshift-deletion	4
Nonsense	4
Silent	5
Indel	6
frameshift	6
In frame INDEL	7
Splicing Site Mutation	8
NON_SYNONYMOUS_CODING	14
stopgain	15
Frame Shift INDEL	19
FRAMESHIFT_CODING	27
splice	28
Missense	29
Frame_Shift	32
3UTR	40
non-coding-exon	51
5UTR	51
5'Flank	53
coding	60
nonsynonymous	92
5Flank	121
NA	782
Nonstop_Mutation	2950
In_Frame_Ins	3125
Translation_Start_Site	3780
Targeted_Region	6518
In_Frame_Del	17289
Frame_Shift_Ins	43871
Fusion	50049
Splice_Region	63858
Splice_Site	70971
Frame_Shift_Del	100550
Nonsense_Mutation	184773
Missense_Mutation	2469774

**Comment by yichaoS** [comment]
@jjgao Updated list:
cll_iuopa_2015: 3 variants 
hcc_inserm_fr_2015_mutations: 7 variants
skcm_yale_mutations: 3 variants

**Comment by yichaoS** [comment]
@jjgao updated list:

5'Flank	74 (acc_tcga, included in mutated issue) 
Essential splice	2
Frame_Shift	1 (msk_impact_2017, ???)
Frame_Shift_Del	147813
Frame_Shift_Ins	62016
Fusion	67463
In_Frame_Del	26211
In_Frame_Ins	6440
Missense	3 (skcm_yale)
Missense_Mutation	3476025
NA	8 (hcc_inserm_fr_2015, cll_iuopa_2015, included in mutated issue)
Nonsense_Mutation	243791
Nonstop_Mutation	4084
p.Q274L	1 (cesc_tcga, included in mutated issue)
Splice_Region	89463
Splice_Site	100474
Targeted_Region	177
Translation_Start_Site	5856

**Comment by jjgao** [comment]
This looks much better! Thanks, @yichaoS. I am wondering how's our private databases look like?

**Comment by sbabyanusha** [comment]
Ran the query in private DB just now and the results are as below: (the number is # of mutations w/ this issue)

29 accrf_merged_unfiltered_mutations
29 acyc_fmi_morris_unfiltered_mutations
64 all_phase2_target_2017_mutations
315 aml_target_2017_mutations
1 blca_cmo_solitd_5931_b_mutations
1 brca_mskcc_solitd_5065_g_mutations
1 brca_sanger_2012_mutations
1 brca_sanger_2016_mutations
3 breast_msk_2017_mutations
1 cellline_cclp_sanger_mutations
20 cgci_blgsp_2017_mutations
2 coadread_cbe_saltzl_5281_mi_mutations
2 coadread_saltzl_2015_mutations
22 egc_msk_janjigy_2017_mutations
101 gbm_yale_mutations
1 gct_tcga_freeze_mutations
1 lcll_13-079_mskcc_foundation_mutations
1 lihc_tcga_pub_mutations
3 lms_cbe_agaramn_4786_mutations
1 lymphoma_filtered_merged_mutations
1 lymphoma_merged_mutations
4 mbl_icgc_2014_mutations
14 mixed_13-060_mskcc_foundation_mutations
1 mixed_13-158_mskcc_foundation_mutations
3 mixed_dmp_MSK-IMPACT_2013_mutations
22 mixed_gray_proj_06208_mutations
1 mixed_lymphoma-sa_therp_filtered_mskcc_foundation_mutations
1 mixed_lymphoma-sa_therp_mskcc_foundation_mutations
30 mixed_lymph_mskcc_foundation_160830_mutations
2 mpn_cbe_rampalr_RR_mpnaml_mutations
64 mpn_mskcc_2015_mutations
2 nbl_target_2017_mutations
1 nsclc_msk_subset_2018_mutations
2 os_target_2017_mutations
1 ovt_levine_2015_mutations
2 prad_mskcc_foundation_mutations
2 prad_su2c_2018_prad_su2c_mutations
3 thca_mskcc_faginj_2014_mutations
3 thhc_mskcc_2015_chant_mutations
1 ulm_cbe_weigeltb_BW_lmbn_mutations
1 wt_target_2017_mutations
