### ISSUE TITLE
Prostate Neuroendocrine study is missing mRNA z-scores

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#250]
@schultzn commented on [Thu Jul 05 2018](https://github.com/cBioPortal/cbioportal/issues/4436)

The neuroendocrine prostate cancer study is missing the mRNA z-scores. RNA expression levels are there, you just can't query the data.
 http://www.cbioportal.org/study?id=nepc_wcm_2016

---

@schultzn commented on [Thu Jul 05 2018](https://github.com/cBioPortal/cbioportal/issues/4436#issuecomment-402826420)

This was reported by a user:
https://groups.google.com/forum/#!topic/cbioportal/Ur-XlJwzUnI

**Comment by rmadupuri** [comment]
Zscores were added in https://github.com/cBioPortal/datahub/pull/791
