### ISSUE TITLE
list of studies with mRNA data but no z-score profiles

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#251]
Since we have a few studies missing z-score profiles (#250, #242), I did a query in the public data and find if we have more.

```sql
select distinct cs.cancer_study_identifier
from cancer_study cs, genetic_profile gp
where cs.cancer_study_id=gp.cancer_study_id
and gp.genetic_alteration_type="MRNA_EXPRESSION" and
cs.cancer_study_id not in (
 select cs1.cancer_study_id
 from cancer_study cs1, genetic_profile gp1
 where cs1.cancer_study_id=gp1.cancer_study_id
 and gp1.datatype="Z-SCORE"
)
```

```
prad_mskcc_cheny1_organoids_2014
nepc_wcm_2016
prad_eururol_2017
rt_target_2018_pub
```

@ritikakundra @angelicaochoa : please look into the studies above.

@sheridancbio : maybe you could add this into the database validation code?

Note: this is not a complete list since we don't know if a study have z-score profiles for all of its expression profiles.

**Comment by jjgao** [comment]
Updated list:

```
prad_mskcc_cheny1_organoids_2014
nepc_wcm_2016
prad_eururol_2017
brca_metabric
```

**Comment by yichaoS** [comment]
Updated list: 
utuc_cornell_baylor_mdacc_2019
prad_eururol_2017
pcpg_tcga_pub
aml_ohsu_2018
gbm_mayo_pdx_sarkaria_2019
brca_tcga_pub2015

**Comment by rmadupuri** [comment]
The above query in public db doesn't return anything now. The missing diploid ref zscores were added to all studies in https://github.com/cBioPortal/datahub/pull/1164 and imported.
