### ISSUE TITLE
Mutation data curation issue

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#255]
I noticed there are many deletion/insertions annotated as missense mutations. For example:

http://www.cbioportal.org/case.do#/patient?studyId=brca_broad&caseId=BR-M-189

![image](https://user-images.githubusercontent.com/840895/42531382-d19c159e-8451-11e8-91ed-c9215ffeb253.png)

So I did some database query:

```sql
select distinct gp.stable_id as profile, count(*)
from mutation m, mutation_event me, genetic_profile gp, sample s, gene g
where
m.mutation_event_id=me.mutation_event_id
and gp.genetic_profile_id=m.genetic_profile_id
and me.entrez_gene_id=g.entrez_gene_id
and m.sample_id=s.internal_id
and mutation_type="Missense_Mutation" and tumor_seq_allele="-"
group by gp.stable_id
```

and found out there are 6922 mutation events with this problem.

```
prad_mich_mutations	3081
brca_broad_mutations	3062
mbl_icgc_mutations	669
sclc_cancercell_gardner_2017_mutations	21
ucec_tcga_pub_mutations	15
prad_p1000_mutations	13
cellline_nci60_mutations	9
kirc_tcga_pub_mutations	9
stad_tcga_pub_mutations	7
nsclc_tcga_broad_2016_mutations	6
prad_su2c_2015_mutations	5
lusc_tcga_pub_mutations	3
escc_icgc_mutations	2
brca_metabric_mutations	2
hnsc_broad_mutations	2
ov_tcga_pub_mutations	2
ccrcc_utokyo_2013_mutations	1
brca_tcga_pub_mutations	1
acyc_mda_2015_mutations	1
liad_inserm_fr_2014_mutations	1
lgggbm_tcga_pub_mutations	1
laml_tcga_pan_can_atlas_2018_mutations	1
skcm_broad_mutations	1
coad_tcga_pan_can_atlas_2018_mutations	1
prad_broad_mutations	1
lihc_tcga_pan_can_atlas_2018_mutations	1
paad_tcga_pan_can_atlas_2018_mutations	1
hnsc_mdanderson_2013_mutations	1
esca_broad_mutations	1
kirp_tcga_pan_can_atlas_2018_mutations	1
```

For example:

```sql
select me.chr, me.start_position, me.end_position, me.reference_allele, me.tumor_seq_allele, m.tumor_seq_allele1, m.tumor_seq_allele2, me.mutation_type, g.hugo_gene_symbol,me.protein_change, gp.stable_id as profile, s.stable_id as sample
from mutation m, mutation_event me, genetic_profile gp, sample s, gene g
where
m.mutation_event_id=me.mutation_event_id
and gp.genetic_profile_id=m.genetic_profile_id
and me.entrez_gene_id=g.entrez_gene_id
and m.sample_id=s.internal_id
and mutation_type="Missense_Mutation" and tumor_seq_allele="-"
```

```
chr	start_position	end_position	reference_allele	tumor_seq_allele	tumor_seq_allele1	tumor_seq_allele2	mutation_type	hugo_gene_symbol	protein_change	profile	sample
17	7577538	7577538	C	-	-	T	Missense_Mutation	TP53	R248Q	brca_broad_mutations	BR-M-189
17	7577085	7577085	C	-	-	T	Missense_Mutation	TP53	E285K	brca_broad_mutations	BR-V-008
17	7578271	7578271	T	-	-	C	Missense_Mutation	TP53	H193R	brca_broad_mutations	BR-V-043
17	7577121	7577121	G	-	-	A	Missense_Mutation	TP53	R273C	brca_broad_mutations	BR-M-192
17	7577121	7577121	G	-	-	A	Missense_Mutation	TP53	R273C	prad_mich_mutations	WA40
17	7577121	7577121	G	-	-	A	Missense_Mutation	TP53	R273C	prad_mich_mutations	WA54
17	7578461	7578461	C	-	-	A	Missense_Mutation	TP53	V157F	brca_broad_mutations	BR-V-067
3	178936082	178936082	G	-	-	C	Missense_Mutation	PIK3CA	E542Q	brca_broad_mutations	BR-M-083
17	7578442	7578442	T	-	-	C	Missense_Mutation	TP53	Y163C	brca_broad_mutations	BR-V-045
```

The reason was `tumor_seq_allele1` and `tumor_seq_allele2` are different. I looked at the [suppl. data of brca_broad](https://www.nature.com/articles/nature11154#s1) and they only have one column `Tumor Allele`. It looked like this column was copied over to tumor_seq_allele2 to our MAF and `-` was filled in `tumor_seq_allele1`. I suspect the same happened to `prad_mich`. @ritikakundra could you look into them? It would be good to fix prad_mich, brca_broad, and mbl_icgc first?

**Comment by yichaoS** [comment]
@jjgao @ritikakundra After a few rounds of public clean up, here is the updated result of this query in private database: 
acc_tcga_pan_can_atlas_2018_mutations	1
blca_tcga_pan_can_atlas_2018_mutations	8
brca_tcga_pan_can_atlas_2018_mutations	13
cesc_tcga_pan_can_atlas_2018_mutations	3
coadread_tcga_pan_can_atlas_2018_mutations	11
dlbc_13-081_mskcc_foundation_mutations	1
dlbc_tcga_pan_can_atlas_2018_mutations	2
esca_tcga_pan_can_atlas_2018_mutations	5
gbm_fmi_mskcc_2018_mutations	1
gbm_tcga_pan_can_atlas_2018_mutations	1
gbm_yale_mutations	2
genie_mutations	2
glioma_mskcc_2018_mutations	1
hnsc_tcga_pan_can_atlas_2018_mutations	5
kirc_tcga_pan_can_atlas_2018_mutations	3
kirp_tcga_pan_can_atlas_2018_mutations	8
laml_tcga_pan_can_atlas_2018_mutations	1
lgg_tcga_pan_can_atlas_2018_mutations	1
lihc_tcga_pan_can_atlas_2018_mutations	6
luad_tcga_pan_can_atlas_2018_mutations	8
lusc_tcga_pan_can_atlas_2018_mutations	4
lymphoma_merged_mutations	3
lymphoma_super_cohort_fmi_msk_060518_mutations	1
lymphoma_super_cohort_fmi_msk_mutations	1
lymph_landscape_fmi_lymph_fmi_batlevi_landscape_mutations	10
meso_tcga_pan_can_atlas_2018_mutations	2
mixed_13-060_mskcc_foundation_mutations	4
mixed_13-158_mskcc_foundation_mutations	3
mixed_impact_wes_2017_mutations	27
mixed_laml-pif_mskcc_foundation_mutations	1
mixed_lymphoma-sa_therp_mskcc_foundation_mutations	2
mixed_lymphoma_mskcc_foundation_mutations	1
mixed_lymph_mskcc_foundation_160830_mutations	6
mixed_mskcc_cud_wes_2016_mutations	5
mm_mmrf_2018_mutations	23
mskimpact_pp_mutations	3
ov_tcga_pan_can_atlas_2018_mutations	15
ov_tcga_pub_mutations	2
paad_cid_mutations	23
paad_tcga_pan_can_atlas_2018_mutations	3
plmeso_tcga_pub_mutations	4
prad_mskcc_2015_pan_merged_mutations	3016
prad_mskcc_2015_pan_met_mutations	3016
prad_tcga_pan_can_atlas_2018_mutations	6
sarc_tcga_pan_can_atlas_2018_mutations	1
sarc_tcga_pub_mutations	2
skcm_tcga_pan_can_atlas_2018_mutations	2
stad_mskcc_2016_mutations	3
stad_tcga_pan_can_atlas_2018_mutations	13
ucec_mskcc_levine_2015_mutations	1
ucec_tcga_pan_can_atlas_2018_mutations	11
uvm_tcga_pan_can_atlas_2018_mutations	1
yesterday_lymphoma_super_cohort_fmi_msk_mutations	1

**Comment by jjgao** [comment]
Thanks, @yichaoS. How are we going to deal with them?

Is public portal up to date now?

**Comment by jjgao** [comment]
Any update on this?

**Comment by yichaoS** [comment]
@jj this is the updated list in public portal: 
ccrcc_utokyo_2013_mutations	1
coadread_tcga_pan_can_atlas_2018_mutations	1
esca_broad_mutations	1
escc_icgc_mutations	2
hnsc_broad_mutations	2
kirc_tcga_pub_mutations	9
kirp_tcga_pan_can_atlas_2018_mutations	1
laml_tcga_pan_can_atlas_2018_mutations	1
lgggbm_tcga_pub_mutations	1
liad_inserm_fr_2014_mutations	1
lihc_tcga_pan_can_atlas_2018_mutations	1
lusc_tcga_pub_mutations	3
mixed_pipseq_2017_mutations	26
nsclc_tcga_broad_2016_mutations	6
ov_tcga_pub_mutations	2
paad_tcga_pan_can_atlas_2018_mutations	1
pediatric_dkfz_2017_mutations	4
prad_broad_mutations	1
prad_p1000_mutations	13
skcm_broad_mutations	1

**Comment by jjgao** [comment]
thanks, @yichaoS!

**Comment by yichaoS** [comment]
@jjgao @ritikakundra @rmadupuri After the cleanup/rebuild of the public database, this is the updated query result:
coadread_tcga_pan_can_atlas_2018_mutations	1
kirp_tcga_pan_can_atlas_2018_mutations	1
laml_tcga_pan_can_atlas_2018_mutations	1
lihc_tcga_pan_can_atlas_2018_mutations	1
paad_tcga_pan_can_atlas_2018_mutations	1

**Comment by ritikakundra** [comment]
@yichaoS That's great! We can fix these easily

**Comment by jjgao** [comment]
Great job 👍  Let's fix the rest and close this!

**Comment by jjgao** [comment]
It may be a good idea to run this type of analysis from time to time. Maybe discuss with @n1zea144 and see if it's possible to add it as part of the database test process.

**Comment by ritikakundra** [comment]
@jjgao From our curators last meeting, I zeroed on these issues:
https://github.com/cBioPortal/datahub/issues/621
https://github.com/cBioPortal/datahub/issues/225
And this one. 
We can add more to doing such analysis from time to time.

**Comment by jjgao** [comment]
@ritikakundra great! Maybe it's a good idea to start an issue to collect these analyses?

**Comment by yichaoS** [comment]
@here GN fixes expected: https://github.com/genome-nexus/genome-nexus/issues/288
