### ISSUE TITLE
Chapuy et al., Nature Medicine 24, 679–690 (2018) 

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/datahub#256]
https://www.nature.com/articles/s41591-018-0016-8

Have not checked data availability yet

- [x] [create a issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [x] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [x] Document the curation process, e.g. how and by whom the data was transformed
- [x] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [ ] Create a pull request to datahub once the data is curated
- [x] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

**Comment by ritikakundra** [comment]
Does study name and study ID follow our convention? e.g. Tumor_Type (Institue, Journal Year); brca_mskcc_2015
  is study meta data complete? e.g. pmid, group of PUBLIC
  were all samples profiled with WES/WGS? If not, is gene panel file curated?
  are oncotree codes of all samples curated; Cancer Type and Cancer Type Detailed needs to be added in addition to Oncotree Code
  clinical sample and patient data with meta files
  mutations data with meta files
  MAF is based on hg19
  MAF with 2 isoforms: uniprot and mskcc
  CNA data with meta files
  CNA segment data with meta files
  Expression data including z-scores with meta files
  Case-lists for all profiles.
  Passes Validation
  Manual checking (Niki or JJ): Triage Portal

**Comment by schultzn** [comment]
@rmadupuri Can you please prioritize this study? Thanks!

**Comment by schultzn** [comment]
@rmadupuri Is this one ready to go out?
