### ISSUE TITLE
New Studies

### ISSUE THREAD

**Issue by ritikakundra** [cBioPortal/datahub#257]
- [ ] 20399149 : Data Issue - Missing genomic data
- [ ] 20129251 : Data Issue - Missing genomic data
- [ ] 28825729 : Need to be curated - has multiple MAFs
- [x] 28985567 : Curated (For August Release)
- [ ] 28635960 : Paper is on somatic mutations in rheumatoid arthritis
- [ ] 28658208 : Data Issue - Missing data
- [ ] 28622513 : Data Issue - Missing genomic data
- [ ] 24920063 : Data Issue
- [ ] 26683228 : Need to be curated
- [ ] 25583493 : Need to be curated
- [ ] 27959731 : Need to be curated
- [ ] 26950094 : Need to be curated
- [ ] 25526346 : Need to be curated
- [ ] 25636086 : Data Issue - Missing genomic data
- [ ] 27064257 : Data Issue - Missing genomic data
- [x] 26437033 : Curated (For August Release)
- [ ] 27182968 : Data Issue - MAF with 6k missing gene symbols
- [ ] 23313954 : Data Issue - MAF has no sample info
- [ ] 26806338 : Data Issue - Missing Clinical data and MAF has no sample info
- [ ] 27276561 : Data Issue - Missing Clinical data and MAF has no gene symbols
- [ ] 28162975 : Need to be curated
- [x] 26977886 : Curated (For August Release)
- [x] 26466571 : Curated (For August Release)

TCGA Publications 
- [ ] 26091043 : Genomic data in GDC under controlled access
- [ ] 26824661 
- [ ] 26536169 
- [ ] 26061751

**Comment by jjgao** [comment]
@ritikakundra maybe we can break this list into issues per study? Maybe @rmadupuri can help?

**Comment by schultzn** [comment]
Reviving this one - would be nice to have these as separate issues with the full citation in the title.

**Comment by jjgao** [comment]
@rmadupuri thanks for creating the separate issues.

**Comment by jjgao** [comment]
@cBioPortal/curation I am wondering if the studies above have been all be captured?

**Comment by rmadupuri** [comment]
@jjgao closing this issue. Each study is captured in a separate issue now.
