### ISSUE TITLE
Schmitz et al., N Engl J Med. 2018 Apr 12;378(15):1396-1407

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/datahub#258]
https://www.ncbi.nlm.nih.gov/pubmed/29641966

The dataset is on dbGAP (NCICCR: phs001444) and GDC (NCICCR-DLBCL)

- [ ] [create a issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [ ] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [ ] Document the curation process, e.g. how and by whom the data was transformed
- [ ] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [ ] Create a pull request to datahub once the data is curated
- [ ] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

**Comment by schultzn** [comment]
@rmadupuri Can you please prioritize this one as well?

**Comment by rmadupuri** [comment]
NOTE: Most of the samples in this study lacked matched normal. The manuscript contains only clinical data associated with it.  Genomic data files are under controlled access in GDC.
(https://gdc.cancer.gov/about-data/publications/DLBCL-2018)

**Comment by jjgao** [comment]
Should we reach out to the author?
