### ISSUE TITLE
public data curation workflow

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#259]
@ritikakundra I think we should have a documented workflow for curating public studies. Here is a rough draft. Please feel free to edit.

- [ ] [create a issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [ ] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [ ] Document the curation process, e.g. how and by whom the data was transformed
- [ ] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [ ] Create a pull request to datahub once the data is curated
- [ ] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

**Comment by ritikakundra** [comment]
@jjgao I moved the checklist before pull request and also added MSK import.
