### ISSUE TITLE
Missing description RNA-Seq normalization

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/datahub#26]
In the meta file for the RNA-Seq of the TCGA provisional data, a description is missing how the data is normalized. It only states: `Expression levels for 20532 genes in 171 gbm cases (RNA Seq V2 RSEM).`
The file does not contain raw read counts, because the values are floats. Also contains some extreme outliers. Information on this is probably located on https://gdc.cancer.gov/ which hosts the TCGA data. 

As an example, some statistics on the values in `gbm_tcga`:
```
> expr_data[1:5,1:5]
          TCGA-02-0047-01 TCGA-02-0055-01 TCGA-02-2483-01 TCGA-02-2485-01 TCGA-02-2486-01
100134869          6.7611         15.6973         13.9398         14.9571          4.8049
10357             54.7036         31.3945         60.3441         91.8238         62.5366
155060           232.9512        162.0182        135.0923        417.6190        276.2195
26823              0.0000          0.5606          0.0000          1.9048          0.0000
280660             0.0000          0.0000          0.0000          0.0000          0.0000

> range(expr_data)
[1]       0 1026361
```
Boxplots including outliers:
![boxplot_rnaseq](https://cloud.githubusercontent.com/assets/9624990/23654216/ebf8d750-032f-11e7-902b-85a14d498533.png)

Boxplots without outliers:
![boxplot_zscores_no-outliers](https://cloud.githubusercontent.com/assets/9624990/23654227/fdf9bafa-032f-11e7-9f5d-f1c996e474af.png)

**Comment by dionnezaal** [comment]
In current version from gbm_tcga on datahub no extra description is added to the meta file. But currently in file-formats.md in the hotfix branch documentation was added about RNA Seq V2 RSEM: https://github.com/cBioPortal/cbioportal/pull/3253.

**Comment by sandertan** [comment]
Current state of datahub meta files for RNA-Seq is good, so Im closing this issue.

brca_tcga expression z-scores:
mRNA z-Scores (RNA Seq V2 RSEM) compared to the expression distribution of each gene tumors that are diploid for this gene.
