### ISSUE TITLE
incorrect gene symbol and entrez ID

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#262]
I came across one mutation that was annotated wrong.

In [this sample](http://www.cbioportal.org/case.do#/patient?studyId=nhl_bcgsc_2013&caseId=MD903), there is a mutation in H3F3A.

![image](https://user-images.githubusercontent.com/840895/42774470-cc82aa20-88ff-11e8-8f38-be71173a1977.png)

But the correct gene should be `PRSS38`: http://www.genomenexus.org/annotation/1:g.228003871G%3EA

The error was introduced in the curated MAF. Not sure how many other mutations are affected.

When we reannotate the MAF, we should override the gene symbols and entrez gene IDs to solve issues like this.

**Comment by ritikakundra** [comment]
Fixed
