### ISSUE TITLE
oncotree_code inconsistency

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#264]
@jjgao commented on [Wed Jul 11 2018](https://github.com/cBioPortal/cbioportal/issues/4445)

Oncotree_code in the clinical data and our database are no longer up to date. We should migrate them to the latest version. CANCER_TYPE and CANCER_TYPE_DETAILED should also be update.

---

@ritikakundra commented on [Thu Jul 12 2018](https://github.com/cBioPortal/cbioportal/issues/4445#issuecomment-404506109)

@jjgao Do you have a way to find those studies?

---

@jjgao commented on [Thu Jul 12 2018](https://github.com/cBioPortal/cbioportal/issues/4445#issuecomment-404700162)

We can write a script to look for outdated oncotree code in clinical data table. I could do that next week. But maybe @yichaoS can help on this? @yichaoS please share your sql query code here if you can do.

---

@jjgao commented on [Thu Jul 12 2018](https://github.com/cBioPortal/cbioportal/issues/4445#issuecomment-404700323)

And this is also impacting internal data. Maybe we need some code in the pipeline to convert old oncotree codes to new ones. @n1zea144 @sheridancbio

**Comment by jjgao** [comment]
@ritikakundra I just queried the public database:

```sql
select cancer_study_identifier, group_concat(distinct attr_value)
from clinical_sample cs
join sample s on cs.internal_id=s.internal_id
join patient p on s.patient_id=p.internal_id
join cancer_study cas on cas.cancer_study_id=p.cancer_study_id
where attr_id="ONCOTREE_CODE" and attr_value not in (
 select type_of_cancer_id
 from type_of_cancer
)
group by cancer_study_identifier
```

and found 13 studies with outdated oncotree codes in their clinical data:


cancer_study_identifier | group_concat(distinct attr_value)
-- | --
all_stjude_2013 | BALL
all_stjude_2015 | BALL,ALL,LEUK,TALL
all_stjude_2016 | ALL
ampca_bcm_2016 | AMPAC
cellline_nci60 | LEUK
ctcl_columbia_2015 | SEZS,CTCL
dlbc_broad_2012 | DLBCL
dlbc_tcga | DLBCL
dlbc_tcga_pan_can_atlas_2018 | DLBCL
lcll_broad_2013 | CLL
mixed_pipseq_2017 | PTCLNOS,BALL
mm_broad | MM
msk_impact_2017 | DLBCL,CLL,TNKL,HIST,TALL,BCL,SLL,MBCL,MM,MALTL

**Comment by jjgao** [comment]
And here are the samples without `oncotree_code`:

cancer_study_identifier | sample_ids
-- | --
brca_tcga_pub | TCGA-A2-A0CK-01,TCGA-A2-A0CO-01,TCGA-A2-A0CR-01,TCGA-A2-A3KC-01,TCGA-A2-A3KD-01,TCGA-A7-A13H-01,TCGA-A7-A2KD-01,TCGA-A7-A3IY-01,TCGA-A7-A3IZ-01,TCGA-A7-A3J0-01,TCGA-A7-A3J1-01,TCGA-A7-A3RF-01,TCGA-AC-A23G-01,TCGA-AC-A2BK-01,TCGA-AC-A2BM-01,TCGA-AC-A2FE-01,TCGA-AC-A2FK-01,TCGA-AC-A2FM-01,TCGA-AC-A2FO-01,TCGA-AC-A2QH-01,TCGA-AC-A2QI-01,TCGA-AC-A2QJ-01,TCGA-AC-A3BB-01,TCGA-AC-A3EH-01,TCGA-AC-A3HN-01,TCGA-AC-A3OD-01,TCGA-AC-A3QQ-01,TCGA-AC-A3TM-01,TCGA-AC-A3TN-01,TCGA-AC-A3W5-01,TCGA-AC-A3W6-01,TCGA-AC-A3W7-01,TCGA-AR-A1AM-01,TCGA-AR-A2LE-01,TCGA-AR-A2LH-01,TCGA-AR-A2LJ-01,TCGA-AR-A2LK-01,TCGA-AR-A2LL-01,TCGA-AR-A2LM-01,TCGA-AR-A2LN-01,TCGA-AR-A2LO-01,TCGA-AR-A2LQ-01,TCGA-AR-A2LR-01,TCGA-B6-A0I1-01,TCGA-B6-A2IU-01,TCGA-BH-A0B6-01,TCGA-BH-A28O-01,TCGA-BH-A2L8-01,TCGA-C8-A3M7-01,TCGA-C8-A3M8-01,TCGA-E2-A14U-01,TCGA-E2-A1LE-01,TCGA-E2-A2P5-01,TCGA-E2-A2P6-01,TCGA-E2-A3DX-01,TCGA-E9-A2JS-01,TCGA-E9-A2JT-01,TCGA-E9-A3HO-01,TCGA-E9-A3Q9-01,TCGA-E9-A3QA-01,TCGA-EW-A1PC-01,TCGA-EW-A2FR-01,TCGA-EW-A3U0-01,TCGA-GI-A2C9-01,TCGA-GM-A3NW-01,TCGA-GM-A3NY-01,TCGA-HN-A2NL-01
cellline_nci60 | CSF_268,CSF_295,CSF_539,CSNB_19,CSNB_75,CU251,X786_0
es_iocurie_2014 | IC315,IC316,IC319
gbm_tcga_pub | TCGA-06-0119-01,TCGA-06-0121-01,TCGA-06-0165-01,TCGA-06-1806-01,TCGA-15-1444-01,TCGA-28-2501-01,TCGA-28-2510-01,TCGA-76-6283-01,TCGA-76-6660-01,TCGA-06-0676-01,TCGA-08-0625-01,TCGA-06-0678-01,TCGA-06-0675-01,TCGA-08-0623-01,TCGA-06-0681-01,TCGA-06-0673-01,TCGA-08-0627-01,TCGA-06-0680-01,TCGA-08-0626-01
hcc_msk_venturaa_2018 | s_AV_hcchca_019_N
hnsc_tcga_pub | TCGA-BB-8596-01,TCGA-BB-8601-01,TCGA-C9-A47Z-01,TCGA-C9-A480-01,TCGA-CN-A497-01,TCGA-CN-A498-01,TCGA-CN-A499-01,TCGA-CN-A49A-01,TCGA-CN-A49B-01,TCGA-CN-A49C-01,TCGA-CQ-5333-01,TCGA-CQ-7063-01,TCGA-CQ-7064-01,TCGA-CQ-7069-01,TCGA-CQ-A4C6-01,TCGA-CQ-A4C7-01,TCGA-CQ-A4C9-01,TCGA-CQ-A4CA-01,TCGA-CQ-A4CB-01,TCGA-CQ-A4CD-01,TCGA-CV-A45O-01,TCGA-CV-A45P-01,TCGA-CV-A45Q-01,TCGA-CV-A45R-01,TCGA-CV-A45T-01,TCGA-CV-A45U-01,TCGA-CV-A45V-01,TCGA-CV-A45W-01,TCGA-CV-A45X-01,TCGA-CV-A45Y-01,TCGA-CV-A45Z-01,TCGA-CV-A460-01,TCGA-CX-A4AQ-01,TCGA-D6-8568-01,TCGA-D6-8569-01,TCGA-D6-A4Z9-01,TCGA-D6-A4ZB-01,TCGA-F7-8298-01,TCGA-F7-8489-01,TCGA-H7-8501-01,TCGA-H7-8502-01,TCGA-HD-8224-01,TCGA-HD-8314-01,TCGA-HD-8634-01,TCGA-HD-8635-01,TCGA-HD-A4C1-01
kirc_tcga_pub | TCGA-CJ-4642-01,TCGA-CW-6096-01
lusc_tcga_pub | TCGA-21-1072-01,TCGA-21-1075-01,TCGA-21-1079-01,TCGA-21-1080-01,TCGA-21-1082-01,TCGA-21-1083-01,TCGA-21-5783-01,TCGA-22-1000-01,TCGA-22-1005-01,TCGA-22-1017-01,TCGA-22-4596-01,TCGA-22-4605-01,TCGA-22-4609-01,TCGA-22-5479-01,TCGA-22-5481-01,TCGA-22-5483-01,TCGA-33-4587-01,TCGA-33-6738-01,TCGA-34-2604-01,TCGA-34-2609-01,TCGA-34-7107-01,TCGA-37-3792-01,TCGA-37-4129-01,TCGA-37-4130-01,TCGA-37-4132-01,TCGA-39-5011-01,TCGA-39-5034-01,TCGA-39-5040-01,TCGA-43-2576-01,TCGA-43-2581-01,TCGA-43-5670-01,TCGA-43-6773-01,TCGA-43-7656-01,TCGA-43-7657-01,TCGA-43-7658-01,TCGA-43-8115-01,TCGA-43-8116-01,TCGA-52-7622-01,TCGA-52-7809-01,TCGA-52-7810-01,TCGA-52-7811-01,TCGA-52-7812-01,TCGA-56-7221-01,TCGA-56-7222-01,TCGA-56-7223-01,TCGA-56-7579-01,TCGA-56-7580-01,TCGA-56-7582-01,TCGA-56-7730-01,TCGA-56-7731-01,TCGA-56-7822-01,TCGA-56-7823-01,TCGA-56-8082-01,TCGA-56-8083-01,TCGA-56-8201-01,TCGA-56-8305-01,TCGA-56-8307-01,TCGA-56-8308-01,TCGA-56-8309-01,TCGA-58-8386-01,TCGA-58-8387-01,TCGA-60-2695-01,TCGA-60-2696-01,TCGA-60-2697-01,TCGA-60-2703-01,TCGA-60-2704-01,TCGA-60-2706-01,TCGA-60-2714-01,TCGA-60-2716-01,TCGA-63-7020-01,TCGA-63-7021-01,TCGA-63-7022-01,TCGA-63-7023-01,TCGA-66-2737-01,TCGA-66-2753-01,TCGA-66-2769-01,TCGA-66-2790-01,TCGA-68-7755-01,TCGA-68-7756-01,TCGA-68-7757-01,TCGA-68-8250-01,TCGA-68-8251-01,TCGA-77-6842-01,TCGA-77-6843-01,TCGA-77-6844-01,TCGA-77-6845-01,TCGA-77-7138-01,TCGA-77-7139-01,TCGA-77-7140-01,TCGA-77-7141-01,TCGA-77-7142-01,TCGA-77-7335-01,TCGA-77-7337-01,TCGA-77-7338-01,TCGA-77-7463-01,TCGA-77-7465-01,TCGA-77-8007-01,TCGA-77-8008-01,TCGA-77-8009-01,TCGA-77-8128-01,TCGA-77-8130-01,TCGA-77-8131-01,TCGA-77-8133-01,TCGA-77-8136-01,TCGA-77-8138-01,TCGA-77-8139-01,TCGA-77-8140-01,TCGA-77-8143-01,TCGA-77-8144-01,TCGA-77-8145-01,TCGA-77-8148-01,TCGA-77-8150-01,TCGA-77-8154-01,TCGA-77-8156-01,TCGA-79-5596-01,TCGA-85-6798-01,TCGA-85-7696-01,TCGA-85-7697-01,TCGA-85-7698-01,TCGA-85-7699-01,TCGA-85-7710-01,TCGA-85-7843-01,TCGA-85-7844-01,TCGA-85-7950-01,TCGA-85-8048-01,TCGA-85-8049-01,TCGA-85-8052-01,TCGA-85-8070-01,TCGA-85-8071-01,TCGA-85-8072-01,TCGA-85-8276-01,TCGA-85-8277-01,TCGA-85-8287-01,TCGA-85-8288-01,TCGA-85-8350-01,TCGA-85-8351-01,TCGA-85-8353-01,TCGA-85-8355-01,TCGA-90-6837-01,TCGA-90-7766-01,TCGA-90-7767-01,TCGA-90-7769-01,TCGA-90-7964-01,TCGA-92-7340-01,TCGA-92-7341-01,TCGA-92-8063-01,TCGA-92-8064-01,TCGA-92-8065-01,TCGA-94-7033-01,TCGA-94-7557-01,TCGA-94-7943-01,TCGA-94-8035-01,TCGA-96-7544-01,TCGA-96-7545-01,TCGA-96-8169-01,TCGA-96-8170-01,TCGA-98-7454-01,TCGA-98-8020-01,TCGA-98-8021-01,TCGA-98-8022-01,TCGA-98-8023-01
ov_tcga | TCGA-13-0791-02,TCGA-29-1704-02,TCGA-61-1916-02,TCGA-61-2095-02,TCGA-61-2610-02,TCGA-61-2611-02
prad_broad | Entrez_Gene_Id   ,PR-1701,PR-1783,PR-2525,PR-2621,PR-2741,PR-2832,PR-3027,PR-3042,PR-3043,PR-0508,PR-0581
prad_broad_2013 | PR-01-28-Normal,PR-01-28,PR-02-1431-Normal,PR-03-1426-Normal,PR-03-1426,PR-03-2345-Normal,PR-03-2345,PR-03-728-Normal,PR-04-1084-Normal,PR-04-1084,PR-04-1243-Normal,PR-05-1657-Normal,PR-05-1657,PR-05-2709-Normal,PR-05-2709,PR-05-3595-Normal,PR-05-3852-Normal,PR-05-3852,PR-06-1749-Normal,PR-07-144-Normal,PR-07-144,PR-07-360-Normal,PR-07-837-Normal,PR-07-837,PR-09-146-Normal
prad_mskcc | PAN0095,PAN0107,PAN0109,PAN0110,PAN0112,PAN0113,PAN0114,PAN0115,PAN0117,PAN0120,PAN0122,PAN0125,PAN0127,PAN0128,PAN0129,PAN0134,PAN0135,PAN0136,PAN0144,PAN0147,PAN0151,PAN0157,PAN0162,PAN0164,PAN0167,PAN0169,PAN0171,PAN0172,PAN0174,LAPC14-5748,LAPC14-5749,LAPC17,LAPC23,LAPC25,LAPC4-1T
sarc_mskcc | NF115,NF117,NF119,NF180,NF225,NF84,NF90,NF92,NF95
sclc_cancercell_gardner_2017 | SCRX-Lu149-R,SCRX-Lu149,JHU-LX48-R,JHU-LX48,JHU-LX33-R,JHU-LX33,JHU-LX22-R,JHU-LX22,JHU-LX110-R,JHU-LX110,JHU-LX108-R,JHU-LX108,JHU-LX102-R,JHU-LX102,JHU-LX101-R,JHU-LX101,MSK-LX95-R,MSK-LX95,MSK-LX40-R,MSK-LX40
skcm_tcga | TCGA-D9-A4Z6-01
stad_tcga_pub | TCGA-B7-A5TI-01,TCGA-B7-A5TJ-01,TCGA-B7-A5TK-01,TCGA-B7-A5TN-01,TCGA-BR-6709-01,TCGA-BR-7704-01,TCGA-BR-8060-01,TCGA-CD-8533-01,TCGA-CG-4460-01,TCGA-CG-5716-01,TCGA-CG-5725-01,TCGA-D7-A6ET-01,TCGA-D7-A6EV-01,TCGA-D7-A6EX-01,TCGA-D7-A6EY-01,TCGA-D7-A6EZ-01,TCGA-D7-A6F0-01,TCGA-D7-A6F2-01,TCGA-D7-A747-01,TCGA-D7-A748-01,TCGA-D7-A74A-01,TCGA-D7-A74B-01,TCGA-F1-A72C-01,TCGA-FP-A8CX-01,TCGA-HF-7131-01,TCGA-HF-7134-01,TCGA-HF-A5NB-01,TCGA-HU-8238-01,TCGA-HU-8244-01,TCGA-HU-A4GJ-01,TCGA-HU-A4HB-01,TCGA-IN-A6RI-01,TCGA-IN-A6RJ-01,TCGA-IN-A6RL-01,TCGA-IN-A6RN-01,TCGA-IN-A6RO-01,TCGA-IN-A6RP-01,TCGA-IN-A6RR-01,TCGA-IN-A6RS-01,TCGA-IN-A7NR-01,TCGA-IN-A7NT-01,TCGA-IN-A7NU-01,TCGA-KB-A6F5-01,TCGA-KB-A6F7-01,TCGA-MX-A5UG-01,TCGA-MX-A5UJ-01,TCGA-MX-A663-01,TCGA-MX-A666-01,TCGA-R5-A7O7-01,TCGA-R5-A7ZE-01,TCGA-R5-A7ZF-01,TCGA-R5-A7ZI-01,TCGA-R5-A7ZR-01,TCGA-R5-A804-01,TCGA-R5-A805-01,TCGA-RD-A7BS-01,TCGA-RD-A7BT-01,TCGA-RD-A7BW-01,TCGA-RD-A7C1-01,TCGA-RD-A8MV-01,TCGA-RD-A8MW-01,TCGA-RD-A8N0-01,TCGA-RD-A8N1-01,TCGA-RD-A8N2-01,TCGA-RD-A8N4-01,TCGA-RD-A8N5-01,TCGA-RD-A8N6-01,TCGA-SW-A7EA-01,TCGA-SW-A7EB-01,TCGA-VQ-A8DL-01,TCGA-VQ-A8DT-01,TCGA-VQ-A8DU-01,TCGA-VQ-A8DV-01,TCGA-VQ-A8P2-01,TCGA-VQ-A8P3-01,TCGA-ZA-A8F6-01
thym_tcga | TCGA-XM-AAZ2-12,TCGA-XM-AAZ3-12
utuc_mskcc_2013 | DS-uttcc-079-P




```sql
select cas.cancer_study_identifier, group_concat(s.stable_id) as sample_ids
from sample s
join patient p on s.patient_id=p.internal_id
join cancer_study cas on cas.cancer_study_id=p.cancer_study_id
where s.internal_id not in (
 select cs.internal_id
 from clinical_sample cs
)
group by cancer_study_identifier;
```

**Comment by jjgao** [comment]
@pieterlukasse is it possible to have the validate to check if we are missing oncotree codes or using wrong ones?

**Comment by pieterlukasse** [comment]
@jjgao yes, a field like  `ONCOTREE_CODE` could be validated against the list of cancer types. The list is built up here https://github.com/cBioPortal/cbioportal/blob/master/core/src/main/scripts/importer/validateData.py#L3795. There could be a validation rule that gives an error if `ONCOTREE_CODE` is not found in the list of cancer types.
