### ISSUE TITLE
Aggarwal et al., Small Cell Neuroendocrine Prostate Cancer, JCO 2018

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/datahub#265]
http://ascopubs.org/doi/suppl/10.1200/JCO.2017.77.6880

The supplemental tables have mutation data (contains copy-number calls, which have to be pulled out and converted) and expression levels.

**Comment by schultzn** [comment]
Clinical data seems to be missing - will try to get that.

**Comment by rmadupuri** [comment]
Clinical data was recently added to GitHub (Shared by the author - Rahul Aggarwal) https://github.com/DavidQuigley/WCDT/blob/master/clinical_metadata/2021_03_24_JCO_2018.txt

The data here is available for only 101 patients. Emailed for more clarification.
