### ISSUE TITLE
LUSC study 

### ISSUE THREAD

**Issue by zwiesler** [cBioPortal/datahub#27]
http://www.cbioportal.org/study?id=lusc_tcga_pub#clinical

If you download the tarball you will see SAMPLE_ID and PATIENT_ID in data_clinical.txt are LUSC-XX-XXXX, but Tumor_Sample_Barcode is TCGA-XX-XXXX in data_mutations_extended.txt. The above url has empty columns for clinical data.

**Comment by ritikakundra** [comment]
Fixed it. Will be pushing it to public portal tonight
