### ISSUE TITLE
incorrect clinical annotation

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#272]
@khzhu commented on [Fri Jul 20 2018](https://github.com/cBioPortal/cbioportal/issues/4492)

the patient TCGA-BW-A5NP is from Liver Hepatocellular Carcinoma (TCGA, Provisional) study
> Dear Sir or Madam,
We are using TCGA data for hepatocellular carcinoma from cBioportal. We noticed something seems strange regarding patient clinical data.
For patient TCGA-BW-A5NP, the overall survival is 0 while the disease free survival is about 3.5 months.  Is there something we misunderstand?
Thank you.
Jingjing

**Comment by schultzn** [comment]
@n1zea144 Can you take a look at your code and see what possibly happened? Should this be NA instead of 0 for overall survival time?
