### ISSUE TITLE
Study archive download stalls

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#273]
@guv commented on [Wed Jul 25 2018](https://github.com/cBioPortal/cbioportal/issues/4513)

I tried to download the study archive for `hnsc_tcga_pan_can_atlas_2018` from the [download link](http://download.cbioportal.org/hnsc_tcga_pan_can_atlas_2018.tar.gz).
After 109/140 MB the download stalls and does not continue again.

---

@jjgao commented on [Wed Jul 25 2018](https://github.com/cBioPortal/cbioportal/issues/4513#issuecomment-407897561)

@guv thanks for the contacting us. Is it a one-time glitch or are you experiencing this constantly?

---

@jjgao commented on [Wed Jul 25 2018](https://github.com/cBioPortal/cbioportal/issues/4513#issuecomment-407897779)

Actually I am closing this and please contact cbioportal@googlegroups.com if the problem persists.

---

@guv commented on [Thu Jul 26 2018](https://github.com/cBioPortal/cbioportal/issues/4513#issuecomment-408017911)

@jjgao Yes, this is reproducible for larger downloads (>100MB). Though, the time when it happens (measured in completion percentage) varies.
It is reproducible in browsers (Firefox, Chrome) and Java programs (e.g. NIO `Files.copy`).
Additionally, the download speed varies strongly during the download (50 KB/s to 1.5 MB/s, tested from University network with enough bandwidth).

---

@jjgao commented on [Thu Jul 26 2018](https://github.com/cBioPortal/cbioportal/issues/4513#issuecomment-408101667)

@guv thanks, I can reproduce it now. We will look into this.

**Comment by jjgao** [comment]
@n1zea144 @yichaoS I could reproduce it twice when downloading the same file above. Once stalled around 114mb and another 77MB. Would you please verify and investigate? We may need Joanne's help.

**Comment by ritikakundra** [comment]
This works now from the study page
