### ISSUE TITLE
CCLE data mistake?

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#275]
@pieterlukasse commented on [Thu Jun 23 2016](https://github.com/cBioPortal/cbioportal/issues/1406)

The public study loaded at 
http://www.cbioportal.org/study?id=cellline_ccle_broad#summary

seems to have a mistake in the clinical attribute data. 
![image](https://cloud.githubusercontent.com/assets/2900303/16302960/3ca0a126-394e-11e6-826b-cc0c077df988.png)

The values in "Tumor type" seem to be switched with "Cancer type". 

@schultzn, @jjgao  : what do you think? Adding the values in "Tumor type" to "Cancer type" would also yield a more useful pan-cancer histogram for this pan-cancer study. 

---

@pieterlukasse commented on [Fri Jul 01 2016](https://github.com/cBioPortal/cbioportal/issues/1406#issuecomment-229941626)

@zheins @n1zea144 could you check this one please?

**Comment by jjgao** [comment]
We should curate the oncotree_code for each cell line. Ideally we should also update the ccle data to the latest one.

**Comment by yichaoS** [comment]
@jjgao @ritikakundra The values under `tumor type` still seems to be more like a `cancer type`, and the original values for `tumor type` is missing. Should rename `tumor type` and restore the original values? Oncotree code is added to all as `mixed`.

**Comment by sbabyanusha** [comment]
Added correct oncotree codes to the samples, but some of the samples are still missing `tumor type` values and the oncotree codes for the missing tumor type values are still left as `MIXED`.
