### ISSUE TITLE
cellline_ccle_broad study: Error in file data_mRNA_median_Zscores.txt

### ISSUE THREAD

**Issue by priti88** [cBioPortal/datahub#286]
Gene TTL if occurs twice in the file with different expression values.

User reported:
https://groups.google.com/forum/#!topic/cbioportal/2ar1ne0uvzA

**Comment by yichaoS** [comment]
@priti88 Among the duplicates, we removed the second entry.  The data would be updated in portal and for download tomorrow.

**Comment by yichaoS** [comment]
@priti88 @ritikakundra  The data is updated now. We removed the second duplicate entry and now the data is in sync with what's shown in the portal.
