### ISSUE TITLE
Quigley et al, Cell 2018. Genomic Hallmarks and Structural Variation in Metastatic Prostate Cancer.

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#289]
Paper: https://www.ncbi.nlm.nih.gov/pubmed/30033370

- [ ] [create a issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [ ] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [ ] Document the curation process, e.g. how and by whom the data was transformed
- [ ] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [ ] Create a pull request to datahub once the data is curated
- [ ] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

**Comment by ritikakundra** [comment]
Liftover for the MAF will be required. This is hg38 build.

**Comment by jjgao** [comment]
@ritikakundra could you reply to the email and ask them if they have hg19 mutation data?

**Comment by rmadupuri** [comment]
Treatment related clinical attributes are found here: https://github.com/DavidQuigley/WCDT/blob/master/clinical_metadata/2021_03_24_cell_2018.txt. 

Data source shared by the co-author (Rahul Aggarwal) when contacted for another study https://github.com/cBioPortal/datahub/issues/265. Looks like the patients in this study are a subset of the Aggarwal et al. JCO 2018 study (datahub issue 265). We are still waiting on the complete patient list for issue 265.
