### ISSUE TITLE
Landau et al., Chronic Lymphocytic Leukemia, Nature 2015

### ISSUE THREAD

**Issue by rmadupuri** [cBioPortal/datahub#292]
Please keep this checklist for curation of a new study.

- [x] [create a issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [x] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [ ] Document the curation process, e.g. how and by whom the data was transformed
- [x] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [ ] Create a pull request to datahub once the data is curated
- [ ] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

**Comment by rmadupuri** [comment]
Study identifier: cll_broad_2015
PMID: 26466571

- [ ] Does study name and study ID follow our convention? e.g. Tumor_Type (Institue, Journal Year); brca_mskcc_2015   
- [ ] Is study meta data complete? e.g. pmid, group of PUBLIC
- [ ] Were all samples profiled with WES/WGS? If not, is gene panel file curated?
- [ ] Are oncotree codes of all samples curated; Cancer Type and Cancer Type Detailed needs to be added in addition to Oncotree Code
- [ ] Clinical sample and patient data with meta files
- [ ] Mutations data with meta files
- [ ] MAF is based on hg19
- [ ] MAF with 2 isoforms: uniprot and mskcc
- [ ] CNA data with meta files **(NA)**
- [ ] CNA segment data with meta files **(NA)**
- [ ] Expression data including z-scores with meta files **(NA)**
- [ ] Case-lists for all profiles.
- [ ] Passes Validation
- [ ] Manual checking (Niki or JJ): Triage Portal

**Comment by jjgao** [comment]
someone asked for this study: https://groups.google.com/forum/#!msg/cbioportal/z7I5R6mLCys/vwvxIJjtDAAJ. Please update the thread once the study is released.
