### ISSUE TITLE
caselists -> case_lists

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/datahub#305]
https://github.com/cBioPortal/datahub/tree/master/public/brca_mbcproject_wagle_2017

The dir `caselists` should be named `case_lists`. I found it in `brca_mbcproject_wagle_2017` but perhaps there are other studies which have the same format error.

When I have time I'll add additional validations for case lists, such as the _sequenced must be present when there's mutation data.

**Comment by yichaoS** [comment]
Solved in https://github.com/cBioPortal/datahub/pull/263
