### ISSUE TITLE
two mutation profiles in egc_msk_2017

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#307]
@ritikakundra just to keep track. Let's either remove the `uncalled` profile or merge it to the main mutaiton profile soon.

![image](https://user-images.githubusercontent.com/840895/44109119-393197c2-9fca-11e8-8e8f-f403ee6ae0cd.png)

**Comment by yichaoS** [comment]
@ritika I saw them imported to public and msk. closing the issue now.
