### ISSUE TITLE
samples with mutations but not in sequenced case list

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#308]
There are samples with mutations but are not included in the sequenced case list.

Here is the SQL:

``` sql
select distinct sample_id, s.stable_id, cs.cancer_study_identifier
from mutation m, sample s, patient p, cancer_study cs
where m.sample_id=s.internal_id
  and s.patient_id=p.internal_id
  and p.cancer_study_id=cs.cancer_study_id
  and s.internal_id not in (
    select ll.sample_id
    from sample_list l, sample_list_list ll
    where l.list_id=ll.list_id
    and l.stable_id like "%_sequenced"
  );
```

updated list (8/14/2018)

9 studies:
```
all_phase2_target_2018_pub
aml_target_2018_pub
brca_tcga
kirc_tcga_pub
luad_tsp
lusc_tcga_pub
nhl_bcgsc_2013
prad_mskcc
stad_tcga
```

sample_id | stable_id | cancer_study_identifier
-- | -- | --
531806 | TARGET-10-PANCVR-03 | all_phase2_target_2018_pub
531815 | TARGET-10-PANDWE-03 | all_phase2_target_2018_pub
531820 | TARGET-10-PANGIF-09 | all_phase2_target_2018_pub
531822 | TARGET-10-PANIEU-09 | all_phase2_target_2018_pub
531823 | TARGET-10-PANJWJ-09 | all_phase2_target_2018_pub
531825 | TARGET-10-PANKAK-09 | all_phase2_target_2018_pub
531832 | TARGET-10-PANSBR-09 | all_phase2_target_2018_pub
531834 | TARGET-10-PANSDA-09 | all_phase2_target_2018_pub
531836 | TARGET-10-PANSHK-09 | all_phase2_target_2018_pub
531837 | TARGET-10-PANSPW-09 | all_phase2_target_2018_pub
531838 | TARGET-10-PANSUL-09 | all_phase2_target_2018_pub
531839 | TARGET-10-PANTSM-03 | all_phase2_target_2018_pub
531842 | TARGET-10-PANUHA-09 | all_phase2_target_2018_pub
531855 | TARGET-10-PANWHJ-09 | all_phase2_target_2018_pub
531856 | TARGET-10-PANWYH-09 | all_phase2_target_2018_pub
531858 | TARGET-10-PANXPE-03 | all_phase2_target_2018_pub
531863 | TARGET-10-PANYGB-09 | all_phase2_target_2018_pub
531864 | TARGET-10-PANYYV-03 | all_phase2_target_2018_pub
531866 | TARGET-10-PANYZE-09 | all_phase2_target_2018_pub
531872 | TARGET-10-PANZPJ-09 | all_phase2_target_2018_pub
531876 | TARGET-10-PAPACP-03 | all_phase2_target_2018_pub
531879 | TARGET-10-PAPAGK-03 | all_phase2_target_2018_pub
531881 | TARGET-10-PAPAGK-09 | all_phase2_target_2018_pub
531882 | TARGET-10-PAPAIZ-09 | all_phase2_target_2018_pub
531888 | TARGET-10-PAPCUR-09 | all_phase2_target_2018_pub
531892 | TARGET-10-PAPCVZ-09 | all_phase2_target_2018_pub
531896 | TARGET-10-PAPDJM-09 | all_phase2_target_2018_pub
531898 | TARGET-10-PAPDKJ-09 | all_phase2_target_2018_pub
531899 | TARGET-10-PAPDUF-09 | all_phase2_target_2018_pub
531901 | TARGET-10-PAPDUV-09 | all_phase2_target_2018_pub
531903 | TARGET-10-PAPDWT-09 | all_phase2_target_2018_pub
531908 | TARGET-10-PAPECF-09 | all_phase2_target_2018_pub
531909 | TARGET-10-PAPEFH-03 | all_phase2_target_2018_pub
531915 | TARGET-10-PAPEJN-09 | all_phase2_target_2018_pub
531921 | TARGET-10-PAPFWH-09 | all_phase2_target_2018_pub
531923 | TARGET-10-PAPGFP-09 | all_phase2_target_2018_pub
531925 | TARGET-10-PAPGYC-09 | all_phase2_target_2018_pub
531927 | TARGET-10-PAPHEK-03 | all_phase2_target_2018_pub
531930 | TARGET-10-PAPHJF-09 | all_phase2_target_2018_pub
531931 | TARGET-10-PAPHMH-09 | all_phase2_target_2018_pub
531937 | TARGET-10-PAPIJB-09 | all_phase2_target_2018_pub
531939 | TARGET-10-PAPIRZ-09 | all_phase2_target_2018_pub
531940 | TARGET-10-PAPISG-03 | all_phase2_target_2018_pub
531944 | TARGET-10-PAPJHB-09 | all_phase2_target_2018_pub
531946 | TARGET-10-PAPJHR-09 | all_phase2_target_2018_pub
531947 | TARGET-10-PAPJIB-03 | all_phase2_target_2018_pub
531949 | TARGET-10-PAPJIB-09 | all_phase2_target_2018_pub
531956 | TARGET-10-PAPKNC-09 | all_phase2_target_2018_pub
531957 | TARGET-10-PAPLDL-03 | all_phase2_target_2018_pub
531959 | TARGET-10-PAPLDL-09 | all_phase2_target_2018_pub
531961 | TARGET-10-PAPLDM-09 | all_phase2_target_2018_pub
531965 | TARGET-10-PAPLUG-09 | all_phase2_target_2018_pub
531969 | TARGET-10-PAPMVB-09 | all_phase2_target_2018_pub
531970 | TARGET-10-PAPMYD-03 | all_phase2_target_2018_pub
531972 | TARGET-10-PAPNFY-03 | all_phase2_target_2018_pub
531976 | TARGET-10-PAPNMY-09 | all_phase2_target_2018_pub
531978 | TARGET-10-PAPNNX-03 | all_phase2_target_2018_pub
531983 | TARGET-10-PAPPGN-03 | all_phase2_target_2018_pub
531989 | TARGET-10-PAPRCS-09 | all_phase2_target_2018_pub
531990 | TARGET-10-PAPRFE-09 | all_phase2_target_2018_pub
531993 | TARGET-10-PAPSPG-03 | all_phase2_target_2018_pub
531996 | TARGET-10-PAPSPN-03 | all_phase2_target_2018_pub
531998 | TARGET-10-PAPSPN-09 | all_phase2_target_2018_pub
532003 | TARGET-10-PAPTLM-09 | all_phase2_target_2018_pub
532007 | TARGET-10-PAPVTA-09 | all_phase2_target_2018_pub
532013 | TARGET-10-PAPZNK-03 | all_phase2_target_2018_pub
532015 | TARGET-10-PAPZNK-09 | all_phase2_target_2018_pub
532017 | TARGET-10-PAPZST-09 | all_phase2_target_2018_pub
532019 | TARGET-10-PARACA-09 | all_phase2_target_2018_pub
532020 | TARGET-10-PARAKF-03 | all_phase2_target_2018_pub
532022 | TARGET-10-PARAKF-09 | all_phase2_target_2018_pub
532024 | TARGET-10-PARARJ-09 | all_phase2_target_2018_pub
532027 | TARGET-10-PARBRK-03 | all_phase2_target_2018_pub
532029 | TARGET-10-PARBRK-09 | all_phase2_target_2018_pub
532031 | TARGET-10-PARBVI-09 | all_phase2_target_2018_pub
532034 | TARGET-10-PARCHB-03 | all_phase2_target_2018_pub
532038 | TARGET-10-PARDWE-03 | all_phase2_target_2018_pub
532042 | TARGET-10-PARFLV-09 | all_phase2_target_2018_pub
532043 | TARGET-10-PARFTR-03 | all_phase2_target_2018_pub
532045 | TARGET-10-PARFTR-09 | all_phase2_target_2018_pub
532048 | TARGET-10-PARGFV-03 | all_phase2_target_2018_pub
532051 | TARGET-10-PARGHW-03 | all_phase2_target_2018_pub
532053 | TARGET-10-PARGHW-09 | all_phase2_target_2018_pub
532054 | TARGET-10-PARGML-03 | all_phase2_target_2018_pub
532057 | TARGET-10-PARGVZ-03 | all_phase2_target_2018_pub
532061 | TARGET-10-PARIAD-03 | all_phase2_target_2018_pub
532065 | TARGET-10-PARJSR-09 | all_phase2_target_2018_pub
532066 | TARGET-10-PARJZZ-03 | all_phase2_target_2018_pub
532068 | TARGET-10-PARJZZ-09 | all_phase2_target_2018_pub
532071 | TARGET-10-PARLAF-09 | all_phase2_target_2018_pub
532072 | TARGET-10-PARLEK-03 | all_phase2_target_2018_pub
532078 | TARGET-10-PARMSP-09 | all_phase2_target_2018_pub
532081 | TARGET-10-PARMXF-09 | all_phase2_target_2018_pub
532084 | TARGET-10-PARNMF-03 | all_phase2_target_2018_pub
532088 | TARGET-10-PARNSH-03 | all_phase2_target_2018_pub
532093 | TARGET-10-PARPNM-03 | all_phase2_target_2018_pub
532095 | TARGET-10-PARPNM-09 | all_phase2_target_2018_pub
532097 | TARGET-10-PARPRW-03 | all_phase2_target_2018_pub
532099 | TARGET-10-PARPRW-09 | all_phase2_target_2018_pub
532103 | TARGET-10-PARPZJ-03 | all_phase2_target_2018_pub
532108 | TARGET-10-PARSGC-03 | all_phase2_target_2018_pub
532111 | TARGET-10-PARSZH-09 | all_phase2_target_2018_pub
532115 | TARGET-10-PARTKL-09 | all_phase2_target_2018_pub
532124 | TARGET-10-PARUGP-09 | all_phase2_target_2018_pub
532127 | TARGET-10-PARVWD-09 | all_phase2_target_2018_pub
532132 | TARGET-10-PARXMC-09 | all_phase2_target_2018_pub
532133 | TARGET-10-PASCIU-03 | all_phase2_target_2018_pub
532135 | TARGET-10-PASDYK-09 | all_phase2_target_2018_pub
532137 | TARGET-10-PASEVJ-09 | all_phase2_target_2018_pub
532140 | TARGET-10-PASFXA-03 | all_phase2_target_2018_pub
532144 | TARGET-10-PASHUI-09 | all_phase2_target_2018_pub
532145 | TARGET-10-PASKAY-03 | all_phase2_target_2018_pub
532148 | TARGET-10-PASKHT-03 | all_phase2_target_2018_pub
532150 | TARGET-10-PASLZM-03 | all_phase2_target_2018_pub
532162 | TARGET-10-PASUBW-09 | all_phase2_target_2018_pub
532165 | TARGET-10-PASYGM-03 | all_phase2_target_2018_pub
532175 | TARGET-10-PATTEE-03 | all_phase2_target_2018_pub
533206 | TARGET-10-PAKSWW-03 | all_phase2_target_2018_pub
533208 | TARGET-10-PAKSWW-09 | all_phase2_target_2018_pub
533151 | TARGET-10-PANFNZ-09 | all_phase2_target_2018_pub
533153 | TARGET-10-PANKDT-09 | all_phase2_target_2018_pub
533155 | TARGET-10-PANJPG-03 | all_phase2_target_2018_pub
533156 | TARGET-10-PANKGK-09 | all_phase2_target_2018_pub
533157 | TARGET-10-PANPJI-09 | all_phase2_target_2018_pub
533159 | TARGET-10-PANRDC-03 | all_phase2_target_2018_pub
533160 | TARGET-10-PANRWG-09 | all_phase2_target_2018_pub
533161 | TARGET-10-PANUUF-09 | all_phase2_target_2018_pub
533163 | TARGET-10-PANZXZ-09 | all_phase2_target_2018_pub
533166 | TARGET-10-PAPIGX-03 | all_phase2_target_2018_pub
533169 | TARGET-10-PAMXHJ-09 | all_phase2_target_2018_pub
533170 | TARGET-10-PANEUH-09 | all_phase2_target_2018_pub
533172 | TARGET-10-PANXDB-03 | all_phase2_target_2018_pub
533173 | TARGET-10-PANXDR-09 | all_phase2_target_2018_pub
533174 | TARGET-10-PAPHGD-09 | all_phase2_target_2018_pub
533176 | TARGET-10-PANWHW-03 | all_phase2_target_2018_pub
533194 | TARGET-10-PAMXSP-09 | all_phase2_target_2018_pub
533195 | TARGET-10-PANKRG-03 | all_phase2_target_2018_pub
533196 | TARGET-10-PANRYM-09 | all_phase2_target_2018_pub
533197 | TARGET-10-PANSIA-09 | all_phase2_target_2018_pub
533199 | TARGET-10-PANSXG-03 | all_phase2_target_2018_pub
533201 | TARGET-10-PANWVW-09 | all_phase2_target_2018_pub
533202 | TARGET-10-PANYEJ-09 | all_phase2_target_2018_pub
533203 | TARGET-10-PAPBES-03 | all_phase2_target_2018_pub
533204 | TARGET-10-PAPBFN-09 | all_phase2_target_2018_pub
533205 | TARGET-10-PAPIJM-09 | all_phase2_target_2018_pub
533209 | TARGET-10-PANKMB-09 | all_phase2_target_2018_pub
533210 | TARGET-10-PANLIC-09 | all_phase2_target_2018_pub
533212 | TARGET-10-PAPBZK-03 | all_phase2_target_2018_pub
533213 | TARGET-10-PAPEWB-09 | all_phase2_target_2018_pub
528002 | TARGET-20-PABLDZ-09 | aml_target_2018_pub
528006 | TARGET-20-PADZCG-09 | aml_target_2018_pub
528010 | TARGET-20-PAEAKL-09 | aml_target_2018_pub
528013 | TARGET-20-PAECCE-09 | aml_target_2018_pub
528018 | TARGET-20-PAEERJ-09 | aml_target_2018_pub
528019 | TARGET-20-PAEEYP-09 | aml_target_2018_pub
528020 | TARGET-20-PAEFGR-09 | aml_target_2018_pub
528022 | TARGET-20-PAEFGT-09 | aml_target_2018_pub
528029 | TARGET-20-PAERAH-09 | aml_target_2018_pub
528032 | TARGET-20-PAKERZ-09 | aml_target_2018_pub
528037 | TARGET-20-PAKIWK-09 | aml_target_2018_pub
528038 | TARGET-20-PAKIYW-09 | aml_target_2018_pub
528040 | TARGET-20-PAKKBK-09 | aml_target_2018_pub
528045 | TARGET-20-PAKSMZ-03 | aml_target_2018_pub
528047 | TARGET-20-PAKTCX-09 | aml_target_2018_pub
528048 | TARGET-20-PAKVGI-09 | aml_target_2018_pub
528052 | TARGET-20-PALGKX-09 | aml_target_2018_pub
528053 | TARGET-20-PAMVKZ-09 | aml_target_2018_pub
528056 | TARGET-20-PAMYAS-09 | aml_target_2018_pub
528057 | TARGET-20-PAMYGX-09 | aml_target_2018_pub
528060 | TARGET-20-PANAEV-09 | aml_target_2018_pub
528063 | TARGET-20-PANBZH-09 | aml_target_2018_pub
528065 | TARGET-20-PANCSC-09 | aml_target_2018_pub
528067 | TARGET-20-PANDER-09 | aml_target_2018_pub
528068 | TARGET-20-PANDIX-09 | aml_target_2018_pub
528069 | TARGET-20-PANFMG-09 | aml_target_2018_pub
528071 | TARGET-20-PANGDN-09 | aml_target_2018_pub
528073 | TARGET-20-PANGJY-09 | aml_target_2018_pub
528074 | TARGET-20-PANGTF-09 | aml_target_2018_pub
528076 | TARGET-20-PANHYK-09 | aml_target_2018_pub
528078 | TARGET-20-PANINI-09 | aml_target_2018_pub
528079 | TARGET-20-PANJGR-09 | aml_target_2018_pub
528081 | TARGET-20-PANKFG-09 | aml_target_2018_pub
528082 | TARGET-20-PANKFZ-09 | aml_target_2018_pub
528083 | TARGET-20-PANKKE-09 | aml_target_2018_pub
528084 | TARGET-20-PANKNB-09 | aml_target_2018_pub
528085 | TARGET-20-PANLIR-09 | aml_target_2018_pub
528087 | TARGET-20-PANLIZ-09 | aml_target_2018_pub
528090 | TARGET-20-PANLKB-09 | aml_target_2018_pub
528091 | TARGET-20-PANLLX-09 | aml_target_2018_pub
528092 | TARGET-20-PANLRE-09 | aml_target_2018_pub
528094 | TARGET-20-PANLXM-09 | aml_target_2018_pub
528097 | TARGET-20-PANNHB-09 | aml_target_2018_pub
528098 | TARGET-20-PANNJI-09 | aml_target_2018_pub
528099 | TARGET-20-PANPKN-09 | aml_target_2018_pub
528100 | TARGET-20-PANPLS-03 | aml_target_2018_pub
528106 | TARGET-20-PANSBH-09 | aml_target_2018_pub
528107 | TARGET-20-PANSJB-09 | aml_target_2018_pub
528109 | TARGET-20-PANTPW-09 | aml_target_2018_pub
528113 | TARGET-20-PANUTB-09 | aml_target_2018_pub
528114 | TARGET-20-PANUUA-09 | aml_target_2018_pub
528116 | TARGET-20-PANVGE-09 | aml_target_2018_pub
528118 | TARGET-20-PANVGP-09 | aml_target_2018_pub
528123 | TARGET-20-PANYGP-09 | aml_target_2018_pub
528124 | TARGET-20-PANYNR-09 | aml_target_2018_pub
528127 | TARGET-20-PANZKA-09 | aml_target_2018_pub
528128 | TARGET-20-PANZWB-09 | aml_target_2018_pub
528130 | TARGET-20-PAPAWN-09 | aml_target_2018_pub
528131 | TARGET-20-PAPBEJ-09 | aml_target_2018_pub
528132 | TARGET-20-PAPVCN-09 | aml_target_2018_pub
528133 | TARGET-20-PAPVDV-09 | aml_target_2018_pub
528136 | TARGET-20-PAPVZK-09 | aml_target_2018_pub
528137 | TARGET-20-PAPWHS-09 | aml_target_2018_pub
528139 | TARGET-20-PAPWYK-09 | aml_target_2018_pub
528141 | TARGET-20-PAPXRJ-09 | aml_target_2018_pub
528142 | TARGET-20-PAPXWI-09 | aml_target_2018_pub
528147 | TARGET-20-PARAJX-09 | aml_target_2018_pub
528149 | TARGET-20-PARASV-03 | aml_target_2018_pub
528150 | TARGET-20-PARBFJ-09 | aml_target_2018_pub
528153 | TARGET-20-PARBIU-09 | aml_target_2018_pub
528155 | TARGET-20-PARBRA-09 | aml_target_2018_pub
528158 | TARGET-20-PARBXE-09 | aml_target_2018_pub
528159 | TARGET-20-PARCCH-03 | aml_target_2018_pub
528163 | TARGET-20-PARCUK-09 | aml_target_2018_pub
528169 | TARGET-20-PARCZL-09 | aml_target_2018_pub
528171 | TARGET-20-PARDDY-09 | aml_target_2018_pub
528173 | TARGET-20-PARDMG-09 | aml_target_2018_pub
528176 | TARGET-20-PARENB-09 | aml_target_2018_pub
528179 | TARGET-20-PARFAL-09 | aml_target_2018_pub
528188 | TARGET-20-PARGVC-03 | aml_target_2018_pub
528194 | TARGET-20-PARHVK-09 | aml_target_2018_pub
528198 | TARGET-20-PARIHK-09 | aml_target_2018_pub
528199 | TARGET-20-PARIMT-09 | aml_target_2018_pub
528201 | TARGET-20-PARIZR-09 | aml_target_2018_pub
528203 | TARGET-20-PARJCR-09 | aml_target_2018_pub
528205 | TARGET-20-PARJYP-03 | aml_target_2018_pub
528207 | TARGET-20-PARKCX-09 | aml_target_2018_pub
528213 | TARGET-20-PARLVL-09 | aml_target_2018_pub
528219 | TARGET-20-PARMZF-09 | aml_target_2018_pub
528224 | TARGET-20-PARPDS-09 | aml_target_2018_pub
528227 | TARGET-20-PARPWL-09 | aml_target_2018_pub
528228 | TARGET-20-PARSAN-09 | aml_target_2018_pub
528229 | TARGET-20-PARSHM-03 | aml_target_2018_pub
528231 | TARGET-20-PARTAL-09 | aml_target_2018_pub
528236 | TARGET-20-PARUBT-09 | aml_target_2018_pub
528241 | TARGET-20-PARUDL-09 | aml_target_2018_pub
528243 | TARGET-20-PARUNX-09 | aml_target_2018_pub
528246 | TARGET-20-PARUTH-09 | aml_target_2018_pub
528247 | TARGET-20-PARUUB-09 | aml_target_2018_pub
528248 | TARGET-20-PARUWX-09 | aml_target_2018_pub
528249 | TARGET-20-PARVAI-09 | aml_target_2018_pub
528250 | TARGET-20-PARVUA-03 | aml_target_2018_pub
528253 | TARGET-20-PARWDZ-09 | aml_target_2018_pub
528255 | TARGET-20-PARWXU-09 | aml_target_2018_pub
528259 | TARGET-20-PARXMP-09 | aml_target_2018_pub
528260 | TARGET-20-PARXNG-09 | aml_target_2018_pub
528264 | TARGET-20-PARYFN-03 | aml_target_2018_pub
528267 | TARGET-20-PARYGA-09 | aml_target_2018_pub
528269 | TARGET-20-PARYVW-09 | aml_target_2018_pub
528272 | TARGET-20-PARZUU-09 | aml_target_2018_pub
528273 | TARGET-20-PARZWH-09 | aml_target_2018_pub
528283 | TARGET-20-PASBHI-09 | aml_target_2018_pub
528284 | TARGET-20-PASBPK-09 | aml_target_2018_pub
528287 | TARGET-20-PASCCS-09 | aml_target_2018_pub
528288 | TARGET-20-PASCFW-09 | aml_target_2018_pub
528290 | TARGET-20-PASCGR-03 | aml_target_2018_pub
528307 | TARGET-20-PASFEW-09 | aml_target_2018_pub
528309 | TARGET-20-PASFJB-09 | aml_target_2018_pub
528311 | TARGET-20-PASFLM-09 | aml_target_2018_pub
528317 | TARGET-20-PASGGK-09 | aml_target_2018_pub
528318 | TARGET-20-PASGMZ-09 | aml_target_2018_pub
528321 | TARGET-20-PASGWH-09 | aml_target_2018_pub
528324 | TARGET-20-PASHBI-09 | aml_target_2018_pub
528328 | TARGET-20-PASHYZ-09 | aml_target_2018_pub
528330 | TARGET-20-PASIBG-09 | aml_target_2018_pub
528340 | TARGET-20-PASJTM-09 | aml_target_2018_pub
528344 | TARGET-20-PASLSD-03 | aml_target_2018_pub
528347 | TARGET-20-PASMGW-09 | aml_target_2018_pub
528348 | TARGET-20-PASMHY-03 | aml_target_2018_pub
528352 | TARGET-20-PASPGA-09 | aml_target_2018_pub
528353 | TARGET-20-PASPKE-09 | aml_target_2018_pub
528355 | TARGET-20-PASPLU-09 | aml_target_2018_pub
528357 | TARGET-20-PASPTM-09 | aml_target_2018_pub
528362 | TARGET-20-PASRTP-09 | aml_target_2018_pub
528363 | TARGET-20-PASSSI-09 | aml_target_2018_pub
528365 | TARGET-20-PASTTW-09 | aml_target_2018_pub
528366 | TARGET-20-PASTUH-03 | aml_target_2018_pub
528370 | TARGET-20-PASVVS-09 | aml_target_2018_pub
528373 | TARGET-20-PASVYL-09 | aml_target_2018_pub
528375 | TARGET-20-PASWAJ-09 | aml_target_2018_pub
528377 | TARGET-20-PASWLN-09 | aml_target_2018_pub
528379 | TARGET-20-PASWPT-09 | aml_target_2018_pub
528384 | TARGET-20-PASXYG-09 | aml_target_2018_pub
528387 | TARGET-20-PASZLJ-09 | aml_target_2018_pub
528391 | TARGET-20-PATAST-09 | aml_target_2018_pub
528392 | TARGET-20-PATDHA-09 | aml_target_2018_pub
528394 | TARGET-20-PATDNN-09 | aml_target_2018_pub
528395 | TARGET-20-PATELT-03 | aml_target_2018_pub
528397 | TARGET-20-PATIAK-09 | aml_target_2018_pub
528398 | TARGET-20-PATJHJ-09 | aml_target_2018_pub
500269 | TCGA-A8-A08C-01 | brca_tcga
342270 | TCGA-A3-3325-01 | kirc_tcga_pub
342319 | TCGA-CW-5590-01 | kirc_tcga_pub
362340 | luad_tsp_16594 | luad_tsp
346789 | TCGA-22-0940-01 | lusc_tcga_pub
346790 | TCGA-33-4589-01 | lusc_tcga_pub
346791 | TCGA-22-4594-01 | lusc_tcga_pub
346792 | TCGA-34-2605-01 | lusc_tcga_pub
346793 | TCGA-33-4579-01 | lusc_tcga_pub
535576 | RG133 | nhl_bcgsc_2013
349482 | DU145 | prad_mskcc
349483 | DU145T | prad_mskcc
349494 | LuCAP35T | prad_mskcc
349744 | LAPC14-5748 | prad_mskcc
349745 | LAPC14-5749 | prad_mskcc
349746 | LAPC17 | prad_mskcc
349747 | LAPC23 | prad_mskcc
349748 | LAPC25 | prad_mskcc
349749 | LAPC4-1T | prad_mskcc
509877 | TCGA-B7-A5TI-01 | stad_tcga
509878 | TCGA-B7-A5TJ-01 | stad_tcga
509879 | TCGA-B7-A5TK-01 | stad_tcga
509880 | TCGA-B7-A5TN-01 | stad_tcga
509673 | TCGA-BR-6709-01 | stad_tcga
509688 | TCGA-BR-7704-01 | stad_tcga
509718 | TCGA-BR-8060-01 | stad_tcga
509724 | TCGA-BR-8285-01 | stad_tcga
509835 | TCGA-BR-A4J5-01 | stad_tcga
509755 | TCGA-CD-8533-01 | stad_tcga
510084 | TCGA-CG-4460-01 | stad_tcga
509656 | TCGA-CG-5716-01 | stad_tcga
510111 | TCGA-CG-5725-01 | stad_tcga
509892 | TCGA-D7-A6ET-01 | stad_tcga
509881 | TCGA-D7-A6EV-01 | stad_tcga
509882 | TCGA-D7-A6EX-01 | stad_tcga
509883 | TCGA-D7-A6EY-01 | stad_tcga
509884 | TCGA-D7-A6EZ-01 | stad_tcga
509885 | TCGA-D7-A6F0-01 | stad_tcga
509886 | TCGA-D7-A6F2-01 | stad_tcga
509902 | TCGA-D7-A747-01 | stad_tcga
509893 | TCGA-D7-A748-01 | stad_tcga
509894 | TCGA-D7-A74A-01 | stad_tcga
509903 | TCGA-D7-A74B-01 | stad_tcga
509904 | TCGA-F1-A72C-01 | stad_tcga
509922 | TCGA-FP-A8CX-01 | stad_tcga
509942 | TCGA-FP-A9TM-01 | stad_tcga
509698 | TCGA-HF-7131-01 | stad_tcga
509701 | TCGA-HF-7134-01 | stad_tcga
509887 | TCGA-HF-A5NB-01 | stad_tcga
509772 | TCGA-HU-8238-01 | stad_tcga
509774 | TCGA-HU-8244-01 | stad_tcga
509861 | TCGA-HU-A4GJ-01 | stad_tcga
509875 | TCGA-HU-A4HB-01 | stad_tcga
509895 | TCGA-IN-A6RI-01 | stad_tcga
509905 | TCGA-IN-A6RJ-01 | stad_tcga
509896 | TCGA-IN-A6RL-01 | stad_tcga
509906 | TCGA-IN-A6RN-01 | stad_tcga
509907 | TCGA-IN-A6RO-01 | stad_tcga
509908 | TCGA-IN-A6RP-01 | stad_tcga
509897 | TCGA-IN-A6RR-01 | stad_tcga
509912 | TCGA-IN-A6RS-01 | stad_tcga
509913 | TCGA-IN-A7NR-01 | stad_tcga
509914 | TCGA-IN-A7NT-01 | stad_tcga
509915 | TCGA-IN-A7NU-01 | stad_tcga
509957 | TCGA-IN-AB1V-01 | stad_tcga
509943 | TCGA-IN-AB1X-01 | stad_tcga
509909 | TCGA-KB-A6F5-01 | stad_tcga
509898 | TCGA-KB-A6F7-01 | stad_tcga
509944 | TCGA-KB-A93G-01 | stad_tcga
509946 | TCGA-KB-A93J-01 | stad_tcga
509888 | TCGA-MX-A5UG-01 | stad_tcga
509889 | TCGA-MX-A5UJ-01 | stad_tcga
509890 | TCGA-MX-A663-01 | stad_tcga
509891 | TCGA-MX-A666-01 | stad_tcga
509910 | TCGA-R5-A7O7-01 | stad_tcga
509916 | TCGA-R5-A7ZE-01 | stad_tcga
509917 | TCGA-R5-A7ZF-01 | stad_tcga
509918 | TCGA-R5-A7ZI-01 | stad_tcga
509919 | TCGA-R5-A7ZR-01 | stad_tcga
509923 | TCGA-R5-A804-01 | stad_tcga
509924 | TCGA-R5-A805-01 | stad_tcga
509899 | TCGA-RD-A7BS-01 | stad_tcga
509911 | TCGA-RD-A7BT-01 | stad_tcga
509900 | TCGA-RD-A7BW-01 | stad_tcga
509901 | TCGA-RD-A7C1-01 | stad_tcga
509925 | TCGA-RD-A8MV-01 | stad_tcga
509926 | TCGA-RD-A8MW-01 | stad_tcga
509927 | TCGA-RD-A8N0-01 | stad_tcga
509928 | TCGA-RD-A8N1-01 | stad_tcga
509929 | TCGA-RD-A8N2-01 | stad_tcga
509930 | TCGA-RD-A8N4-01 | stad_tcga
509931 | TCGA-RD-A8N5-01 | stad_tcga
509932 | TCGA-RD-A8N6-01 | stad_tcga
509947 | TCGA-RD-A8N9-01 | stad_tcga
509920 | TCGA-SW-A7EA-01 | stad_tcga
509921 | TCGA-SW-A7EB-01 | stad_tcga
509933 | TCGA-VQ-A8DL-01 | stad_tcga
509934 | TCGA-VQ-A8DT-01 | stad_tcga
509935 | TCGA-VQ-A8DU-01 | stad_tcga
509936 | TCGA-VQ-A8DV-01 | stad_tcga
509937 | TCGA-VQ-A8DZ-01 | stad_tcga
509938 | TCGA-VQ-A8E2-01 | stad_tcga
509959 | TCGA-VQ-A8E7-01 | stad_tcga
509939 | TCGA-VQ-A8P2-01 | stad_tcga
509940 | TCGA-VQ-A8P3-01 | stad_tcga
509961 | TCGA-VQ-A8PE-01 | stad_tcga
509965 | TCGA-VQ-A8PK-01 | stad_tcga
509966 | TCGA-VQ-A8PM-01 | stad_tcga
509969 | TCGA-VQ-A8PQ-01 | stad_tcga
509981 | TCGA-VQ-A91Q-01 | stad_tcga
509983 | TCGA-VQ-A91U-01 | stad_tcga
509984 | TCGA-VQ-A91V-01 | stad_tcga
509995 | TCGA-VQ-A92D-01 | stad_tcga
509999 | TCGA-VQ-A94T-01 | stad_tcga
510001 | TCGA-VQ-AA64-01 | stad_tcga
510002 | TCGA-VQ-AA68-01 | stad_tcga
510003 | TCGA-VQ-AA69-01 | stad_tcga
510004 | TCGA-VQ-AA6A-01 | stad_tcga
510005 | TCGA-VQ-AA6B-01 | stad_tcga
510007 | TCGA-VQ-AA6F-01 | stad_tcga
510008 | TCGA-VQ-AA6G-01 | stad_tcga
510009 | TCGA-VQ-AA6I-01 | stad_tcga
510010 | TCGA-VQ-AA6J-01 | stad_tcga
510011 | TCGA-VQ-AA6K-01 | stad_tcga
509941 | TCGA-ZA-A8F6-01 | stad_tcga

**Comment by yichaoS** [comment]
@jjgao @ritikakundra 
all cleared/fixed in public DB. In private DB this is the updated list:
accrf_merged_filtered	24
accrf_merged_unfiltered	24
brca_sanger_2016	13
genie_bpc_test	41
grail_mskcc_brca_autopsy	2
ilc_bordet_2016	1016
lcarc_mskcc_rekhtman_2014	18
lihc_tcga_pub	2
lusc_tcga_pub	18
lymph_landscape_fmi_201611	2029
mixed_genie_akt1_analysis	3
mixed_rudinc_cmo_06437_h_468_p1_zp	21
mskimpact_foundation_2019	13354
nhl_bcgsc_2013	2
plmeso_tcga_pub	3385
poetic	32
sclc_mskcc_rekhtman_2014	104
sclc_washu_2018	289
stad_mskcc_2016	2
stad_tcga	23924
thca_mskcc_faginj_2014	2
tnbc_shahlab_2019	2317

**Comment by yichaoS** [comment]
@jjgao For every new study we add, we'll re-generate the case lists. So I think it is unlikely this would happen again. But I added this item to the validator improvement list here: https://github.com/cBioPortal/datahub/issues/1062 anyways. It is good to have.

**Comment by ritikakundra** [comment]
Am closing this cos a lot of the private studies are not live or have been pushed to public.
