### ISSUE TITLE
Need to liftover public studies with hg18 segment files

### ISSUE THREAD

**Issue by yichaoS** [cBioPortal/datahub#309]
to be lift over to hg 19

- [x] cellline_nci60
- [x] prad_mich
- [x] prad_broad
- [x] prad_mskcc
- [x] sarc_mskcc

*sarc_mskcc seg is currently removed, need to add back ASAP
![screen shot 2018-08-15 at 7 01 34 pm](https://user-images.githubusercontent.com/5973438/44177851-aefed700-a0bd-11e8-8d83-e968e8f40b4c.png)

**Comment by sandertan** [comment]
How are you doing this? Are you using https://github.com/baudisgroup/segment-liftover ?

**Comment by yichaoS** [comment]
We are using http://hgdownload.cse.ucsc.edu/admin/exe/

**Comment by yichaoS** [comment]
From JJ: I made a fake segment file as attached so that we can view the segments in IGV. I am surprised that most of them are focal changes. The only large region is around chr1 centromere. 
![image](https://user-images.githubusercontent.com/5973438/44408684-de369d80-a52e-11e8-86ab-523f292b182c.png)

**Comment by jjgao** [comment]
@yichaoS https://github.com/baudisgroup/segment-liftover seems like a good one to try out for segment data. Could you give it a try?
