### ISSUE TITLE
Gene symbol starts w/ numbers

### ISSUE THREAD

**Issue by yichaoS** [cBioPortal/datahub#315]
e.g. in prad_broad_2013
![screen shot 2018-08-15 at 6 54 09 pm](https://user-images.githubusercontent.com/5973438/44177634-c9848080-a0bc-11e8-807b-1075f6b1bfd6.png)

e.g. in prad_su2c_2015
![screen shot 2018-08-15 at 6 57 05 pm](https://user-images.githubusercontent.com/5973438/44177725-16685700-a0bd-11e8-94ab-27ba8224bf0a.png)

* affected files is currently removed from DH. Need to fix and add them back ASAP

e.g. The rows with rRNA gene in prad_mskcc_cheny1_organoids_2014 RNA Seq exp file is currently separated: https://github.com/cBioPortal/datahub/blob/master/public/prad_mskcc_cheny1_organoids_2014/data_RNA_Seq_expression_median_rRNA_removed.txt

**Comment by sandertan** [comment]
Wow that's a lot of symbols that start with a number. In the current seed, there are only 8 official symbols that have a symbol as first character, but lots of aliases. 

If they're not in the database, they can't not imported. Shall I make this a warning and inform the user these genes are skipped?

Or do you intend adding the right symbols to these genes?

**Comment by sandertan** [comment]
3 lines above the error it states that 20383 genes are not loaded. That sounds also quite serious.

**Comment by yichaoS** [comment]
The rows with rRNA gene in prad_mskcc_cheny1_organoids_2014 RNA Seq exp file is currently separated: https://github.com/cBioPortal/datahub/blob/master/public/prad_mskcc_cheny1_organoids_2014/data_RNA_Seq_expression_median_rRNA_removed.txt

**Comment by sandertan** [comment]
@yichaoS Can we close this one? If the gene symbol starts with a number and it is in the gene / gene_alias database, there's no error.

**Comment by yichaoS** [comment]
@sandertan Agree. Will do.
