### ISSUE TITLE
msk_impact_2017 cancer types

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/datahub#316]
Hi @yichaoS and @ritikakundra , I was wondering if you could add `ONCOTREE_CODE`, `CANCER_TYPE` and `CANCER_TYPE_DETAILED` to the `msk_impact_2017`. These are available on cbioportal.org but not in the data here.

Also, could you make the following columns a NUMBER instead of STRING in `msk_impact_2017/data_clinical_sample.txt`? I think this will benefit the cbioportal.org version as well.
- DNA_INPUT
- SAMPLE_COVERAGE
- TUMOR_PURITY

**Comment by sandertan** [comment]
Thanks @yichaoS and @rmadupuri for the update!

**Comment by jjgao** [comment]
@yichaoS @rmadupuri have you pushed the chance to the production? I still see the three attributes as String.
