### ISSUE TITLE
TCGA pancancer atlas studies have swapped short names

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#317]
@adamabeshouse commented on [Thu Aug 16 2018](https://github.com/cBioPortal/cbioportal/issues/4656)

Colon Adenocarcinoma and Cholangiocarcinoma have swapped short names.

Worth a check if others do too

**Comment by jjgao** [comment]
@yichaoS @ritikakundra please prioritize. Thanks.

**Comment by ritikakundra** [comment]
@jjgao Fixed in Datahub, will reimport
