### ISSUE TITLE
thca_tcga_pub, nsclc_tcga_broad_2016 validator exceptions

### ISSUE THREAD

**Issue by yichaoS** [cBioPortal/datahub#318]
These two studies are currently missing from DH master branch due to:
![image](https://user-images.githubusercontent.com/5973438/44289372-dd0d2400-a241-11e8-8a78-02dd2e762d82.png)

Quote from @fedde-s slack: 
I can't answer the question, but it looks like something that should, at least partially, be fixed in the validation script—even if it is invalid data, that should cause the validator to output a pretty report telling you about the invalid data, instead of to crash with a Python exception. (edited)
Btw, for the one who is going to answer it: I think the part of that line that's looking for an iterable is the `in` statement. If so, `hugo_symbol` is `None` in a piece of code that expects that to never happen.

These two studies are added in PR https://github.com/cBioPortal/datahub/pull/320

**Comment by sandertan** [comment]
Fix for this crash in https://github.com/cBioPortal/cbioportal/pull/4691

While looking at the issue in the code, I also found the format issue in the data. It seems one rows has been split over 2 lines.

![screen shot 2018-08-22 at 11 25 57](https://user-images.githubusercontent.com/9624990/44459118-b451a980-a608-11e8-96f9-ad2d8f986286.png)
![screen shot 2018-08-22 at 12 38 40](https://user-images.githubusercontent.com/9624990/44459119-b451a980-a608-11e8-9ae2-7788a34ea799.png)
