### ISSUE TITLE
calls to oncokb fail for CDKN2A-isoform gene names

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#321]
@tmazor commented on [Mon Aug 20 2018](https://github.com/cBioPortal/cbioportal/issues/4672)

If I query for CDKN2A isoform gene names (CDKN2AP14ARF and CDKN2AP16INK4A), the OncoKB annotations don't load -- see below, where the same mutations are called drivers in the CDKN2A track but passengers in the isoform tracks. The mutations table also fails to load OncoKB annotations.

![image](https://user-images.githubusercontent.com/10508276/44356163-8c353f80-a47c-11e8-9491-6a87a501ba89.png)

http://www.cbioportal.org/index.do?session_id=5b7af99e498eb8b3d56773c9

---

@jjgao commented on [Mon Aug 20 2018](https://github.com/cBioPortal/cbioportal/issues/4672#issuecomment-414433254)

@schultzn should we remove CDKN2AP14ARF and CDKN2AP16INK4A from the public portal?

---

@schultzn commented on [Mon Aug 20 2018](https://github.com/cBioPortal/cbioportal/issues/4672#issuecomment-414456709)

Yes, I think we should.

**Comment by jjgao** [comment]
@yichaoS @ritikakundra please remove data that are associated with `CDKN2AP14AF` and `CDKN2AP16INK4A`. Please make sure the `CDKN2A` was used.

- [ ] odg_msk_2017
- [ ] lung_msk_2017
- [ ] prad_mskcc_2017
- [ ] hnc_mskcc_2016
- [ ] thyroid_mskcc_2016
- [ ] msk_impact_2017
- [ ] crc_msk_2018
- [ ] summit_2018
- [ ] nsclc_pd1_msk_2018
- [ ] egc_msk_2017
- [ ] blca_nmibc_2017

**Comment by yichaoS** [comment]
fixed in egc_msk_2017 as well.
