### ISSUE TITLE
Run validator on all studies weekly using circleCI

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/datahub#322]
@pieterlukasse : 
>Think about a weekly (cron) run of circle CI on all studies in datahub/master. This is a feature in circle CI (https://circleci.com/docs/2.0/workflows/#scheduling-a-workflow ). Perhaps there is also a badge for this to indicate if master is still completely passing. 

This is useful because the validator will be updated regularly, which could lead that some studies that first passed validation and are merged to `master`, would now fail. Therefore it would be nice to check all studies in `master` regularly. 

It would then be nice to display a list of all studies on datahub in the README, with a badge next to them how they validate (green, yellow, red).

**Comment by fedde-s** [comment]
An alternative would be to start have the `master` branch start from scratch with every major release (=breakage of backwards compatibility) of the validation/loading pipeline, ensuring that only data sets that can actually be loaded enter the `master` branch.

**Comment by fedde-s** [comment]
I think that changes to the pipeline that potentially break compatibility with all existing transformation code should probably be considered a big deal, and not happen every few months.

**Comment by fedde-s** [comment]
But if we want to keep studies that can't be loaded in the `master` branch (is there an issue report about that yet?), such a badge sounds useful.

**Comment by pieterlukasse** [comment]
Perhaps datahub needs its own releases, each with a README stating which cBioPortal version can be used to load the files in this release.

**Comment by fedde-s** [comment]
In that case, instead of weekly, the CI scripts would have to run whenever the cBioPortal release listed in both the README and the Travis config changes?

**Comment by sandertan** [comment]
The enhancement this issue originally was about, is merged in https://github.com/cBioPortal/datahub/pull/341.
