### ISSUE TITLE
Bonilla et al., Genomic analysis identifies new drivers and progression pathways in skin basal cell carcinoma, Nature Genetics 2016

### ISSUE THREAD

**Issue by rmadupuri** [cBioPortal/datahub#335]
Please keep this checklist for curation of a new study.

- [x] [create a issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [ ] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [ ] Document the curation process, e.g. how and by whom the data was transformed
- [ ] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [ ] Create a pull request to datahub once the data is curated
- [ ] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

**Comment by rmadupuri** [comment]
PMID: [26950094](https://www.ncbi.nlm.nih.gov/pubmed/?term=26950094)

- [ ] Does study name and study ID follow our convention? e.g. Tumor_Type (Institue, Journal Year); brca_mskcc_2015
- [ ] Is study meta data complete? e.g. pmid, group of PUBLIC
- [ ] Were all samples profiled with WES/WGS? If not, is gene panel file curated?
- [ ] Are oncotree codes of all samples curated; Cancer Type and Cancer Type Detailed needs to be added in addition to Oncotree Code
- [ ] Clinical sample and patient data with meta files
- [ ] Mutations data with meta files
- [ ] MAF is based on hg19
- [ ] MAF with 2 isoforms: uniprot and mskcc
- [ ] CNA data with meta files
- [ ] CNA segment data with meta files
- [ ] Expression data including z-scores with meta files
- [ ] Case-lists for all profiles
- [ ] Passes Validation
- [ ] Manual checking (Niki or JJ): Triage Portal

**Comment by yichaoS** [comment]
@ritikakundra  There's an extra 10 samples besides  the 293 samples appeared in MAF. Only 1 of them are RNA sample.

**Comment by yichaoS** [comment]
PMID: [26950094](https://www.ncbi.nlm.nih.gov/pubmed/?term=26950094)

- [x] Does study name and study ID follow our convention? e.g. Tumor_Type (Institue, Journal Year); brca_mskcc_2015
- [x] Is study meta data complete? e.g. pmid, group of PUBLIC
- [x] Were all samples profiled with WES/WGS? If not, is gene panel file curated?
- [x] Are oncotree codes of all samples curated; Cancer Type and Cancer Type Detailed needs to be added in addition to Oncotree Code
- [x] Clinical sample and patient data with meta files
- [x] Mutations data with meta files
- [ ] MAF is based on hg19
- [ ] MAF with 2 isoforms: uniprot and mskcc
- [ ] CNA data with meta files
- [ ] CNA segment data with meta files
- [ ] Expression data including z-scores with meta files
- [ ] Case-lists for all profiles
- [ ] Passes Validation
- [ ] Manual checking (Niki or JJ): Triage Portal

**Comment by jjgao** [comment]
@yichaoS is there a pull request for this?

**Comment by rmadupuri** [comment]
Hi @yichaoS, here's my first review of the study:
1. There are 995 Missense mutations in the current MAF that do not have annotations. I think the maf requires reannotation.
2. I see sample `5-VS087-T1` from clinical file is missing in maf. Does that mean this sample doesn't have any mutations?
3. I think MutSig data from supp table 5 should be curated as well and ranked on q value.
4. Should `MATCHED_CONTROL` be changed to `SOMATIC_STATUS` and the values be updated from `yes, no` to `Matched, Unmatched`?
5. Few categorical variables require changing `yes, no` to `Yes, No` or require first letter capitalization

Everything else looks good to me!

**Comment by yichaoS** [comment]
@ritikakundra @rmadupuri re-annotating the MAF. @ritikakundra Do we want to include the mustig data as well?

**Comment by yichaoS** [comment]
@rmadupuri I remembered the discussion we had with @jjgao when this paper is first curated, that the mutsig doesn't need to be included.

**Comment by yichaoS** [comment]
Triage instance: 
https://triage.cbioportal.mskcc.org/study/summary?id=bcc_unige_2016

Screenshot of result for querying 283 non-clonal samples on Hh pathway genes:
![Screen Shot 2019-05-20 at 3 21 45 PM](https://user-images.githubusercontent.com/5973438/58046417-37aa1800-7b13-11e9-8179-2e09fee3c214.png)

Compare to the paper: 
![Screen Shot 2019-05-20 at 3 24 15 PM](https://user-images.githubusercontent.com/5973438/58046449-514b5f80-7b13-11e9-8757-b8f6889a4d0f.png)

**Comment by jjgao** [comment]
@yichaoS the study looks good! Thanks!

**Comment by ritikakundra** [comment]
Curated:https://www.cbioportal.org/study/summary?id=bcc_unige_2016
