### ISSUE TITLE
Welch et al., TP53 and Decitabine in Acute Myeloid Leukemia and Myelodysplastic Syndromes, NEJM 2016

### ISSUE THREAD

**Issue by rmadupuri** [cBioPortal/datahub#337]
Please keep this checklist for curation of a new study.

- [x] [create a issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [x] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [x] Document the curation process, e.g. how and by whom the data was transformed
- [ ] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [ ] Create a pull request to datahub once the data is curated
- [x] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

**Comment by rmadupuri** [comment]
PMID: [27959731](https://www.ncbi.nlm.nih.gov/pubmed/?term=27959731)

- [ ] Does study name and study ID follow our convention? e.g. Tumor_Type (Institue, Journal Year); brca_mskcc_2015
- [ ] Is study meta data complete? e.g. pmid, group of PUBLIC
- [ ] Were all samples profiled with WES/WGS? If not, is gene panel file curated?
- [ ] Are oncotree codes of all samples curated; Cancer Type and Cancer Type Detailed needs to be added in addition to Oncotree Code
- [ ] Clinical sample and patient data with meta files
- [ ] Mutations data with meta files
- [ ] MAF is based on hg19
- [ ] MAF with 2 isoforms: uniprot and mskcc
- [ ] CNA data with meta files
- [ ] CNA segment data with meta files
- [ ] Expression data including z-scores with meta files
- [ ] Case-lists for all profiles
- [ ] Passes Validation
- [ ] Manual checking (Niki or JJ): Triage Portal

**Comment by yichaoS** [comment]
Does study name and study ID follow our convention? e.g. Tumor_Type (Institue, Journal Year); brca_mskcc_2015
  Is study meta data complete? e.g. pmid, group of PUBLIC
  Were all samples profiled with WES/WGS? If not, is gene panel file curated?
  Are oncotree codes of all samples curated; Cancer Type and Cancer Type Detailed needs to be added in addition to Oncotree Code
  Clinical sample and patient data with meta files
  Mutations data with meta files
  MAF is based on hg19
  MAF with 2 isoforms: uniprot and mskcc
  CNA data with meta files
  CNA segment data with meta files
  Expression data including z-scores with meta files
  Case-lists for all profiles
  Passes Validation
  Manual checking (Niki or JJ): Triage Portal

**Comment by rmadupuri** [comment]
Hi @yichaoS, here's the first review of the study:

1. Convert OVERALL_SURVIVAL_DAYS to OS_MONTHS?
2. Can EXPIRED `Yes, No` be changed to OS_STATUS `DECEASED, ALIVE`? (Not sure if that’s right)
3. Include SOMATIC_STATUS attribute in clinical file and normal status in study description? 
4. (minor thing) 5 rows in the maf missed annotation. 
5. Can enhanced exome sequencing be removed/replaced with NA in gene_matrix since there's no explicit panel? 

I didn't find other issues but have the same question from your comment above (point 1) (@ritikakundra) Thanks!

**Comment by yichaoS** [comment]
Re-pasted @rmadupuri comments: 
Hi @yichaoS<https://github.com/yichaoS>, here's the first review of the study:

 - [ ] 1.  Convert OVERALL_SURVIVAL_DAYS to OS_MONTHS?
 - [ ]2.  Can EXPIRED Yes, No be changed to OS_STATUS DECEASED, ALIVE? (Not sure if that’s right)
 - [ ]3.  Include SOMATIC_STATUS attribute in clinical file and normal status in study description?
 - [ ]4.  (minor thing) 5 rows in the maf missed annotation.
 - [ ]5.  Can enhanced exome sequencing be removed/replaced with NA in gene_matrix since there's no explicit panel?

I didn't find other issues but have the same question from your comment above (point 1) (@ritikakundra<https://github.com/ritikakundra>) Thanks!

**Comment by yichaoS** [comment]
@ramya I'm not sure about EXPIRED either. Keeping it as it is for now.

**Comment by ritikakundra** [comment]
@yichaoS I think Expired will mean Deceased

**Comment by yichaoS** [comment]
@ritikakundra @rmadupuri I re-annotated the MAFs and strangely those 5 are still not annotated, and it happened that they all lack values in the `consequences` columns. Would that be the reason?

**Comment by ritikakundra** [comment]
Can you try some on GN browser link to see if they are not suppose to get annotated.

________________________________

**Comment by yichaoS** [comment]
@ritika I tried that. All 5's results was saying this is `introgenetic_variant` in consequence, and the protein change is empty. I manually filled the consequence in, but the annotation remains empty.

**Comment by ritikakundra** [comment]
Are you saying 5 records or 5'?


Cos 5' wont get annotated

________________________________

**Comment by yichaoS** [comment]
No No. I meant "all five records's"

**Comment by ritikakundra** [comment]
Then if they are intronic then its fine if they are not, right?

________________________________

**Comment by yichaoS** [comment]
@ritikakundra I thought so too. So I guess the MAF is fine now?

**Comment by ritikakundra** [comment]
Curated study:https://www.cbioportal.org/study/summary?id=mnm_washu_2016
