### ISSUE TITLE
TCGA Case lists contain samples that are not in study

### ISSUE THREAD

**Issue by zheins** [cBioPortal/datahub#34]

**Comment by oplantalech** [comment]
I am testing all TCGA studies and checking if the case lists are correct:

- [ ]  `acc_tcga`
- [ ]  `blca_tcga`
- [ ]  `brca_tcga`
- [ ]  `cesc_tcga`
- [ ]  `chol_tcga`
- [ ]  `coadread_tcga`
- [ ]  `dlbc_tcga`
- [ ]  `esca_tcga`
- [ ]  `gbm_tcga`
- [ ]  `hnsc_tcga`
- [ ]  `kich_tcga`
- [ ]  `kirc_tcga`
- [ ]  `kirp_tcga`
- [ ]  `laml_tcga`
- [ ]  `lgg_tcga`
- [ ]  `lihc_tcga`
- [ ]  `luad_tcga`
- [ ]  `lusc_tcga`
- [ ]  `meso_tcga`
- [ ]  `ov_tcga`
- [ ]  `paad_tcga`
- [ ]  `pcpg_tcga`
- [ ]  `prad_tcga`
- [ ]  `sarc_tcga`
- [ ]  `skcm_tcga`
- [ ]  `stad_tcga`
- [ ]  `tgct_tcga`
- [ ]  `thca_tcga`
- [ ]  `thym_tcga`
- [ ]  `ucec_tcga`
- [ ]  `ucs_tcga`
- [ ]  `uvm_tcga`

**Comment by oplantalech** [comment]
I'm closing this issue because it is not clear what was the problem.
