### ISSUE TITLE
nsclc_tcga_broad_2016 study is missing from cbioportal.org

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/datahub#348]
The nsclc_tcga_broad_2016 study is no longer visible in the public portal.

See this user report:
https://groups.google.com/forum/#!topic/cbioportal/2IIJeIoUYWU

**Comment by yichaoS** [comment]
@schultzn this might due to a fix from Ino and Ersin last week for multiple mutation_count records for the same sample id. Some studies needs to be completely removed first and then reimport. Trying to arrange an import of that study now.

**Comment by schultzn** [comment]
Thanks. Are other studies affected too?

**Comment by yichaoS** [comment]
@schultzn nsclc_tcga_broad_2016 is back thanks for @n1zea144 help. The other studies I just checked were all private studies and were not affected.

**Comment by jjgao** [comment]
@yichaoS Thanks. It would be great if we can detect missing studies automatically. https://github.com/cBioPortal/datahub/issues/350
