### ISSUE TITLE
CCSK.html 

### ISSUE THREAD

**Issue by saxenaa1** [cBioPortal/datahub#35]
data_cna.txt in the CCSK data set has an issue defined as "Invalid CNA value: possible values are [-2, -1, 0, 1, 2, NA]"
The values encountered are "-0.0072, 0.0078, 0.0799, (1023 more)"

**Comment by pieterlukasse** [comment]
hi @saxenaa1, could you share the link to the study file? I.e. which of the files in https://github.com/cBioPortal/datahub/tree/master/public are you referring to? Thanks.

**Comment by kalletlak** [comment]
Sorry! this is a internal dataset which were testing.
Please ignore it.
Thanks
