### ISSUE TITLE
automatic detection of missing studies on datahub

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#350]
@yichaoS @n1zea144 now that we have all studies in datahub again (do we?), it would be great if we can automatically detect when a study is missing in datahub.

**Comment by yichaoS** [comment]
@jjgao We (almost) have all the studies in. The progress can be tracked here: https://github.com/cBioPortal/datahub/pull/263. We can add in the tracking piece into the weekly circle ci test maybe?
