### ISSUE TITLE
CCSK data set

### ISSUE THREAD

**Issue by saxenaa1** [cBioPortal/datahub#36]
The file: target_ccsk_pa_01_cna_hg19.seg has failures:

Sample ID not defined in clinical file in lines 2, 3, 4, (2655 more)

Unknown chromosome, must be one of (24|20|21|22|23|1|3|2|5|4|7|6|9|8|Y|X|11|10|13|12|15|14|17|16|19|18) in lines 30, 61, 458, (20 more)

and 
Blank cell found in column in line 2497

**Comment by kalletlak** [comment]
Sorry! this is a internal dataset which were testing.
Please ignore it.
Thanks
