### ISSUE TITLE
Labeling of metastatic samples in TCGA Provisional

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/datahub#361]
A few samples (e.g. [this patient in TCGA BRCA](http://www.cbioportal.org/patient?studyId=brca_tcga&caseId=TCGA-AC-A6IX#navCaseIds=TCGA-AC-A6IX)) in the TCGA Provisional studies are not labeled as metastatic in the Patient View, because of wrong data format in the clinical files. The underlying problem for this is quite deep, and I'm not sure if it's worth explaining it our time. This problem only occurs in a few cases (less than 1% of total patients) where patients in TCGA Prov have multiple samples.

Is this a problem worth spending a lot of time on? The correct solution involves moving multiple columns from patient to sample file, which will cause issues with patients that have multiple samples (roughly 1% of patients). For example, with a simple transfer of columns from patient to sample file, all samples will contain the PRIMARY_SITE and METASTATIC_SITE columns and values, although only the primary samples should contain values for PRIMARY_SITE and only metastatic samples should contain values for METASTATIC_SITE. So this will require a lot of manual review and curation. 

Also, I'm not sure if these samples are important, as many don't have mutations, but only segment data. Also most clinical data is missing (see example above) for the second sample.

If it's not worth spending our time on, and we accept that some samples are not correctly labeled, we can add an exception to the validator to allow this data error for TCGA Provisional. Adding this exception is ready in this PR: https://github.com/cBioPortal/cbioportal/pull/4836.

**Comment by jjgao** [comment]
@sandertan @pieterlukasse thanks for bringing this up. It's a systematic issue. It's worse in some cancer types, e.g. melanoma.

I think we should fix it. The minimal we should do is to define `SAMPLE_TYPE` for every TCGA sample based on the barcode suffix.

**Comment by jjgao** [comment]
@sandertan @pieterlukasse would you have the bandwidth to work on this? Or should we put it in our curation backlog?

**Comment by pieterlukasse** [comment]
@jjgao we were hoping the curation team could fix this.

**Comment by Sjoerd-van-Hagen** [comment]
@jjgao please put it in the backlog for now. If we find funding, we might take it on.

**Comment by jjgao** [comment]
@pieterlukasse @Sjoerd-van-Hagen thanks. I assigned it to the @cBioPortal/curation team.

**Comment by pieterlukasse** [comment]
@jjgao any news on this one?

**Comment by jjgao** [comment]
@ritikakundra @rmadupuri I think it's good idea to prioritize this one as the data is wrong currently.

cc'ing @n1zea144

**Comment by ritikakundra** [comment]
@jjgao Ok, we will prioritize this based on this code table:
https://gdc.cancer.gov/resources-tcga-users/tcga-code-tables/sample-type-codes

**Comment by jjgao** [comment]
@ritikakundra yes. thanks!

**Comment by jjgao** [comment]
@rmadupuri could you also fix the data for published and pancan TCGA datasets?
