### ISSUE TITLE
fix entrez_gene_ids in mutation files

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#369]
This issue was found due to #370.

- [ ] add rules in validator, e.g. only numbers should be allowed. Maybe we shouldn't even allow empty entrez_gene_id?
- [ ] reannotate MAFs with wrong/empty entrez_gene_ids.

**Comment by pieterlukasse** [comment]
@sandertan can you discuss this one in datahub channel?

@jjgao you want this warning to be an error instead: https://github.com/cBioPortal/cbioportal/blob/master/core/src/main/scripts/importer/validateData.py#L691?

**Comment by jjgao** [comment]
I think it's a good idea to do that, but I am not sure if I am missing something that prevents us from doing that.

cc'ing @ritikakundra @n1zea144 @sheridancbio

**Comment by sandertan** [comment]
> add rules in validator, e.g. only numbers should be allowed. Maybe we shouldn't even allow empty entrez_gene_id?

We can add this rule to the validator. It is valid MAF format. For mutations outside of genes the GDC file format says:
> "0" is used for regions that do not correspond to a gene region or Ensembl ID

**Comment by jjgao** [comment]
@sandertan: makes sense. thanks!
