### ISSUE TITLE
CBTTC-0005 Data Set

### ISSUE THREAD

**Issue by saxenaa1** [cBioPortal/datahub#37]
The file called data_expression_median.txt in CBTTC-0005 has the following failure messages:

Value is neither a real number nor NA in lines 2, 3, 4, (22947 more) and column number 21

and

Entrez gene id is non-positive in lines 12, 73, 129, (2414 more)

**Comment by pieterlukasse** [comment]
hi @saxenaa1, could you share the link to the study file? I.e. which of the files in https://github.com/cBioPortal/datahub/tree/master/public are you referring to? Thanks.

**Comment by kalletlak** [comment]
Sorry! this is a internal dataset which were testing.
Please ignore it.
Thanks
