### ISSUE TITLE
AML Data Set

### ISSUE THREAD

**Issue by saxenaa1** [cBioPortal/datahub#38]
The file called data_mutations_extended.txt in the data set AML contains the following error that needs to be addressed:

Invalid column header, file cannot be parsed

**Comment by pieterlukasse** [comment]
Hi @saxenaa1, can you point us to the exact AML study you are testing from https://github.com/cBioPortal/datahub/tree/master/public? Thanks.

**Comment by kalletlak** [comment]
Sorry! this is a internal dataset which were testing.
Please ignore it.
Thanks
