### ISSUE TITLE
Grinfeld et al. Classification and Personalized Prognosis in Myeloproliferative Neoplasms. NEJM 2018.

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#395]
"Targeted sequencing for the full coding sequence of 69 genes and genomewide copy-number information was undertaken in 1887 patients"

PMID: 30304655

https://www.ncbi.nlm.nih.gov/pubmed/30304655

- [x] [create a issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [ ] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [ ] Document the curation process, e.g. how and by whom the data was transformed
- [ ] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [ ] Create a pull request to datahub once the data is curated
- [ ] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

**Comment by yichaoS** [comment]
@jjgao @ritikakundra The mutation data is provided in PDF form in the supplemental.  Sent the author an email to request mutation data is csv/txt format, CNA data and survival data.

**Comment by jjgao** [comment]
@yichaoS has the author responded?

**Comment by yichaoS** [comment]
@jjgao Sorry for being so over-due. Sent author another email just now.

**Comment by yichaoS** [comment]
Data Availability:
- Gene Panel: Table S1
- Mutation data: Table S4 (many pages in PDF, not curate-able, email author for CSV format)

Key data that's missing (emailed author)
- CNA
- Survival

**Comment by yichaoS** [comment]
Got reply from `jn5@sanger.ac.uk` on Jun 1, 2021:
```
I can send the supplemental data through as an excel document - I'll endeavour to do so this week. Would be great to have it included in cbioportal.
```
