### ISSUE TITLE
Tyner et al. Functional genomic landscape of acute myeloid leukaemia. Nature 2018

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#402]
https://www.nature.com/articles/s41586-018-0623-z

- [ ] [create a issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [ ] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [ ] Document the curation process, e.g. how and by whom the data was transformed
- [ ] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [ ] Create a pull request to datahub once the data is curated
- [ ] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

data also avaiable here: http://www.vizome.org/aml/

**Comment by bzip2** [comment]
Hi. 

Do you have an idea when this data set will be available in cBio? 

Thanks.

**Comment by rmadupuri** [comment]
Hi,

Thank you for contacting us. We will prioritize this study and make it available on the portal soon.

**Comment by rmadupuri** [comment]
**Data Collection:**

|Datatype|Source|
|---|---|--|
|Clinical|Table S5|
|Mutation|Table S7|
|Expression|Table S8|


**Checklist:**

- [x] Does study name and study ID follow our convention? e.g. Tumor_Type (Institue, Journal Year); brca_mskcc_2015
- [x] Is study meta data complete? e.g. pmid, group of PUBLIC
- [x] Were all samples profiled with WES/WGS? If not, is gene panel file curated?
- [x] Are oncotree codes of all samples curated; Cancer Type and Cancer Type Detailed needs to be added in addition to Oncotree Code
- [x] Clinical sample and patient data with meta files
- [x] Mutations data with meta files
- [x] MAF is based on hg19
- [x] MAF with 2 isoforms: uniprot and mskcc
- [ ] CNA data with meta files
- [ ] CNA segment data with meta files
- [ ] Expression data including z-scores with meta files
- [x] Case-lists for all profiles
- [x] Passes Validation
- [ ] Manual checking (Niki or JJ): Triage Portal

**Comment by yichaoS** [comment]
@rmadupuri: 1st round of QC 

[ ] rename sample and patient ID (add study stable ID as prefix, e.g. 125 -> aml_ohsu_2018_125)
[ ] Study description indicated all samples have matched normals.
[ ] May extract fusion data from source data 3 (supplemental)
[ ] "bone marrow blast %" type change to number (make `>50` a real number that falls into the `50` section of the bar chart
[ ] convert the numeric values in `center of sequencing` into real string values. 
[ ] may extract CPM expression data from table S9
[ ] may overwrite CDD attr meta with table S24
[ ] remove empty lines at the end of MAFs

**Comment by rmadupuri** [comment]
@yichaoS updated the study with your comments. The `center` attribute is coded and centers providing less than five samples were aggregated together and given one ID. Its not mentioned which centers falls under one ID. Leaving as it is for now.

**Comment by rmadupuri** [comment]
Link to public study: https://www.cbioportal.org/study/summary?id=aml_ohsu_2018
