### ISSUE TITLE
one line difference in CPTAC brca files

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/datahub#41]
`data_protein_quantification_Zscores.txt` has 84233 lines while `data_protein_quantification.txt` 84234 lines. Is this correct, or was one line left out from zscores file by mistake?

**Comment by pieterlukasse** [comment]
@yichaoS any updates?

**Comment by rmadupuri** [comment]
@pieterlukasse Can you point us to the study? Cos @ritikakundra is working with GSOC student on the brca  CpTAC data.

**Comment by jjgao** [comment]
it should be this one: https://github.com/cBioPortal/datahub/tree/master/public/brca_tcga

**Comment by rmadupuri** [comment]
@jjgao both the `data_protein_quantification_Zscores.txt` and `data_protein_quantification.txt` in brca_tcga have 82721 lines (not sure if this is the study mentioned by pieter which has 84234 lines).

But we recently redid all the zscores and the line difference issue is taken care of. 

I think the issue can be closed?

**Comment by jjgao** [comment]
thanks, @rmadupuri
