### ISSUE TITLE
Cristescu et al. Pan-tumor genomic biomarkers for PD-1 checkpoint blockade–based immunotherapy. Science 2018.

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#414]
http://science.sciencemag.org/content/362/6411/eaar3593.long

We may need to contact the authors to get the genomic data.

- [ ] [create a issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [ ] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [ ] Document the curation process, e.g. how and by whom the data was transformed
- [ ] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [ ] Create a pull request to datahub once the data is curated
- [ ] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

**Comment by ritikakundra** [comment]
Need Data

**Comment by yichaoS** [comment]
Emailed Author

**Comment by jjgao** [comment]
@yichaoS has the author responded?

**Comment by yichaoS** [comment]
@jjgao didn't get reply. Emailed the author again at `razvan_cristescu@merck.com`

**Comment by sbabyanusha** [comment]
This issue is being closed as we couldn't get a response from the author.
