### ISSUE TITLE
brca_tcga_pub2015 zscore profile issue

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#415]
A user has reported [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/cbioportal/G_haS1Rt5-0/TUW7IQeMBwAJ):

"I was previously working on bio markers for Invasive Ductal Cancer(PAM50 Basal -Like) from  TCGA Breast Cancer Data published in Cell-2015 two years back. When I was analyzing the data at that point in time, some genes were expressed highly (up to 85%). However, when I recently performed the scanning,the mRNA expression(RNA Seq data)  for some, came down to 0%(ANP32E, HDGF, B3GNT5, ENY2, E2F3, C8ORF33 and HEATR1)"

![image](https://user-images.githubusercontent.com/840895/47315052-76293400-d611-11e8-8b62-980240b6e3d3.png)

I did the same query and was able to reproduce the issue.

http://www.cbioportal.org/index.do?session_id=5bce2894498eb8b3d5687234

These genes do not exist in [the z-score file](https://media.githubusercontent.com/media/cBioPortal/datahub/master/public/brca_tcga_pub2015/data_RNA_Seq_v2_mRNA_median_Zscores.txt).

When I looked at plots tab, the original expression data (and copy number data) for these genes exist. 

@ritikakundra @yichaoS  could you help look into this further? Maybe try to regenerate the z-score profiles and see if these genes would re-appear?

**Comment by rmadupuri** [comment]
Fixed. 
![Screen Shot 2020-08-07 at 10 42 22 AM](https://user-images.githubusercontent.com/34350829/89658082-15c5be00-d89c-11ea-9955-40c98b477d8c.png)
