### ISSUE TITLE
over calling CNAs in nepc_wcm_2016?

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#419]
Reported by [a user](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/cbioportal/zXbXFPjYWCw/uuZQ6loTCgAJ)

A query of [a few random genes](http://www.cbioportal.org/index.do?session_id=5bcfdc5b498eb8b3d5687840) returned a lot of amplified cases. Looking at `CN Segments`, the CN changes seems to be long range / arm level.

Querying the same set of random genes in [all prostate studies](http://www.cbioportal.org/results/cancerTypesSummary?session_id=5bcfdd32498eb8b3d5687842). nepc_wcm_2016 contains much more amplification events than other studies.

![image](https://user-images.githubusercontent.com/840895/47402958-bc67bb80-d715-11e8-97c4-2a28772f5b3c.png)

@schultzn any insights?

**Comment by jjgao** [comment]
@schultzn thoughts?

**Comment by schultzn** [comment]
The easy solution is to remove the copy-number calls altogether.

**Comment by jjgao** [comment]
Sounds good.

@yichaoS please remove the discrete copy number data for this study.

**Comment by rmadupuri** [comment]
@jjgao, should the diploid RNA Seq profile be removed as well? Thanks!
