### ISSUE TITLE
mrna zscore files missing in nepc_wcm_2016

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#422]
reported by a user: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/cbioportal/WB8fREqUSPg/XI7ZaxNNCgAJ

@yichao could you generate the zscore files and reimport the study?

**Comment by yichaoS** [comment]
@jj solved in https://github.com/cBioPortal/datahub/pull/518
