### ISSUE TITLE
calculating TMBs

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#426]
We will need to re-curate non-WES studies for:

- gene panel
- number of covered base pairs (can be calculated based on genes covered) #1269
- with matched normal or not (not required by TMB calculation, but could be useful for users to exclude samples w/o matched normals)

cc'ing @schultzn @n1zea144

**Comment by yichaoS** [comment]
@jjgao Gene panels (and matrix files) were added to all public studies.

**Comment by jjgao** [comment]
Thanks, @yichaoS. 

For the next step, we should implement script to calculate `number of covered base pairs` and tmb and save tmb as clinical attributes.

@inodb do we have a service in Genome Nexus to get the length of a gene/exons/protein?

**Comment by jjgao** [comment]
@yichaoS any update on this?

**Comment by inodb** [comment]
we do indeed have a service to get protein/exon length: https://www.genomenexus.org/ensembl/canonical-transcript/hgnc/EGFR?isoformOverrideSource=uniprot

but not gene length yet. We can update https://www.genomenexus.org/ensembl/canonical-gene/hgnc/EGFR to add that

**Comment by jjgao** [comment]
Since we are only going to do nonsynonymous TMBs, we should probably use the CDS length, which is protein length x3...

**Comment by yichaoS** [comment]
TODO list
1. TMB calculation scripts:
     - https://github.com/cBioPortal/datahub-study-curation-tools/pull/20
2. Add `somatic_status`
     - TCGA studies: https://github.com/cBioPortal/datahub/issues/623
     - other public studies: https://github.com/cBioPortal/datahub/issues/626
