### ISSUE TITLE
Remove normals

### ISSUE THREAD

**Issue by yichaoS** [cBioPortal/datahub#440]
These normals were found in data_clinical_sample file

coadread_tcga    TCGA-AG-3725-11
coadread_tcga    TCGA-AG-A020-11
coadread_tcga    TCGA-AG-A01Y-11
coadread_tcga    TCGA-AG-A02N-11
coadread_tcga    TCGA-AG-A036-11
coadread_tcga    TCGA-AG-3731-11
coadread_tcga    TCGA-AG-A01W-11
lgg_tcga    TCGA-TM-A84C-12
lgg_tcga    TCGA-TM-A84B-12
thym_tcga    TCGA-XM-AAZ3-12
thym_tcga    TCGA-XM-AAZ2-12

Also double check MAF and other genomic files, and remove there as well if found.

**Comment by rmadupuri** [comment]
Data files that contain normal samples

coadread_tcga:
1. data_bcr_clinical_data_sample.txt
2. data_methylation_hm450_normals.txt
3. cases_all.txt

lgg_tcga:
1. data_bcr_clinical_data_sample.txt
2. data_cna_hg19.seg
3. cases_all.txt

thym_tcga:
1. data_bcr_clinical_data_sample.txt
2. data_cna_hg19.seg
3. data_mutations_extended.txt
4. data_mutations_mskcc.txt
