### ISSUE TITLE
We should replace the term "Sequenced Tumors" in case lists

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#444]
@schultzn commented on [Fri Oct 19 2018](https://github.com/cBioPortal/cbioportal/issues/5048)

The term sequenced tumors is misleading. To be consistent with what we use in the study view, we should rename these lists to:

"Tumors with mutation data"
and
"Tumors with mutation and CNA data"

**Comment by jjgao** [comment]
- [ ] let's only change the name, not the case list ID (since `_sequenced` is used in code)
- [ ] fix files of `cases_sequenced.txt` and `cases_cnaseq.txt` on datahub
- [ ] run an SQL to fix the database
- [ ] fix the pipeline for future import

**Comment by jjgao** [comment]
@rmadupuri asked if we should use "Samples with..." instead of "Tumors with...". I think it's a good idea.

**Comment by schultzn** [comment]
+1

**Comment by rmadupuri** [comment]
@jjgao @schultzn @ritikakundra here is the table of current case_list_names and their normalized values. Could you let me know if the normalized names are correct or require any changes? Thank you!

case file name | current case_list_name | new normalized case_list_name
----|----- |-------
cases_all.txt | All tumors | All samples
cases_sequenced.txt | Sequenced Tumors / Sequenced Samples / All Seq Tumors / All sequenced samples / All Sequenced Tumors | Samples with mutation data
cases_cna.txt | Tumor Samples with CNA data / Tumors CNA | Samples with CNA data
cases_cnaseq.txt | Tumor Samples with sequencing and CNA data / Tumors with sequencing and CNA data | Samples with mutation and CNA data
cases_log2CNA.txt | Tumor Samples with log2 copy-number / Tumors log2 copy-number | Samples with log2 copy-number
cases_methylation_all.txt | All tumor samples with methylation data | All samples with methylation data
cases_methylation_hm27.txt | Tumor Samples with methylation data (HM27) / Tumors with methylation data | Samples with methylation data (HM27)
cases_methylation_hm450.txt | Tumor Samples with methylation data (HM450) / Tumors with methylation data (HM450) | Samples with methylation data (HM450)
cases_miRNA.txt | Tumor Samples with microRNA data (microRNA-Seq) / Tumors with microRNA | Samples with microRNA data (microRNA-Seq)
cases_mRNA_U133.txt | Tumor Samples with mRNA data (U133 microarray only) | Samples with mRNA data (U133 microarray only)
cases_mRNA.txt | Tumor Samples with mRNA data (Agilent microarray) / Tumors with mRNA | Samples with mRNA data (Agilent microarray)
cases_protein_quantification.txt | Tumor Samples with Protein Quantification (Mass Spec) / Protein Quantification (Mass Spec) | Samples with Protein Quantification (Mass Spec)
cases_RNA_Seq_mRNA.txt | Tumor Samples with mRNA data (RNA Seq) / Tumors with mRNA data (RNA Seq) | Samples with mRNA data (RNA Seq)
cases_RNA_Seq_v2_mRNA.txt | Tumor Samples with mRNA data (RNA Seq V2) / Tumors with mRNA data (RNA Seq V2) | Samples with mRNA data (RNA Seq V2)
cases_rppa.txt | Tumor Samples with RPPA data / Tumors with RPPA data | Samples with RPPA data

**Comment by schultzn** [comment]
Thanks. See my edits in red below.

Niki.

**Comment by schultzn** [comment]
Edits did not come through. Here is an image.

![image](https://user-images.githubusercontent.com/11892704/53385606-f4de0700-394c-11e9-9d49-95491e5ce059.png)

**Comment by rmadupuri** [comment]
Summary table of normalized case names and descriptions - (for reference)

case list file | normalized name | normalized description
------|--------|------
cases_all.txt | All samples | All samples (# samples)
cases_sequenced.txt | Samples with mutation data | Samples with mutation data (# samples)
cases_cna.txt | Samples with CNA data | Samples with CNA data (# samples)
cases_cnaseq.txt | Samples with mutation and CNA data | Samples with mutation and CNA data (# samples)
cases_log2CNA.txt | Samples with log2 copy-number data | Samples with log2 copy-number data (# samples)
cases_methylation_all.txt | Samples with methylation data | Samples with methylation data (# samples)
cases_methylation_hm27.txt | Samples with methylation data (HM27) | Samples with methylation (HM27) data (# samples)
cases_methylation_hm450.txt | Samples with methylation data (HM450) | Samples with methylation (HM450) data (# samples)
cases_miRNA.txt | Samples with microRNA data (microRNA-Seq) | Samples with microRNA data (# samples)
cases_mRNA_U133.txt | Samples with mRNA data (U133 microarray) | Samples with mRNA expression data (# samples)
cases_mRNA.txt | Samples with mRNA data (Agilent microarray) | Samples with mRNA expression data (# samples)
cases_protein_quantification.txt | Samples with protein data (Mass Spec) | Samples with protein data (Mass Spec) (# samples)
cases_RNA_Seq_mRNA.txt | Samples with mRNA data (RNA Seq) | Samples with mRNA expression data (# samples)
cases_RNA_Seq_v2_mRNA.txt | Samples with mRNA data (RNA Seq V2) | Samples with mRNA expression data (# samples)
cases_rppa.txt | Samples with protein data (RPPA) | Samples protein data (RPPA) (# samples)
cases_complete.txt | Complete samples | Samples with mutation, CNA and expression data (# samples)

**Comment by yichaoS** [comment]
@jjgao @schultzn  Do we want to rename these case lists as well? They are only used in the poetic study.

cases_methylation_promoters_hmEPIC.txt
cases_methylation_genebodies_hmEPIC.txt
cases_methylation_promoters_wgbs.txt
cases_methylation_genebodies_wgbs.txt

And this one in gbm_tcga:
cases_GSVA.txt

**Comment by jjgao** [comment]
@yichaoS I think these are fine.
