### ISSUE TITLE
renaming files

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#445]
[A user](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/cbioportal/ONB38tO4JYw/1c7QUfgOBAAJ) was asking about RNAseq v2 file name. 

_median_ in `data_RNA_Seq_v2_mRNA_median_Zscores.txt` the name is confusing and we should consider rename them.

It would be a good idea to look at all file names in datahub, then we can review and rename them in needed.

Once renamed, we will need to make the pipeline code recoganize them. Is it just to change the file names in the importer config sheet?

cc'ing @ritikakundra @n1zea144 @schultzn @tmazor 

- [x] get list of all file names in datahub
- [x] review all file names and decide if we need to rename some of them
- [ ] rename the files in datahub
- [x] support the new file names in Validator
- [x] support the new file names in pipeline (changing the names in importer config sheet)
- [ ] make the changes in the [file format page](https://github.com/cbioportal/cbioportal/blob/master/docs/File-Formats.md)

**Comment by rmadupuri** [comment]
@jjgao adding the list of all unique files names from datahub

all_data_by_genes.txt
data_clinical_patient.txt
data_clinical_sample.txt
data_clinical.txt
data_CNA_consensus.txt
data_cna_hg19.txt
data_CNA_microRNA_removed.txt
data_CNA_RAE.txt
data_CNA.txt
data_expression_median_microRNA_removed.txt
data_expression_median.txt
data_expression_merged_median_Zscores.txt
data_expression_miRNA.txt
data_expression_zscores_file.txt
data_expression_Zscores.txt
data_expression.txt
data_fusions.txt
data_gene_matrix.txt
data_gene_panel_name.txt
data_gistic_genes_amp.txt
data_gistic_genes_del.txt
data_linear_CNA_microRNA_removed.txt
data_linear_CNA_removed.txt
data_linear_CNA.txt
data_log2CNA_microRNA_removed.txt
data_log2CNA.txt
data_methylation_hm27_normals.txt
data_methylation_hm27.txt
data_methylation_hm450_normals.txt
data_methylation_hm450.txt
data_miRNA_median_Zscores.txt
data_mRNA_median_Zscores.txt
data_mRNA_outliers.txt
data_mRNA_seq_fpkm.txt
data_mutations_extended copy.txt
data_mutations_extended_msk.txt
data_mutations_extended_mskcc.txt
data_mutations_extended_non_chrm_genes.txt
data_mutations_extended.txt
data_mutations_filtered_bcca.txt
data_mutations_misc.txt
data_mutations_mskcc.txt
data_mutsig.txt
data_protein_quantification_Zscores.txt
data_protein_quantification.txt
data_RNA_Seq_expression_median_microRNA_removed.txt
data_RNA_Seq_expression_median_rRNA_removed.txt
data_RNA_Seq_expression_median.txt
data_RNA_Seq_mRNA_median_Zscores.txt
data_RNA_Seq_v2_expression_median_normals.txt
data_RNA_Seq_v2_expression_median.txt
data_RNA_Seq_v2_mRNA_median_Zscores.txt
data_rppa_Zscores.txt
data_rppa.txt
data_subtypes.txt
data_SV.txt
data_timeline_specimen.txt
data_timeline_status.txt
data_timeline_surgery.txt
data_timeline_treatment.txt
ignore_data_mutsig.txt
study_id_data_cna_hg19.seg

**Comment by ritikakundra** [comment]
Just to add a note to also make the changes in the file format page:
https://github.com/cbioportal/cbioportal/blob/master/docs/File-Formats.md#expression-data

**Comment by jjgao** [comment]
Thanks, @rmadupuri! I'll review them.

Thanks, @ritikakundra! I've added a to-do list above.

**Comment by jjgao** [comment]
@ritikakundra @schultzn @tmazor here is my first pass. Please review.

file name | rename | comment
-- | -- | --
all_data_by_genes.txt |   | Is this gistic output?
data_clinical_patient.txt |   |  
data_clinical_sample.txt |   |  
data_clinical.txt |   |  
data_CNA_consensus.txt |   | should we rename it?
data_cna_hg19.txt | data_CNA_hg19.seg? |  
data_CNA_RAE.txt |   | should we rename it?
data_CNA.txt |   |  
data_expression_median.txt | data_mRNA_microarray.txt |  
data_expression_merged_median_Zscores.txt | data_RNA_merged_Zscores.txt |  
data_expression_miRNA.txt | data_miRNA.txt |  
data_expression_zscores_file.txt | data_mRNA_microarray_Zscores.txt |  
data_expression_Zscores.txt | data_mRNA_microarray_Zscores.txt | affymetrix-gene-expression-zscores
data_expression.txt | data_mRNA_microarray.txt |  
data_fusions.txt |   |  
data_gene_matrix.txt | data_sequencing_panel_matrix.txt |  
data_gene_panel_name.txt |   |  
data_gistic_genes_amp.txt |   |  
data_gistic_genes_del.txt |   |  
data_linear_CNA.txt |   |  
data_log2CNA.txt |   |  
data_methylation_hm27_normals.txt |   | why do we have this?
data_methylation_hm27.txt |   |  
data_methylation_hm450_normals.txt |   | why do we have this?
data_methylation_hm450.txt |   |  
data_miRNA_median_Zscores.txt | data_miRNA_Zscores.txt |  
data_mRNA_median_Zscores.txt | data_mRNA_microarray_Zscores.txt | agilent-gene-expression
data_mRNA_outliers.txt |   |  
data_mRNA_seq_fpkm.txt |   |  
data_mutations_extended   copy.txt |   | remove?
data_mutations_extended_msk.txt | data_mutations_mskcc.txt |  
data_mutations_extended_mskcc.txt |   |  
data_mutations_extended_non_chrm_genes.txt | ? |  
data_mutations_extended.txt |   |  
data_mutations_filtered_bcca.txt | ? |  
data_mutations_misc.txt | ? |  
data_mutations_mskcc.txt |   |  
data_mutsig.txt |   |  
data_protein_quantification_Zscores.txt |   |  
data_protein_quantification.txt |   |  
data_RNA_Seq_expression_median.txt | data_mRNA_Seq_rpkm.txt | rpkm according to the original firehose data
data_RNA_Seq_mRNA_median_Zscores.txt | data_mRNA_Seq_rpkm_Zscores.txt |  
data_RNA_Seq_v2_expression_median_normals.txt | remove?
data_RNA_Seq_v2_expression_median.txt | data_mRNA_Seq_v2_rsem.txt |  
data_RNA_Seq_v2_mRNA_median_Zscores.txt | data_mRNA_Seq_v2_rsem_Zscores.txt |  
data_rppa_Zscores.txt |   |  
data_rppa.txt |   |  
data_subtypes.txt |   |  
data_SV.txt |   |  
data_timeline_specimen.txt |   |  
data_timeline_status.txt |   |  
data_timeline_surgery.txt |   |  
data_timeline_treatment.txt |   |  
ignore_data_mutsig.txt | ? |  
study_id_data_cna_hg19.seg | data_CNA_hg19.seg |

**Comment by jjgao** [comment]
I like to push this forward. @schultzn could you review the new names above? Thanks.

**Comment by n1zea144** [comment]
@jjgao Yes, once the new names are established, it would be a matter of changing the STAGING_FILENAME on the datatypes worksheet of the importer configuration spreadsheet.  Of course, I would test on a single study first to make sure of this.

**Comment by n1zea144** [comment]
@jjgao Can we keep the file names all lowercase?  The mixed case hurts the eyes.

**Comment by n1zea144** [comment]
@jjgao Can we lowercase all the names?

**Comment by jjgao** [comment]
@n1zea144 good idea. I've made all the names in the 2nd column lower case.

**Comment by jjgao** [comment]
@rmadupuri I am wondering if we can move this forward at some point?

**Comment by rmadupuri** [comment]
Hi @jjgao, @n1zea144, reviving this issue, couple of new files were added after the last review. I have summarized them here https://docs.google.com/spreadsheets/d/1mYfY1xrxDSzJeQKkK9ikTOz_468fJRLPX0OGM-dv2LY/edit?usp=sharing. Could you take another look to finalize the names? Thanks!! cc: @cBioPortal/curation

**Comment by jjgao** [comment]
Thanks, @rmadupuri. I have edited the sheet.

**Comment by jjgao** [comment]
I also renamed the two mutations files to make them more clear...

![image](https://user-images.githubusercontent.com/840895/95587964-c5d8b400-0a10-11eb-8d06-16efb554f9f6.png)

**Comment by rmadupuri** [comment]
New naming patterns list:

File Category | Old Data Filename | New Data Filename
-- | -- | --
Clinical | data_bcr_clinical_data_patient.txt | data_clinical_patient.txt
Clinical | data_bcr_clinical_data_sample.txt | data_clinical_sample.txt
CNA | data_CNA.txt | data_cna.txt
CNA | data_linear_CNA.txt | data_linear_cna.txt
CNA | data_log2_CNA.txt | data_log2_cna.txt
CNA | data_log2CNA.txt | data_log2_cna.txt
CNA | data_CNA_consensus.txt | data_cna_consensus.txt
CNA | data_CNA_RAE.txt | data_cna_rae.txt
CNA | data_CNA_foundation.txt | data_cna_foundation.txt
CNA | data_armlevel_CNA.txt | data_armlevel_cna.txt
RPPA | data_rppa_Zscores.txt | data_rppa_zscores.txt
Protein Quantification | data_protein_quantification_Zscores.txt | data_protein_quantification_zscores.txt
MAF | data_mutations_extended.txt | data_mutations_uniprot_canonical_transcripts.txt
MAF | data_mutations_extended_*.txt | data_mutations_uniprot_canonical_transcripts_*.txt
MAF | data_mutations_extended_foundation.txt | data_mutations_uniprot_canonical_transcripts_foundation.txt
MAF | data_mutations_mskcc.txt | data_mutations_mskimpact_transcripts.txt
Gene Panel | data_gene_matrix.txt | data_gene_panel_matrix.txt
Generic Assay | data_drug_treatment_AUC.txt | data_drug_treatment_auc.txt
Generic Assay | data_drug_treatment_IC50.txt | data_drug_treatment_ic50.txt
Generic Assay | data_drug_treatment_ZSCORE.txt | data_drug_treatment_zscore.txt
mRNA | data_expression.txt | data_mrna_affymetrix_microarray.txt
mRNA | data_expression_Zscores.txt | data_mrna_affymetrix_microarray_zscores_ref_diploid_samples.txt
mRNA | data_expression_all_sample_Zscores.txt | data_mrna_affymetrix_microarray_zscores_ref_all_samples.txt
mRNA | data_expression_median.txt | data_mrna_agilent_microarray.txt
mRNA | data_mRNA_median_Zscores.txt | data_mrna_agilent_microarray_zscores_ref_diploid_samples.txt
mRNA | data_mRNA_median_all_sample_Zscores.txt | data_mrna_agilent_microarray_zscores_ref_all_samples.txt
mRNA | data_RNA_Seq_expression_median.txt | data_mrna_seq_rpkm.txt
mRNA | data_rna_seq_mrna.txt | data_mrna_seq_rpkm.txt
mRNA | data_rna_seq_mrna_median_Zscores.txt | data_mrna_seq_rpkm_zscores_ref_diploid_samples.txt
mRNA | data_RNA_Seq_mRNA_median_Zscores.txt | data_mrna_seq_rpkm_zscores_ref_diploid_samples.txt
mRNA | data_expression_zscores_file.txt | data_mrna_seq_rpkm_zscores_ref_diploid_samples.txt
mRNA | data_RNA_Seq_mRNA_median_all_sample_Zscores.txt | data_mrna_seq_rpkm_zscores_ref_all_samples.txt
mRNA | data_RNA_Seq_v2_expression_median.txt | data_mrna_seq_v2_rsem.txt
mRNA | data_RNA_Seq_v2_expression_RSEM_UQ_Log2.txt | data_mrna_seq_v2_rsem.txt
mRNA | data_RNA_Seq_v2_mRNA_median_Zscores.txt | data_mrna_seq_v2_rsem_zscores_ref_diploid_samples.txt
mRNA | data_RNA_Seq_v2_mRNA_median_all_sample_Zscores.txt | data_mrna_seq_v2_rsem_zscores_ref_all_samples.txt
mRNA | data_mRNA_seq_fpkm_capture.txt | data_mrna_seq_fpkm_capture.txt
mRNA | data_mRNA_seq_fpkm_capture_Zscores.txt | data_mrna_seq_fpkm_capture_zscores_ref_diploid_samples.txt
mRNA | data_mRNA_seq_fpkm_capture_all_sample_Zscores.txt | data_mrna_seq_fpkm_capture_zscores_ref_all_samples.txt
mRNA | data_mRNA_seq_fpkm_polya.txt | data_mrna_seq_fpkm_polya.txt
mRNA | data_mRNA_seq_fpkm_polya_Zscores.txt | data_mrna_seq_fpkm_polya_zscores_ref_diploid_samples.txt
mRNA | data_mRNA_seq_fpkm_polya_all_sample_Zscores.txt | data_mrna_seq_fpkm_polya_zscores_ref_all_samples.txt
mRNA | data_RNA_Seq_expression_cpm.txt | data_mrna_seq_cpm.txt
mRNA | data_RNA_Seq_expression_cpm_Zscores.txt | data_mrna_seq_cpm_zscores_ref_diploid_samples.txt
mRNA | data_RNA_Seq_expression_cpm_all_sample_Zscores.txt | data_mrna_seq_cpm_zscores_ref_all_samples.txt
mRNA | data_RNA_Seq_expression_tpm.txt | data_mrna_seq_tpm.txt
mRNA | data_RNA_Seq_expression_tpm_Zscores.txt | data_mrna_seq_tpm_zscores_ref_diploid_samples.txt
mRNA | data_RNA_Seq_expression_tpm_all_sample_Zscores.txt | data_mrna_seq_tpm_zscores_ref_all_samples.txt
mRNA | data_RNA_Seq_v2_mRNA_median_normals.txt | data_mrna_seq_v2_rsem_normal_samples.txt
mRNA | data_RNA_Seq_v2_mRNA_median_Zscores_normals.txt | data_mrna_seq_v2_rsem_normal_samples_zscores_ref_normal_samples.txt
mRNA | data_RNA_Seq_v2_mRNA_median_all_sample_ref_normal_Zscores.txt | data_mrna_seq_v2_rsem_zscores_ref_normal_samples.txt
mRNA | data_expression_merged.txt | data_mrna_affymetrix_microarray_merged.txt
mRNA | data_expression_merged_Zscores.txt | data_mrna_affymetrix_microarray_merged_zscores_ref_diploid_samples.txt
mRNA | data_expression_merged_median_Zscores.txt | data_mrna_mirna_merged_zscores.txt
mRNA | data_mRNA_outliers.txt | data_mrna_outliers.txt
miRNA | data_expression_miRNA.txt | data_mirna.txt
miRNA | data_miRNA_median_Zscores.txt | data_mirna_zscores.txt
SV | data_SV.txt | data_sv.txt
Methylation | data_methylation_promoters_hmEPIC.txt | data_methylation_promoters_hmepic.txt
Methylation | data_methylation_genebodies_hmEPIC.txt | data_methylation_genebodies_hmepic.txt

**Comment by jjgao** [comment]
Any update on this? _median has created a lot of confusion. Here is another one: https://groups.google.com/g/cbioportal/c/ajpBL6xaz0Q/m/fPZxTVTQAwAJ

**Comment by rmadupuri** [comment]
This will be picked up in the next two weeks @jjgao. Importer updates are underway. Backend team is busy currently cc @n1zea144 @sheridancbio.

**Comment by songsong0425** [comment]
Hi, can I ask a question? What is the "data_mrna_seq_v2_rsem_zscores_ref_normal_samples.txt" file in cBioPortal? Is there any description about this file?
