### ISSUE TITLE
In study selector, tooltip reports higher sample count than elsewhere

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#446]
@alisman commented on [Mon Nov 05 2018](https://github.com/cBioPortal/cbioportal/issues/5190)

![image.png](https://images.zenhubusercontent.com/597f3b48f8b79f8376e15c84/9db8c09a-3297-4352-81fd-21557424e938)

---

@alisman commented on [Mon Nov 05 2018](https://github.com/cBioPortal/cbioportal/issues/5190#issuecomment-436021290)

@onursumer can you figure out why this is?  Maybe one shows the patient count, the other the sample count?

---

@jjgao commented on [Mon Nov 05 2018](https://github.com/cBioPortal/cbioportal/issues/5190#issuecomment-436076216)

cc'ing @kalletlak as well as he developed the code to add the number of samples.

---

@alisman commented on [Fri Nov 09 2018](https://github.com/cBioPortal/cbioportal/issues/5190#issuecomment-437452013)

It's a data issue.  There's a description field on sample list which contains a sample count which is add odds with the real count
http://www.cbioportal.org/rc/api/studies/nsclc_tcga_broad_2016/sample-lists?projection=DETAILED

![image](https://user-images.githubusercontent.com/186521/48281110-9f283200-e423-11e8-9938-7087a0aea29a.png)

@jjgao is this for @ritikakundra ?

**Comment by yichaoS** [comment]
@jjgao Case list are all normalized (manually in DB, and in datafiles in this PR number of samples in case lists.https://github.com/cBioPortal/datahub/pull/684), with no mentioning of number of samples.
