### ISSUE TITLE
NA in REFERENCE_ALLELE or TUMOR_SEQ_ALLELE

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#465]
There are many studies with `NA` in either REFERENCE_ALLELE or TUMOR_SEQ_ALLELE
Our annotator seems to be able to handle NA in REFERENCE_ALLELE but not in TUMOR_SEQ_ALLELE

![image](https://user-images.githubusercontent.com/840895/48809329-29a94500-ecf2-11e8-9443-665acf4140f6.png)

![image](https://user-images.githubusercontent.com/840895/48809371-51001200-ecf2-11e8-951c-a7d5b8848c11.png)

We should fix them. If NA means `-` (an insertion or deletion), let follow MAF spec and use `-`. @sandertan is there a rule in validator to enforce this?

- acc_tcga_mutations
- ampca_bcm_2016_mutations
- blca_bgi_mutations
- blca_dfarber_mskcc_2014_mutations
- blca_nmibc_2017_mutations
- blca_tcga_mutations
- blca_tcga_pan_can_atlas_2018_mutations
- blca_tcga_pub_2017_mutations
- blca_tcga_pub_mutations
- brca_broad_mutations
- brca_igr_2015_mutations
- brca_tcga_mutations
- brca_tcga_pan_can_atlas_2018_mutations
- brca_tcga_pub2015_mutations
- brca_tcga_pub_mutations
- breast_msk_2018_mutations
- cellline_ccle_broad_mutations
- cesc_tcga_mutations
- cll_iuopa_2015_mutations
- coadread_dfci_2016_mutations
- coadread_tcga_mutations
- coadread_tcga_pub_mutations
- coad_tcga_pan_can_atlas_2018_mutations
- crc_msk_2018_mutations
- desm_broad_2015_mutations
- dlbc_tcga_mutations
- esca_tcga_mutations
- esca_tcga_pan_can_atlas_2018_mutations
- escc_ucla_2014_mutations
- es_dfarber_broad_2014_mutations
- gbm_tcga_mutations
- gbm_tcga_pan_can_atlas_2018_mutations
- gbm_tcga_pub2013_mutations
- hnsc_broad_mutations
- hnsc_mdanderson_2013_mutations
- hnsc_tcga_mutations
- hnsc_tcga_pan_can_atlas_2018_mutations
- hnsc_tcga_pub_mutations
- kich_tcga_mutations
- kich_tcga_pan_can_atlas_2018_mutations
- kich_tcga_pub_mutations
- kirc_bgi_mutations
- kirc_tcga_mutations
- kirc_tcga_pan_can_atlas_2018_mutations
- kirc_tcga_pub_mutations
- kirp_tcga_mutations
- laml_tcga_mutations
- laml_tcga_pan_can_atlas_2018_mutations
- laml_tcga_pub_mutations
- lcll_broad_2013_mutations
- lgggbm_tcga_pub_mutations
- lgg_tcga_mutations
- lgg_tcga_pan_can_atlas_2018_mutations
- lihc_amc_prv_mutations
- lihc_tcga_mutations
- lihc_tcga_pan_can_atlas_2018_mutations
- luad_broad_mutations
- luad_tcga_mutations
- luad_tcga_pan_can_atlas_2018_mutations
- luad_tcga_pub_mutations
- lung_msk_2017_mutations
- lusc_tcga_mutations
- lusc_tcga_pan_can_atlas_2018_mutations
- lusc_tcga_pub_mutations
- mbl_broad_2012_mutations
- mbl_sickkids_2016_mutations
- mel_tsam_liang_2017_mutations
- meso_tcga_mutations
- mixed_pipseq_2017_mutations
- mpnst_mskcc_mutations
- msk_impact_2017_mutations
- nbl_broad_2013_mutations
- npc_nusingapore_mutations
- nsclc_pd1_msk_2018_mutations
- nsclc_tcga_broad_2016_mutations
- ov_tcga_mutations
- ov_tcga_pan_can_atlas_2018_mutations
- ov_tcga_pub_mutations
- paad_qcmg_uq_2016_mutations
- paad_utsw_2015_mutations
- panet_arcnet_2017_mutations
- past_dkfz_heidelberg_2013_mutations
- pcnsl_mayo_2015_mutations
- pcpg_tcga_mutations
- pediatric_dkfz_2017_mutations
- prad_broad_2013_mutations
- prad_broad_mutations
- prad_eururol_2017_mutations
- prad_fhcrc_mutations
- prad_mskcc_2017_mutations
- prad_p1000_mutations
- prad_su2c_2015_mutations
- prad_tcga_mutations
- prad_tcga_pan_can_atlas_2018_mutations
- prad_tcga_pub_mutations
- read_tcga_pan_can_atlas_2018_mutations
- sarc_mskcc_mutations
- sarc_tcga_mutations
- sarc_tcga_pan_can_atlas_2018_mutations
- sclc_cancercell_gardner_2017_mutations
- sclc_jhu_mutations
- skcm_broad_brafresist_2012_mutations
- skcm_broad_mutations
- skcm_tcga_mutations
- skcm_ucla_2016_mutations
- stad_pfizer_uhongkong_mutations
- stad_tcga_mutations
- stad_tcga_pan_can_atlas_2018_mutations
- stad_tcga_pub_mutations
- stes_tcga_pub_mutations
- summit_2018_mutations
- tet_nci_2014_mutations
- tgct_tcga_mutations
- tgct_tcga_pan_can_atlas_2018_mutations
- thca_tcga_mutations
- thca_tcga_pan_can_atlas_2018_mutations
- thca_tcga_pub_mutations
- thym_tcga_mutations
- ucec_msk_2018_mutations
- ucec_tcga_mutations
- ucec_tcga_pan_can_atlas_2018_mutations
- ucec_tcga_pub_mutations
- ucs_tcga_mutations
- ucs_tcga_pan_can_atlas_2018_mutations
- wt_target_2018_pub_mutations

```SQL
select DISTINCT gp.stable_id
from mutation_event me, mutation m, genetic_profile gp
where me.mutation_event_id=m.mutation_event_id and m.genetic_profile_id=gp.genetic_profile_id
AND MUTATION_TYPE!="FUSION"
and (REFERENCE_ALLELE="NA" or TUMOR_SEQ_ALLELE="NA");
```

@ritikakundra: please also run the sql in private databases and fix the data.

**Comment by ritikakundra** [comment]
@jjgao Checked the private instance and majority of these are not part of it. Rebuild of the public database will resolve almost all of this. We have a few from the private portal that we can look into.

**Comment by sandertan** [comment]
@jjgao I think the `--strict_maf_checks` mode in the validator check this. @dionnezaal added some nice validation tests that follow the documented MAF format. Currently, when a PR with new study data or during the weekly check, this mode is **not** enabled. I can't remember why we disabled it, but if this format is a priority, we can enable it again. Perhaps it's best to first run `validateStudies.py` with `--strict_maf_checks` on all studies locally to see what warnings/errors we get from it.

Btw, NCI GDC is updating their MAF documentation soon! I've already received a Word doc with what they propose to publish.

**Comment by jjgao** [comment]
Thanks, @sandertan!

**Comment by yichaoS** [comment]
@jjgao @ritikakundra Updated list from public DB:

**Comment by sbabyanusha** [comment]
@jjgao @ritikakundra  We are dealing with the issue and it is associated with the mutated fix #114. Done resolving this issue for most the studies.

**Comment by yichaoS** [comment]
There are only 3 public studies having this 'NA' issue: 
acc_2019_mutations
brca_igr_2015_mutations
ov_tcga_pan_can_atlas_2018_mutations
Yet there are other studies doesn't have 'NA' in alleles but blanks.
These studies are part of the mutated issue fix effort(https://github.com/cBioPortal/datahub/issues/114), and are listed here: https://docs.google.com/spreadsheets/d/1RFj8zzMPv4PCAs3sFM9ro3FP4vRg-Za-JI2AFlx6FHg/edit#gid=0

**Comment by yichaoS** [comment]
@jjgao Our validator currently are allowing alleles to be blank/NA and importers are still importing these variants.
