### ISSUE TITLE
Mutation count missing for some samples in the published Nature Medicine MSK-IMPACT study.

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/datahub#468]
Mutation count missing for some samples in the published Nature Medicine MSK-IMPACT study.

It looks like 7% are missing mutation count

**Comment by rmadupuri** [comment]
@jjgao @schultzn the 7% (817 samples) were sequenced but no somatic mutations were identified (cross checked with mskimpact 30k cohort).

**Comment by jjgao** [comment]
I thought we would add 0 for those cases. @ersinciftci @inodb do you know?

**Comment by yichaoS** [comment]
This issue is fixed. Missing mutation counts were added as `0`.
