### ISSUE TITLE
where is the cBioPortal release versions 1.8.0 or 1.9.0?

### ISSUE THREAD

**Issue by miaoyibo** [cBioPortal/datahub#481]
Please keep this checklist for curation of a new study.

- [ ] [create a issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [ ] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [ ] Document the curation process, e.g. how and by whom the data was transformed
- [ ] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [ ] Create a pull request to datahub once the data is curated
- [ ] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

**Comment by sandertan** [comment]
Hi @miaoyibo welcome to the cBioPortal Datahub repository, which contains public study data. You can find cBioPortal releases on https://github.com/cBioPortal/cbioportal/releases .

Please use this GitHub repository for logging data issues. Questions regarding the functionality can be sent to cbioportal@googlegroups.com or posted on the User Forum https://groups.google.com/forum/#!forum/cbioportal .
