### ISSUE TITLE
METABRIC RNA-Seq profile description is not clear (is it RNA-Seq or Micorarray)

### ISSUE THREAD

**Issue by PichaiRaman** [cBioPortal/datahub#493]
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/cbioportal/YzgtXRHIOGc

**Comment by jjgao** [comment]
![image](https://user-images.githubusercontent.com/840895/49598246-35c90f80-f94c-11e8-8d72-b7a493cad7a3.png)

**Comment by yichaoS** [comment]
Fixed
![Screen Shot 2019-10-21 at 3 34 14 PM](https://user-images.githubusercontent.com/5973438/67237163-b8e63d80-f418-11e9-88cf-8b121a174d3b.png)
