### ISSUE TITLE
study name change of crc_msk_2017

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#497]
In the [crc msk paper](https://www.sciencedirect.com/science/article/pii/S1535610817305561), a link is included to crc_msk_2017

![image](https://user-images.githubusercontent.com/840895/49954421-6bcb3e00-fece-11e8-8ea3-f060bdf5b155.png)

But it has been changed to crc_msk_2018 in https://github.com/cBioPortal/datahub/pull/155.

I think we should either revert back the name or support aliases in our database.

[reported by a user](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/cbioportal/wmHY8qVZ5TA/bY4n7fHQDwAJ)

notify: @schultzn @n1zea144

**Comment by ritikakundra** [comment]
@schultzn : I think you told me to change the 2017 to 2018 in an email since the paper came out today. Should we go back to map the paper?

**Comment by schultzn** [comment]
Yes, let’s match what was in the paper. Thanks.

**Comment by jjgao** [comment]
@ritikakundra let's rename.

It looks like crc_msk_2018 is out there for so long. Any sessions or virtual studies with the study will not work after renaming.

@n1zea144 maybe we can think of support study aliases which will give us more freedom of rename studies.

**Comment by n1zea144** [comment]
@jjgao This is being worked on this SCRUM (reverting back to study id in the paper).  I'll add a card to backlog to support study aliases, but it will be on the back-burner until higher priority items are addressed.
