### ISSUE TITLE
missing data in mesothelioma tcga

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#50]
From a user:

"I downloaded many of the TCGA, Provisional data sets from the portal (http://www.cbioportal.org/data_sets.jsp) and found only mesothelioma had several files missing, including: data_mutations_extended.txt. Could you please let me know if this file is available for download?"

**Comment by zheins** [comment]
@jjgao  PR #49 addresses this.

**Comment by ritikakundra** [comment]
@zheins Can we close this?
