### ISSUE TITLE
Zhang et al. Interfaces of Malignant and Immunologic Clonal Dynamics in Ovarian Cancer. Cell. 2018.

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#501]
https://www.ncbi.nlm.nih.gov/pubmed/29754820

Please keep this checklist for curation of a new study.

- [ ] [create a issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [ ] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [ ] Document the curation process, e.g. how and by whom the data was transformed
- [ ] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [ ] Create a pull request to datahub once the data is curated
- [ ] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

**Comment by yichaoS** [comment]
Presented in Journal Club: https://docs.google.com/presentation/d/1Z6ClE38fKMXIa-AR4bhO2-Y4uKSwVxAQUWmwFtV9sQU/edit#slide=id.g5b4c162192_0_26

However, seems like we are missing the WGS data in the supp files. 
Need to email author.

**Comment by yichaoS** [comment]
Emailed author. Waiting for response.

**Comment by jjgao** [comment]
@yichaoS should we keep this open?

**Comment by yichaoS** [comment]
@jjgao Yes! The 'wont fix' stale robot closed it. Should have reopened it.

**Comment by sbabyanusha** [comment]
This issue is being closed as we couldn't get a response from the author.
