### ISSUE TITLE
TCGA provisional datasets have a patient_weight field which is not actually patient weight

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#505]
@tmazor commented on [Mon Dec 17 2018](https://github.com/cBioPortal/cbioportal/issues/5467)

I suspect this is sample weight in mg, rather than patient weight in kg, but that should be confirmed against the original data source.

lgg_tcga
![image](https://user-images.githubusercontent.com/10508276/50121177-e7f2b800-0225-11e9-9c46-0ef634596be6.png)

chol_tcga
![image](https://user-images.githubusercontent.com/10508276/50121238-1a9cb080-0226-11e9-8acb-fbc66fd3087d.png)

**Comment by tmazor** [comment]
Also, this plot loads by default in the new study view, so we should fix this quickly since it's quite misleading for users right now

**Comment by ritikakundra** [comment]
Changed this to sample weight

**Comment by tmazor** [comment]
Thanks @ritikakundra  - lgg_tcga looks much better now, but this field exists in many (all?) of the TCGA provisional studies. I looked in acc_tcga, chol_tcga and blca_tcga and see "Initial Patient Weight" in all of them. Can you update all provisional studies for this field? Thanks!

**Comment by tmazor** [comment]
I still see "initial patient weight" in TCGA provisional studies (see: acc_tcga). Is the data correction just not on production yet? @rmadupuri @ritikakundra

**Comment by ritikakundra** [comment]
Addressed in Corrected weight attribute in provisional studies #558

**Comment by jjgao** [comment]
@ritikakundra I think there are still some in published tcga studies: https://github.com/cBioPortal/cbioportal/issues/6315
