### ISSUE TITLE
lgg tcga provisional mutsig results are weird

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#506]
@tmazor commented on [Mon Dec 17 2018](https://github.com/cBioPortal/cbioportal/issues/5471)

NRAS has one mutation but appears with a mutsig icon:
![image](https://user-images.githubusercontent.com/10508276/50121708-921f0f80-0227-11e9-8ce0-822d0e389eb6.png)

**Comment by tmazor** [comment]
I guess so - it's better to show nothing than to show bad data. It's a shame though, MutSig is a nice thing to have.
