### ISSUE TITLE
Gerhauser et al. Molecular Evolution of Early-Onset Prostate Cancer... Cancer Cell 2018.

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/datahub#509]
Please keep this checklist for curation of a new study.

PMID: [30537516](https://www.ncbi.nlm.nih.gov/pubmed/30537516)

- [ ] [create a issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [ ] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [ ] Document the curation process, e.g. how and by whom the data was transformed
- [ ] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [ ] Create a pull request to datahub once the data is curated
- [ ] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

**Comment by schultzn** [comment]
Somatic mutation data is not available yet, but will supposedly be available in Mendeley Data soon (I contacted the authors on 12/19).

**Comment by schultzn** [comment]
The data are now available at:
https://data.mendeley.com/datasets/6gtrrxrn2c/1

**Comment by schultzn** [comment]
@rmadupuri Any update on this study?

**Comment by rmadupuri** [comment]
Hi @schultzn I didn't get to work on this study yet. But will plan to get this out by the end of this week.

**Comment by rmadupuri** [comment]
**Data Collection:**

|Datatype|Source|
|---|---|
|Clinical (Patient)|Table S1 (_Sheet: Clinical data ICGC PC_)|
|Structural Variants| Mendeley _(somatic_svs.gz)_|
|MAF| Mendeley _(somatic_snv.maf.gz)_|
|RNAseq| Mendeley _(rna_rpkm.tsv.gz)_|

NOTE: The paper doesn't specify the number of samples per patient. The number of multi-area samples per patient was derived from the genomic files.
