### ISSUE TITLE
Timeline data not validated

### ISSUE THREAD

**Issue by ritikakundra** [cBioPortal/datahub#533]
The circle CI does not fail if the patient ID in the timeline file is not in the sample or patient file and allows the study to get updated in the master branch of datahub

**Comment by sandertan** [comment]
Hi @ritikakundra indeed, validation for timeline data is not implemented yet. Is there a study on datahub for which contains errors in timeline data we can use for testing purposes? 

I'll have to check how much effort it is to add validation for timeline data.
