### ISSUE TITLE
skml_tcga has NA for z-scores of some genes

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#534]
@tmazor commented on [Wed Jan 16 2019](https://github.com/cBioPortal/cbioportal/issues/5615)

In skml_tcga, EIF2A, AHNAK and DDX3Y are all "NA" for z-scores, even though all 3 genes have expression data.

This issue was flagged by a user: https://groups.google.com/forum/#!topic/cbioportal/RPEBkuhIgus

**Comment by jjgao** [comment]
I thought it could be that the CNA data was not available (NA) so that z-scores were not calculated. But it seems that only DDX3Y dooesn't have CNA data.

@yichaoS could you recalculate the zscores for this study and see if that would fix it?

**Comment by yichaoS** [comment]
@jj Makes sense. After recalculating/generating (PR: https://github.com/cBioPortal/datahub/pull/564), EIF2A, AHNAK now have zscore data, and DDX3Y remains 'NA'.
