### ISSUE TITLE
Robinson et al. Integrative clinical genomics of metastatic cancer. Nature 2017

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#537]
https://www.ncbi.nlm.nih.gov/pubmed/28783718

Please keep this checklist for curation of a new study.

- [x] [create a issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [x] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [x] Document the curation process, e.g. how and by whom the data was transformed
- [x] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [x] Create a pull request to datahub once the data is curated
- [x] Push to triage portal
- [x] Import into  msk and public portal database
- [x] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

**Comment by yichaoS** [comment]
Data curated:
Table 1: Clinical data

**Comment by rmadupuri** [comment]
Link to public study: https://www.cbioportal.org/study/summary?id=metastatic_solid_tumors_mich_2017
