### ISSUE TITLE
Resolve duplicated hugo symbols in gene table

### ISSUE THREAD

**Issue by n1zea144** [cBioPortal/datahub#540]
We are in the process of identifying duplicated hugo gene symbols in the gene table.  In some cases the symbol/entrez-id pair have been discontinued and a new entrez-id has been assigned to the same symbol.  In other cases, the same hugo symbol is assigned to multiple entrez ids (this seems to occur with tRNA type genes, like TRNAC-GCA).

In the cases of discontinued entrez-ids, migrating the to the new entrez id should be straightforward.  More thought will have to be given to the case where the same symbol is mapped to multiple entrez ids (do we even have references to tRNA type genes - maybe in RNASEQ files?).

Once this clean-up is complete, we should revisit adding unique constraint to the gene table opened by @pieterlukasse, [1266](https://github.com/cBioPortal/cbioportal/issues/1266).

We will need to cleanup all production databases for this to happen.  @angelicaochoa can work with @ritikakundra to provide records in question.

**Comment by yichaoS** [comment]
@n1zea144 @inodb @jjgao (cc'@ritikakundra @rmadupuri @sbabyanusha) 

We've done a few rounds of evaluation for potentially using HGNC table as our new gene table. 
The result can be tracked here:  
https://docs.google.com/spreadsheets/d/1Do-ufGJ8PE_2yz_pmPVpcPUl39f7AONkKFrcjVnybSs/edit#gid=1109291529

Based on the above analysis, we think there are a few important questions to be discussed further as a larger group: 
1. How should we handle the genes that is the NCBI (and originally in our public DB) but not in HGNC? (1260 genes)
   - considering: oncoKB, panel, user query, # of studies impacted
   - should we maintain add these genes to HGNC table 
   - how to maintain these in the future
2. Do we want to include the HGNC alias table as well? (491 genes)
3. Handle the outdated symbol/entrezID (310 genes)
    - script to update the old symbols 
    - maintain a mapping for old vs. new symbols and run periodically 
4. Withdrawn symbols (9 genes) 
5. Merge `CDKN2AP14ARF` and `CDKN2AP16INK4A` into `CDKN2A`
    - https://github.com/cBioPortal/datahub/issues/1274
