### ISSUE TITLE
meso_tcga: errors in data_mutation_extended

### ISSUE THREAD

**Issue by oplantalech** [cBioPortal/datahub#57]
The new maf file contains some errors:
<img width="1098" alt="captura de pantalla 2017-06-23 a les 16 53 10" src="https://user-images.githubusercontent.com/20278013/27487624-8cf4c3a4-5834-11e7-90af-218c90a01748.png">
@zheins

**Comment by pieterlukasse** [comment]
@ritikakundra will discuss with backend team

**Comment by pieterlukasse** [comment]
@ritikakundra @yichaoS in which PR can we expect this fix? Could you please refer to it here (or refer to this issue in the PR)?

**Comment by dionnezaal** [comment]
Fixed in PR #164.
