### ISSUE TITLE
MSK CRC study has incomplete MSI data

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/datahub#570]
MSI status is not available for 305 samples, when it should have been available for all.

http://www.cbioportal.org/study?id=crc_msk_2017

![image](https://user-images.githubusercontent.com/11892704/52008180-1b1f9c80-249e-11e9-9f7a-951ca1c3cd65.png)

Also, time to metastasis seems to be encoded as a string?

![image](https://user-images.githubusercontent.com/11892704/52008232-37233e00-249e-11e9-8735-5feb0b28ab59.png)

**Comment by ritikakundra** [comment]
@schultzn Confirmed with Walid: MSI Status is the Pathology MSI Status (Clinical) that didn't have IHC for all of them. The molecular subtype is documented for all:
![screen shot 2019-01-30 at 3 02 12 pm](https://user-images.githubusercontent.com/12007862/52009094-0f34da00-24a0-11e9-8b2f-de3a156cce34.png)
