### ISSUE TITLE
clinical data issues: Sex

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#583]
[study view of all studies](https://www.cbioportal.org/study?id=5c6344e4e4b0f6ce58b5e508)

- [x] Both sex and gender are used in different studies
- [x] Only `Male` and `Female` for values
- [ ] It may be useful to add sex to women's cancer (breast, ovarian, breast, anything else) and men's cancer (prostate, testicular, and penile).

![image](https://user-images.githubusercontent.com/840895/52672535-20440900-2eec-11e9-8761-04031220e328.png)

**Comment by rmadupuri** [comment]
@jjgao we fixed it! But I will make sure of the point 3
![Screen Shot 2019-06-14 at 5 05 08 PM](https://user-images.githubusercontent.com/34350829/59538144-c7e73d00-8ec6-11e9-8c27-e44527fa347b.png)

**Comment by rmadupuri** [comment]
@jjgao this is fixed. No Person_Gender is used. I will confirm the third point though. 
![Screen Shot 2019-06-14 at 5 05 08 PM](https://user-images.githubusercontent.com/34350829/59539009-adfb2980-8ec9-11e9-8964-0574ba441baf.png)

**Comment by jjgao** [comment]
Great 👍  Thank you @rmadupuri!
