### ISSUE TITLE
incorrect case_rppa.txt in hnsc_tcga 

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#586]
The [case_rppa.txt](https://github.com/cBioPortal/datahub/blob/master/public/hnsc_tcga/case_lists/cases_rppa.txt) in hnsc_tcga has 357 samples, but in [data_rppa.txt](https://media.githubusercontent.com/media/cBioPortal/datahub/master/public/hnsc_tcga/data_rppa.txt
), there are only 212 samples. 

@cBioPortal/curation

**Comment by yichaoS** [comment]
![screen shot 2019-02-14 at 11 57 56 am](https://user-images.githubusercontent.com/5973438/52803276-be041900-304f-11e9-9a93-737efa45ac06.png)
