### ISSUE TITLE
missing MYC expression values from TCGA provisional prostate adenocarcinoma dataset mRNA matrix downloaded

### ISSUE THREAD

**Issue by khzhu** [cBioPortal/datahub#597]
Reported by [a user](https://groups.google.com/d/msg/cbioportal/0HkH6zstJqk/hAmldcVXBQAJ)

z-scores are missing for all samples except one in prad_tcga

> Thanks for your e-mail. I have been able to extract the files. However, looking at the RNA Seq Z score file, there are no values for Myc except for 1 patient. I do not understand this when a graph can be drawn to show the correlation of BRF1 and MYC in TCGA provisional prostate adenocarcinoma dataset.
What I want to be able to do is calculate the p value for the Pearson correlation - although a pearson correlation coefficient is stated on the co-expression graph, the p value stated is for the Spearman correlation.
Does this make sense??? To be able to do the calculation, I need to be able to download the MYC expression values which I think should be there if a graph can be drawn???

**Comment by ritikakundra** [comment]
@rmadupuri: Zscore regeneration

**Comment by rmadupuri** [comment]
MYC expression zscores are restored. 
<img width="1202" alt="prad_MYC" src="https://user-images.githubusercontent.com/34350829/63575874-1533fa80-c559-11e9-8675-ca20f1b0201b.png">
