### ISSUE TITLE
Add CPTAC data 

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/datahub#6]
Would be nice to have the CPTAC data in the next version (Ovarian, breast, and colorectal?)

Notify: @zheins

**Comment by pieterlukasse** [comment]
@n1zea144 @zheins any news on this one?

**Comment by sandertan** [comment]
Mass spec data files have been added for all CPTAC assayed TCGA studies (`brca, coadread and ov`) in https://github.com/cBioPortal/datahub/pull/31. Issues with `coadread` and `ov` are listed in https://github.com/cBioPortal/datahub/issues/32
