### ISSUE TITLE
Chromosome (field 5) NA for >50% of COADREAD mutation data

### ISSUE THREAD

**Issue by khunn** [cBioPortal/datahub#60]
Hi there,

it seems that for >50% of all mutations in coadread/tcga/data_mutations_extended.txt field 5 (chromosome) seems to be NA.  To be more precise, only chromosomes >=10 are reported. 

```
$ cut -f5 data_mutations_extended.txt | sort | uniq -c
   3410 10
   4743 11
   4832 12
   1872 13
   2361 14
   2723 15
   2715 16
   3961 17
   1480 18
   5046 19
   1990 20
    821 21
   1288 22
      1 Chromosome
  47344 NA
      1 #version 2.4

```

I did a quick check on a couple of other indications, and there it seems to happen too.

Thanks,
Markus

**Comment by pieterlukasse** [comment]
@ritikakundra can you check the cause?

**Comment by ritikakundra** [comment]
@n1zea144 reannotated the MAF for this, it seems to have been fixed there. I will update the datahub with the new maf

**Comment by ritikakundra** [comment]
datahub updated

**Comment by angelicaochoa** [comment]
@pieterlukasse @khunn this is resolved now.

**Comment by pieterlukasse** [comment]
@angelicaochoa thanks. Which PR solved this one?
