### ISSUE TITLE
MSK cholangio study says "0 samples"

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/datahub#616]
![image](https://user-images.githubusercontent.com/10508276/53115977-84cb1d80-3515-11e9-9933-bce6b37ea7bc.png)

If I go to study view or run a query, the data is all there. But for some reason the query interface doesn't know that.

**Comment by ritikakundra** [comment]
Data was fine, reimport fixed it:
![screen shot 2019-02-21 at 5 37 44 pm](https://user-images.githubusercontent.com/12007862/53206614-6a6d6e80-35ff-11e9-8715-69a1c6ceb1d3.png)
