### ISSUE TITLE
Validator Issue: Change fusion DNA and RNA Support to DNA_support & RNA_support

### ISSUE THREAD

**Issue by ritikakundra** [cBioPortal/datahub#62]
To make headers consistent, can we make the header in fusion file to:
DNA_support & RNA_support?

**Comment by pieterlukasse** [comment]
I vote yes.

**Comment by pieterlukasse** [comment]
Decisions: @ritikakundra will fix studies
@sandertan will change the validator/importer

**Comment by sandertan** [comment]
Merged.

**Comment by pieterlukasse** [comment]
Has @ritikakundra updated the studies in datahub?

**Comment by yichaoS** [comment]
@ritikakundra  Doing the cleaning according to [attr_dna_rna_support.xlsx](https://github.com/cBioPortal/datahub/files/1297045/attr_dna_rna_support.xlsx)

**Comment by pieterlukasse** [comment]
@yichaoS thanks for sharing the detailed log of the changes :+1: 
Let's close this one when all is updated here in datahub.

**Comment by pieterlukasse** [comment]
@yichaoS is working on updating this in datahub. In progress.
