### ISSUE TITLE
Studies lacks information for matched normals

### ISSUE THREAD

**Issue by yichaoS** [cBioPortal/datahub#623]
1. stad_tcga_pub
No mapping found for stad_tcga_pub in the original publication (https://www.nature.com/articles/nature13480), to indicate which samples have matched normals. 

2. skcm_yale

**Comment by jjgao** [comment]
All TCGA samples should have matched normals. @schultzn, please correct me if there are exceptions.

**Comment by ritikakundra** [comment]
@yichaoS For skcm_yale, in the supplemental PDF, table 2 has the matched status. That can be used

**Comment by yichaoS** [comment]
@ritikakundra Resolved that one. Thanks so much!

**Comment by schultzn** [comment]
I am not aware of any exceptions.
