### ISSUE TITLE
Add SOMATIC_STATUS as a clinical attribute

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#626]
@rmadupuri told me that you are curating whether a study has matched normals. I thought it would be very useful to save that information as a clinical attribute, just like we do for mskimpact study.

cc'ing @schultzn

**Comment by ritikakundra** [comment]
@jjgao I have been using this HAS_MATCHED_NORMAL, would this work?

**Comment by jjgao** [comment]
@ritikakundra that would work, but maybe we should use the same for mskimpact?

**Comment by yichaoS** [comment]
Merged issue #623 into this one: 

Remaining issues with #623 
- stad_tcga_pub
No mapping found for stad_tcga_pub in the original publication (https://www.nature.com/articles/nature13480), to indicate which samples have matched normals.

Also as @jjgao and @schultzn confirmed, we should add to all TCGA studies the matched normal column. All samples there have matched normals.

**Comment by yichaoS** [comment]
We are tackling this issue as part of the TMB calculation effort. 
Also this issue was related: https://github.com/cBioPortal/datahub/issues/623
