### ISSUE TITLE
Seem to be missing from datahub: gbc_msk_2018 and sarc_tcga_pub

### ISSUE THREAD

**Issue by inodb** [cBioPortal/datahub#629]
As reported by: https://groups.google.com/forum/#!topic/cbioportal/fIQbwYiH6zo

Please keep this checklist for curation of a new study.

- [x] [create a issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [ ] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [ ] Document the curation process, e.g. how and by whom the data was transformed
- [ ] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [ ] Create a pull request to datahub once the data is curated
- [ ] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

**Comment by jjgao** [comment]
Don't we have a script to detect missing studies?

**Comment by yichaoS** [comment]
@jjgao @inodb Yes we have a script for detecting that. It runs once a week. Here is the report: https://circleci.com/gh/cBioPortal/datahub/1484. 

It did say there are 3 studies missing now (see screenshot). ![screen shot 2019-02-28 at 3 03 23 pm](https://user-images.githubusercontent.com/5973438/53594957-0bad7500-3b6a-11e9-9d5f-d62930828863.png)

Sometimes there's a little delay adding data to datahub, when there's urgency to upload the study to portal, but the format is not perfect yet for datahub. Will try to eliminate this kind of situation. 

The study will be added by the end of tomorrow.

**Comment by jjgao** [comment]
@yichaoS it would be good to create an issue when we see missing studies by the script. I am wondering if we can automate that?

**Comment by yichaoS** [comment]
@jjgao I'm not sure if a github issue would work out the best, because if we don't resolve it in a week's time we would have issues referring to the same problems. How about a weekly email notification with all the errors? Failed studies, missing studies, etc. 

I would add this as a discussion item for our next Datahub call.

**Comment by jjgao** [comment]
@yichaoS a weekly email sounds good. But I think issues should be also logged on datahub -- maybe manually?

**Comment by yichaoS** [comment]
@jjgao Sure will do @inodb Studies added.
