### ISSUE TITLE
Prioritize clinical attributes for TCGA Provisional studies

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/datahub#633]
Show for all TCGA studies:

Cancer Type Detailed
Overall Survival
Disease Free Survival
Mutation Count vs Fraction of Genome Altered
Mutated Genes
CNA Genes
Number of Samples Per Patient
Sex
Mutation Count
Fraction Genome Altered
Diagnosis Age
Sample Type
Tissue Source Site
Overall Survival Status
Overall Survival (Months)
Disease Free Status
Disease Free (Months)
Tissue Source Site
Race Category
Surgical Margin Resection Status
Year Cancer Initial Diagnosis
American Joint Committee on Cancer Metastasis Stage Code
Neoplasm Disease Lymph Node Stage American Joint Committee on Cancer Code
Neoplasm Histologic Grade

Do not show for any TCGA studies:

Days to Last Followup
Disease Free Survival
Is FFPE
Sample type id
Birth from Initial Pathologic Diagnosis Date
Last Alive Less Initial Pathologic Diagnosis
Longest Dimension

Show for PRAD_TCGA:
Gleason pattern primary
Gleason pattern secondary
Days to PSA
Biochemical Recurrence Indicator
Days to biochemical recurrence first

Show for THCA:
Extrathyroidal Extension

Show for KIRC_TCGA:
Primary Tumor Laterality

Show for LUAD_TCGA:
Patient Smoking History Category

Show for ESCA:
Esophageal tumor involvement site
Barretts esophagus
Alcohol History Documented

Show for BRCA:
ER Status By IHC
PR status by ihc
IHC-HER2
Menopause Status

Other notes:
"Days to PSA" needs to be continuous data

The attributes selected for the individuals are not complete. We can revisit this later and potentially add additional attributes.

**Comment by jjgao** [comment]
How about pancan studies?
