### ISSUE TITLE
Issues with RNA-seq data of nepc_wcm_2016

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#64]
1. The RNA-seq data does not look like z-score profiles.

![image](https://user-images.githubusercontent.com/840895/28422895-61f4eaf4-6d37-11e7-9830-0946eb1049ab.png)

2. There is no case list for the RNA-seq profile

![image](https://user-images.githubusercontent.com/840895/28422858-5190c3ae-6d37-11e7-8adf-8768b7f68d94.png)

**Comment by rmadupuri** [comment]
Fixed / converted to continuous type in https://github.com/cBioPortal/datahub/issues/117 and added zscores.
