### ISSUE TITLE
sarc_tcga_pub

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#642]
- [x] Should `AMP 12q15 *` be numerical?
- [x] `Cancer DNA Fraction` should be numerical
- [x] `FNCLCC Grade` should be string (don't we have a vocabulary for grade for tcga?)
- [x] Change `Relapse Free Status (Months)` to `DFS_MONTHS` and `Relapse Free Status` to `DFS_STATUS`
- [x] `Mitotic Rate` should be numerical
- [x] `Months to Distant Recurrence` should be numerical
- [x] `PARADIGM` cluster should be string
- [x] `Ploidy` should be numerical
- [x] `Subclone Genomic Fraction` should be numerical
- [x] `Tumor Size` should be numerical
- [ ] Is RPPA data available?
- [ ] Is methylation data available

**Comment by ritikakundra** [comment]
@jj: FNCLCC Grade should be string (don't we have a vocabulary for grade for tcga?): For this FNLCC grading seems to be different than the other AJCC grade we see in TCGA

**Comment by ritikakundra** [comment]
Changed Datatype for:
PARADIGM_CLUSTER
ICLUSTER
PLOIDY
GENOME_DOUBLINGS
GENOME_DOUBLINGS
CANCER_DNA_FRACTION
TUMOR_SIZE
AVG_CN_12Q13_15	
AMP_12Q15_DDIT3	
AMP_12Q15_CDK4	
AMP_12Q15_HMGA2	
AMP_12Q15_MDM2
AMP_12Q15_FRS2
CN_CLUSTER
MRNA_EXPRESSION_CLUSTER
MIRNA_CLUSTER
MITOTIC_RATE
MONTHS_TO_DISTANT_RECURRENCE
