### ISSUE TITLE
missing case lists for aml_target_2018_pub

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#658]
Missing case lists of _seq, _cna, _cnaseq.

https://www.cbioportal.org/study?id=aml_target_2018_pub

![image](https://user-images.githubusercontent.com/840895/54484044-b4c7c100-4834-11e9-8e14-ca59eafbae45.png)

**Comment by yichaoS** [comment]
@jjgao the case lists are in the data files... and in MSK portal. A reimport to public portal would fix it. Marked to reimporting tonight.

**Comment by yichaoS** [comment]
![Screen Shot 2019-03-18 at 2 29 07 PM](https://user-images.githubusercontent.com/5973438/54555867-f9b33b00-498d-11e9-88a9-d7ae6befa06b.png)

**Comment by yichaoS** [comment]
@jjgao after importing, this issue fixed in public portal now (please see screenshot below)
![Screen Shot 2019-03-19 at 12 17 12 PM](https://user-images.githubusercontent.com/5973438/54622933-eca35400-4a40-11e9-8722-7830d4462262.png)
