### ISSUE TITLE
stad_tcga_pub has 76 extra samples

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/datahub#660]
The publication included 295 samples, and the study here includes 295 samples with clinical data and then an additional 76 samples that have no associated data (except they do somehow have values for fraction genome altered).

Can those 76 samples be removed?

![image](https://user-images.githubusercontent.com/10508276/54612505-75b18f80-4a2f-11e9-94f3-e55cbf83b792.png)

**Comment by yichaoS** [comment]
<img width="1197" alt="Screen Shot 2019-03-20 at 10 51 56 AM" src="https://user-images.githubusercontent.com/5973438/54694247-5170b400-4afe-11e9-8d84-801e51176595.png">
<img width="1200" alt="Screen Shot 2019-03-20 at 10 52 45 AM" src="https://user-images.githubusercontent.com/5973438/54694248-5170b400-4afe-11e9-80ef-058637c2bd11.png">
