### ISSUE TITLE
ucec_tcga_pub and coadread_tcga_pub have extra samples

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/datahub#669]
coadread_tcga_pub has 585 samples but if you link out to the publication, it says 276 samples.

ucec_tcga_pub description says 373 samples but the study has 500.

![image](https://user-images.githubusercontent.com/10508276/54830009-0685a680-4c8e-11e9-9589-4504e0ed3639.png)

This is just like issue reported in #660 which worries me that this is a widespread problem. In addition to fixing these 2 studies, please identify any other studies where this is happening and fix those as well.

**Comment by tmazor** [comment]
I'm looking at lihc_tcga today and it looks like this study has 63 samples with no clinical or genomic data (select Sex = NA to find these samples)

**Comment by tmazor** [comment]
@yichaoS @ritikakundra @rmadupuri do you have any update on this one?

**Comment by ritikakundra** [comment]
@tmazor Am in process of working on it. Will have an update soon

**Comment by ritikakundra** [comment]
@tmazor for tcga pub studies samples are mostly in segment files but we are going to remove them to be in sync with the paper.

For lihc_tcga, I see these samples with NA clinical/genomic data in path and tissue reports. I think we should remove those too but I will quickly discuss this with our group.
