### ISSUE TITLE
metabric rna - is it sequencing or microarray or both?

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/datahub#695]
The Datasets page shows that the METABRIC study has 1904 samples with RNA-seq and 1904 samples with mRNA microarray.

However if I try to query the study, only microarray appears in the genomic profiles list.

Is there RNA-seq data?

**Comment by yichaoS** [comment]
@tmazo @ritikakundra  There's only microarray expression data. The dataset page is now updated.

**Comment by romagnolid** [comment]
Hello @yichaoS, any plan to make RNA-seq data available?
