### ISSUE TITLE
zscore file missing for paad_qcmg_uq_2016

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#711]
https://www.cbioportal.org/study/summary?id=paad_qcmg_uq_2016

**Comment by yichaoS** [comment]
fixed
![Screen Shot 2019-10-18 at 3 00 12 PM](https://user-images.githubusercontent.com/5973438/67120717-d9638d00-f1b7-11e9-9a46-8e78e2ce0203.png)
![Screen Shot 2019-10-18 at 2 59 44 PM](https://user-images.githubusercontent.com/5973438/67120718-d9638d00-f1b7-11e9-9567-cdf3cae11069.png)
