### ISSUE TITLE
Timeline file for events like status fails on validation

### ISSUE THREAD

**Issue by ritikakundra** [cBioPortal/datahub#73]
Event types like status, specimen, surgery etc which are a single day event don't have a stop date. The validator fails when it does not find a stop date for any timeline file. Stop date is only for durations like treatments. Others could or could not have a stop date.Therefore maybe keep it as a warning rather than an error

**Comment by ritikakundra** [comment]
![screen shot 2017-08-14 at 1 40 19 pm](https://user-images.githubusercontent.com/12007862/29283758-12e1255e-80f6-11e7-9222-c0eb7c69e17d.png)

**Comment by pieterlukasse** [comment]
hi @ritikakundra, have you tried adding an empty column with STOP_DATE as column header? According to [documentation](https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md#data-file-9) the column is mandatory, but values can be empty: 

>  "...If the event occurs at a time point (e.g. a Lab_test, Imaging, ...) the STOP_DATE is still mandatory, but the values should be blanks."

**Comment by pieterlukasse** [comment]
agreed to close given the column can be empty
