### ISSUE TITLE
TRACERx - McGranahan et al. Clonal neoantigens elicit T cell immunoreactivity and sensitivity to immune checkpoint blockade. Science. 2016.

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#733]
https://www.ncbi.nlm.nih.gov/pubmed/26940869

- [ ] [create a issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [ ] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [ ] Document the curation process, e.g. how and by whom the data was transformed
- [ ] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [ ] Create a pull request to datahub once the data is curated
- [ ] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

**Comment by yichaoS** [comment]
@jjgao:  @sbabyanusha presented this paper at our journal club yesterday and she identified that there's no MAF provided along with publication.

**Comment by jjgao** [comment]
@yichaoS @sbabyanusha @ritikakundra can we try to contact the author?

**Comment by yichaoS** [comment]
@jjgao We were about to email the author, then noticed that, seems like the paper is using the same 34 patient set (@sbabyanusha doubled checked the list in clinical supplemental) and re-using sequencing data for analysis from a previous published study: https://science.sciencemag.org/content/348/6230/124. The supplemental data seems to have the complete sequencing data with coordinates&allele. We will try to curate this paper next (or soon) scrum. @ritikakundra @sbabyanusha @rmadupuri

**Comment by yichaoS** [comment]
@jjgao me and @sbabyanusha took another closer look at the study, and realized there are 4 parts of the cohort
- Discovery cohort: 
   - 7 patients: mutation data is in `European Genome-phenome Archive`. We're going to email the 
      author to ask for the MAF. 
- Validation cohorts:
   - 34 patients: already in nsclc_mskcc_2015 (ref 2)
   - 64 patients: skcm_mskcc_2014 (ref 4)
   - 110 patients: skcm_dfci_2015 (ref 17)

**Comment by jjgao** [comment]
Thanks @yichaoS @BabyASatravada . I didn't realize they only have 7 new patients. In that case, I should deprioritize this one if it's hard to get the data.

**Comment by yichaoS** [comment]
Emailed the author for the MAF of the 7 primary NSCLC patients.

**Comment by jjgao** [comment]
Sicne it's only 7 patients, maybe we should just close this ticket, esp if the author hasn't responded..

**Comment by yichaoS** [comment]
Replied by Charles Swanton (charles.swanton@crick.ac.uk) on 8/25/2020:
```
I am sure we can provide this information asap
Nicky(nicholas.mcgranahan@crick.ac.uk) and Mariam(m.jamal-hanjani@ucl.ac.uk) are cc’ed who will know where these data are
```

Followed up on 6/1/2021

**Comment by sbabyanusha** [comment]
This issue is being closed as we couldn't get a response from the author.
