### ISSUE TITLE
Rizvi, et al. Mutational landscape determines sensitivity to PD-1 blockade in non-small cell lung cancer. Science 2015

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#738]
https://www.ncbi.nlm.nih.gov/pubmed/25765070

- [x] [create a issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [x] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [x] Document the curation process, e.g. how and by whom the data was transformed
- [x] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [x] Create a pull request to datahub once the data is curated
- [ ] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

**Comment by jjgao** [comment]
already in private portal, we should change the name from lung_science_2015 to lung_mskcc_2015

**Comment by yichaoS** [comment]
Study published at: https://www.cbioportal.org/study/summary?id=nsclc_mskcc_2015#summary
Issue closing.
