### ISSUE TITLE
Miao et al. Genomic correlates of response to immune checkpoint therapies in clear cell renal cell carcinoma. Science. 2018

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#739]
https://www.ncbi.nlm.nih.gov/pubmed/29301960

- [x] [create a issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [x] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [x] Document the curation process, e.g. how and by whom the data was transformed
- [x] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [x] Create a pull request to datahub once the data is curated
- [ ] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

**Comment by yichaoS** [comment]
Curation List 

- Mutation Data: 
Table S1 Tab 1C (discovery cohort WES)
Table S1 Tab 1F (discovery cohort PBRM1)

- Clinical Data:
Table S1 Tab 1B (discovery cohort Clin)
Table S2 Tab B (validation cohort Clin)

**Comment by yichaoS** [comment]
@jjgao Public portal link: https://www.cbioportal.org/study/summary?id=ccrcc_dfci_2019#summary
