### ISSUE TITLE
msk_impact_2017

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/datahub#74]
# Requested changes
### meta_cna.txt
```profile_name: MSK-IMPACT Clinical Sequencing Cohort (MSKCC)```
to
```profile_name: Putative copy-number alterations```

Replace value in `profile_name` and `profile_description` with correct value. (see #65)

### meta_fusions.txt
```stable_id: msk_impact_2017_mutations```
to
```stable_id: fusion```

Add: `data_filename: data_fusions.txt`

### data_mutations_extended.txt
Line 7058: `pp.C189_A190delinsWH` to `p.C189_A190delinsWH`
Line 13878: `p. L482_E483delinsF*` to `p.L482_E483delinsF*`

### meta_study.txt
Add: `add_global_case_list: true`

### data_fusions.txt
Replace `0` for Entrez_Gene_Id by with real values

### data_mutations.txt
Replace `pp.C189_A190delinsWH` to `p.C189_A190delinsWH`

### Gene panels
@zheins mentioned there is gene panel data for msk_impact, but it's currently not included in the files.

**Comment by ritikakundra** [comment]
@sandertan All of these changes have been made, but there is a request for another update so I have to push that with the new changes

**Comment by jjgao** [comment]
and this one too: cBioPortal/cbioportal#3017
