### ISSUE TITLE
Amaria et al. Neoadjuvant immune checkpoint blockade in high-risk resectable melanoma. Nat Med. 2018

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#740]
https://www.ncbi.nlm.nih.gov/pubmed/30297909

- [ ] [create a issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [ ] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [ ] Document the curation process, e.g. how and by whom the data was transformed
- [ ] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [ ] Create a pull request to datahub once the data is curated
- [ ] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

**Comment by yichaoS** [comment]
Data Availability: 
- Whole-exome sequencing, T cell receptor sequencing and Nanostring digital spatial profiling data are available from the European Genome-phenome Archive under accession number EGAS00001003178.
- Supplemental data: patient ID (3 samples each: Baseline, On-treatment, Baseline to on-treatment), treatment, responses, sample collecting time point

**Comment by yichaoS** [comment]
@jjgao Could you please let us know if there's any way for us to access the European Genome-phenome Archive and download the sequencing data from there? If not, I'll send an email to the author.

**Comment by jjgao** [comment]
@yichaoS please contact them. You will need to contact them to get EGA access too.

**Comment by sbabyanusha** [comment]
This issue is being closed as we couldn't get a response from the author.
