### ISSUE TITLE
KRAS AMP missing in `paad_tcga_pan_can_atlas_2018` ?

### ISSUE THREAD

**Issue by inodb** [cBioPortal/datahub#742]
In the latest version of `paad_tcga_pan_can_atlas_2018` it seems that a deep deletion in KRAS has appeared and several amplifications have been removed:

See `reference/profiled_in_tracks_in_a_combined_study_element_chrome_1600x1000.png` in

https://38105-66571349-gh.circle-artifacts.com/0/imageCompare.html

Seems like this might be incorrect?

**Comment by jjgao** [comment]
@cBioPortal/curation @sheridancbio was there a reimport of the study?

**Comment by ritikakundra** [comment]
@inodb The current version in the portal has no deep del for KRAS in paad pancan:
![Screen Shot 2019-05-31 at 4 56 19 PM](https://user-images.githubusercontent.com/12007862/58734276-00feb800-83c5-11e9-8374-e01622848dda.png)

**Comment by inodb** [comment]
@ritikakundra 	this has been fixed after re-import

**Comment by jjgao** [comment]
Wondering what went wrong? Could it affect other studies?

**Comment by inodb** [comment]
@jjgao not clear exactly what went wrong but the issues stemmed from having two databases. One internal public one and one external in AWS. They weren't in a consistent state. Some studies hadn't been imported in a while. We have now removed the internal one, so that part is resolved. It's possible that multiple studies are affected by this, we should prolly do a completely clean data import starting from the seed database at some point
