### ISSUE TITLE
Lee et al. Tracing Oncogene Rearrangements in the Mutational History of Lung Adenocarcinoma. Cell 2019.

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#743]
https://www.cell.com/cell/fulltext/S0092-8674(19)30511-2#%20

- [ ] [create a issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [ ] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [ ] Document the curation process, e.g. how and by whom the data was transformed
- [ ] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [ ] Create a pull request to datahub once the data is curated
- [ ] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

**Comment by rmadupuri** [comment]
**Cohort Stats:** 138 cases - 49 newly sequenced and 89 publicly available cases (also includes a few TCGA Lung Adenocarcinoma cases) - data analyzed in a unified pipeline 

**Data Availability:** 
Clinical - Table S1, S5, S7 
SV's, MAF (in VCF format), RNA-seq, pathology findings, mutational signatures are available here: http://genome.kaist.ac.kr/

**Issue:** Data in http://genome.kaist.ac.kr/ can only be download per sample/gene individually and MAF is in VCF format. 

**Status:** Emailed author (May 26, 2021) if they could share the complete genomic data per profile.

**Comment by sbabyanusha** [comment]
This issue is being closed as we couldn't get a response from the author.
