### ISSUE TITLE
ovarian_tcga_nature_2011 lost an AMP and deep deletion in BRCA1

### ISSUE THREAD

**Issue by inodb** [cBioPortal/datahub#744]
- a DEL in `TCGA-31-1959`
- an AMP in `TCGA-23-1122`

have gone missing

this might be related to #742 as well where AMPs where lost and a DEL appeared

before
<img width="986" alt="Screen Shot 2019-05-31 at 5 07 54 PM" src="https://user-images.githubusercontent.com/1334004/58734974-ff35f400-83c6-11e9-92da-24929c65a290.png">

now
<img width="754" alt="Screen Shot 2019-05-31 at 5 07 50 PM" src="https://user-images.githubusercontent.com/1334004/58734984-06f59880-83c7-11e9-8e8d-8b63c3880029.png">

**Comment by ritikakundra** [comment]
@inodb I still see it in the public portal
![Screen Shot 2019-05-31 at 5 13 49 PM](https://user-images.githubusercontent.com/12007862/58735100-6784d580-83c7-11e9-9573-b7d1f537cd85.png)
:

**Comment by ritikakundra** [comment]
@inodb @sheridancbio Did the reimport to beta portal help?

**Comment by inodb** [comment]
@ritikakundra re-importing didn't work. Some issue with the import process, Rob is looking into it

**Comment by inodb** [comment]
@ritikakundra looks like the import succeeded now and amp and deep deletions are showing up again. Thanks for your help!

**Comment by pieterlukasse** [comment]
@schultzn , @inodb: did the reimport also solve it for BLCA? See https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/cbioportal/6qS93JtOoWs/NPxGh3mSBQAJ

**Comment by schultzn** [comment]
Yes, it looks like that got fixed!
