### ISSUE TITLE
Bertucci et al. Genomic characterization of metastatic breast cancers. Nature 2019

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#746]
https://www.ncbi.nlm.nih.gov/pubmed/31118521

- [ ] [create a issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [ ] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [ ] Document the curation process, e.g. how and by whom the data was transformed
- [ ] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [ ] Create a pull request to datahub once the data is curated
- [ ] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

**Comment by jjgao** [comment]
@cBioPortal/curation please prioritize this study. It will likely be one of the most frequently used studies.

**Comment by yichaoS** [comment]
@jjgao We studied this paper in our journal club. However the data didn't come with the publication, instead we need to download the data from Europe Genome-phenome Archive (see screenshot). I wrote them an email to ask for access permission (can not just register an account by myself, have to email for application), but haven't get an response from them. 
![Screen Shot 2019-08-07 at 4 09 30 PM](https://user-images.githubusercontent.com/5973438/62654501-eea57b00-b92d-11e9-8aab-3623ea9cf2e6.png)

**Comment by jjgao** [comment]
@yichaoS @ritikakundra could you try to contact the author and see if you can get the high-level data, e.g. vcf/maf. We don't really need the low level BAM files.

**Comment by jjgao** [comment]
Have we contacted the authors?

**Comment by ritikakundra** [comment]
@jjgao Authors emailed back saying, due to GDPR issues, they won’t be able to upload their data to cBioPortal
