### ISSUE TITLE
Include RNA-seq data in MET500 study

### ISSUE THREAD

**Issue by yichaoS** [cBioPortal/datahub#761]
public portal link: 
https://www.cbioportal.org/study/summary?id=metastatic_solid_tumors_mich_2017

**Comment by sbabyanusha** [comment]
@yichaoS I have investigated on this and the data is not reported in the supplementary files but available in Xena browser. The paper says that the reads are aligned to GRCh38 build. I will try emailing the author to know whether they can provide the data aligned to GRCh37 build if possible.

**Comment by jjgao** [comment]
@sbabyanusha For expression data, I don't think we need to worry about genome build since we are not storing any genomic locations.
