### ISSUE TITLE
Archive for study hnsc_tcga_pub wrong Metadata

### ISSUE THREAD

**Issue by guv** [cBioPortal/datahub#78]
The archive for the study hnsc_tcga_pub contains wrong metadata.
The file meta_RNA_Seq_v2_expression_median.txt has the wrong "datatype" "Z-SCORE" instead of the expected "CONTINUOUS".

The file meta_RNA_Seq_v2_expression_median.txt contains:
> cancer_study_identifier: hnsc_tcga_pub
genetic_alteration_type: MRNA_EXPRESSION
datatype: Z-SCORE
stable_id: hnsc_tcga_pub_rna_seq_v2_mrna
show_profile_in_analysis_tab: false
profile_description: Expression levels for 20532 genes in 303 hnsc cases (RNA Seq V2 RSEM).
profile_name: mRNA expression (RNA Seq V2 RSEM)
data_filename: data_RNA_Seq_v2_expression_median.txt

**Comment by pieterlukasse** [comment]
@angelicaochoa was this also fixed in one of the recent PRs?

**Comment by pieterlukasse** [comment]
Assigning to @ritikakundra

**Comment by ritikakundra** [comment]
Updated this 
https://github.com/cBioPortal/datahub/pull/108
