### ISSUE TITLE
missing cna profile in the gene matrix file of egc_msk_2017

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#780]
Gene_matrix file of egc_msk_2017 only specified for mutations. CNA profile should be added.

https://github.com/cBioPortal/datahub/blob/master/public/egc_msk_2017/data_gene_matrix.txt

Please check other gene_matrix files (esp, msk studies) and see if they have the same problem.

**Comment by ritikakundra** [comment]
@jjgao Ya these older studies don't have the CNA profile. I can use Maggie's help with this. We will prioritize it.

**Comment by ritikakundra** [comment]
Added
