### ISSUE TITLE
Missing zscores for ov_tcga and brca_tcga for CCND1

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#781]
[A user](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/cbioportal/-NJqHPnZ-vk/ggPu0FyPDgAJ) reported:

"For both TCGA Ovarian (Provisional) and TCGA BRCA (Provisional), it appears that gene expression z-scores (from RNA-seq v2) are missing, for the gene CCND1. From raw data downloaded from TCGA, expression levels for this gene should be available. Can you tell me if there is some reason why the z-scores for this gene are unavailable (CCND1 is reported as the official symbol, so aliases such as BCL1 and PRAD1 do not work)."

I was able to confirm it. @ritikakundra @yichaoS would you please look into it? We should find out the reason to understand whether this affects other genes or studies.

**Comment by ritikakundra** [comment]
@jjgao We did notice that the java Z-score script does indeed drop rows for certain genes (@yichaoS can comment further on this). @rmadupuri  and @yichaoS have completed the development of the new python-based Z-Score script which is not dependent on CNA profile. Maybe this will be a good test run to compute the Z-score with the new script and see if we can salvage CCND1 expression?

**Comment by yichaoS** [comment]
@jjgao @ritikakundra When testing this new script, we discovered the old java code for generating zscores is really buggy. It drops many rows, also swaps out entrez IDs incorrectly. It is very likely this missing gene is caused by this. Now the new script is ready, thanks to @rmadupuri we would address this next scrum with the new script.

**Comment by jjgao** [comment]
@yichaoS sounds good. It may be a good idea to regenerate all zscores.
