### ISSUE TITLE
Only 1 sample does not appear in clinical_sample

### ISSUE THREAD

**Issue by anthony-cros** [cBioPortal/datahub#793]
Sample `342599` is the only one (out of 77K others) not to appear in `clinical_sample` table (suscipicious)

**Comment by jjgao** [comment]
@ritikakundra are we planning to do anything about this? Maybe query the database and see if the problem still exists?

**Comment by rmadupuri** [comment]
@anthony-cros this problem doesn't exist in the database. Looks like its been fixed. Closing the issue.
