### ISSUE TITLE
TCGA Skin Cutaneous Melanoma Provisional Dataset - missing genes

### ISSUE THREAD

**Issue by ritikakundra** [cBioPortal/datahub#809]
As reported by a user:
https://groups.google.com/forum/#!topic/cbioportal/MK1CzBTt_n8

Need to run the new Z-Score script on this?

**Comment by rmadupuri** [comment]
Fixed! 
<img width="1181" alt="skcm_HLA" src="https://user-images.githubusercontent.com/34350829/63575653-99d24900-c558-11e9-9c40-8d7af2be9e67.png">
