### ISSUE TITLE
IPOP data

### ISSUE THREAD

**Issue by ritikakundra** [cBioPortal/datahub#81]
- [ ] There is no RNA-Seq count for study 4 
- [ ] survival plot is not shown for the 2 new studies
- [ ] Priority

**Comment by jjgao** [comment]
are they public datasets?

**Comment by ritikakundra** [comment]
@jjgao Yes, they all have an associated pmid from David

**Comment by jjgao** [comment]
If they are not on the public portal. I would move this issue to some other places.
