### ISSUE TITLE
CCLE - change treatment response data names

### ISSUE THREAD

**Issue by schultzn** [cBioPortal/datahub#817]
Drug treatment AUC --> Treatment response: AUC
Drug treatment z-score of IC50 --> Treatment response: z-score of IC50
Drug treatment IC50 --> Treatment response: IC50

![image](https://user-images.githubusercontent.com/11892704/64459586-3e5e9a00-d0c6-11e9-997f-0a2877ee3292.png)

**Comment by ritikakundra** [comment]
updated
