### ISSUE TITLE
(brca_tcga_pub2015) probably wrong profile name

### ISSUE THREAD

**Issue by dippindots** [cBioPortal/datahub#822]
The profile name of the `brca_tcga_pub2015` is probably wrong.
You can reproduce this by going to the download tab on the home page -> select "Breast Invasive Carcinoma (TCGA, Cell 2015)" 
![Screen Shot 2019-09-10 at 3 10 19 PM](https://user-images.githubusercontent.com/15748980/64643170-d669c580-d3dd-11e9-8056-81304893325b.png)

**Comment by yichaoS** [comment]
![Screen Shot 2019-10-02 at 2 38 46 PM](https://user-images.githubusercontent.com/5973438/66072043-46252900-e522-11e9-95db-0450b0443acf.png)

**Comment by dippindots** [comment]
@yichaoS Thanks for the fix!
