### ISSUE TITLE
Parikh et al. Liquid versus tissue biopsy for detecting acquired resistance and tumor heterogeneity in gastrointestinal cancers. Nat Med, 2019

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#826]
https://www.nature.com/articles/s41591-019-0561-9

- [ ] [create a issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [ ] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [ ] Document the curation process, e.g. how and by whom the data was transformed
- [ ] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [ ] Create a pull request to datahub once the data is curated
- [ ] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update the default quick select study list see https://github.com/cBioPortal/cbioportal/issues/5831 (only for studies that are not overlapping with existing ones; only for human tumors, not cell lines)
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

**Comment by yichaoS** [comment]
We don't have access to https://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/study.cgi?study_id=phs001853.v1.p1 for downloading WES sequencing data and RNA-Seq data. 
(only clinical data was provided in the publication supplemental)

**Comment by yichaoS** [comment]
@jjgao ^

**Comment by jjgao** [comment]
@yichaoS have you tried to contact the author?

**Comment by sbabyanusha** [comment]
Closing the issue as we couldn't get a response from the author.
