### ISSUE TITLE
Change the rnaseq profile ID for paad_qcmg_uq_2016

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#830]
Currently, it is [rna_seq_v2_mrna](https://github.com/cBioPortal/datahub/blob/master/public/paad_qcmg_uq_2016/meta_RNA_Seq_v2_expression_median.txt), but the normalization is actually different from what TCGA is using. This is causing some confusion: https://github.com/cBioPortal/cbioportal/issues/6595. 

Can we rename it to `rna_seq_mrna`?

BTW, why there is only zscores profile for the rna seq data?

**Comment by yichaoS** [comment]
@jjgao updated the profile ID and right now we have the original expression files in it. The z-score is being re-generated and added separately in this PR: https://github.com/cBioPortal/datahub/pull/827
