### ISSUE TITLE
Table 'cbioportal.authorities' doesn't exist

### ISSUE THREAD

**Issue by cb1544** [cBioPortal/datahub#835]
Hi,

I'm trying to deploy with Docker. 
I downloaded the seed database from the cBioPortal Datahub, and use the command indicated to upload the seed data to the server started before.

I got this error :

ERROR 1146 (42S02) at line 22: Table 'cbioportal.authorities' doesn't exist

Any ideas please ?

Thank you !

Best,
Camelia

**Comment by jjgao** [comment]
@cb1544 would you please contact cbioportal@googlegroups.com?
