### ISSUE TITLE
Quentmeier et al: The LL-100 panel: 100 cell lines for blood cancer studies. Sci Rep 2019.

### ISSUE THREAD

**Issue by mcnaircm** [cBioPortal/datahub#850]
Link to paper on pubmed (PMID=PMC6547646): [PubMedLink](https://www.ncbi.nlm.nih.gov/pubmed/?term=PMC6547646)
Link to files associated with WES: [EBI_WES_Data](https://www.ebi.ac.uk/ena/data/view/PRJEB30297)
Link to files associated with RNASeq: [EBI_RNASeq_Data](https://www.ebi.ac.uk/ena/data/view/PRJEB30312)

Please keep this checklist for curation of a new study. 

- [x] [create a issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [x] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [ ] Document the curation process, e.g. how and by whom the data was transformed
- [ ] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [ ] Create a pull request to datahub once the data is curated
- [ ] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] ~~Update the default quick select study list see https://github.com/cBioPortal/cbioportal/issues/5831 (only for studies that are not overlapping with existing ones; only for human tumors, not cell lines)~~
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

**Comment by yichaoS** [comment]
Data Issue: 
- Under the ENA data links seems like there are are only separated FASTQ files for each sample. 
- In the paper’s supplemental section, seems like there’s no data we can use either.

**Comment by mcnaircm** [comment]
What data types are needed for RNASeq and WES experiments in order to be curated and used?
________________________________

**Comment by yichaoS** [comment]
Hi @mcnaircm We defined our file format here: https://github.com/cbioportal/cbioportal/blob/master/docs/File-Formats.md

**Comment by jjgao** [comment]
Since we could not find the data, let's close it for now.
