### ISSUE TITLE
Typo in ZSCORE treatment response profile name of ccle_broad_2019 

### ISSUE THREAD

**Issue by pvannierop** [cBioPortal/datahub#862]
In meta files `meta_drug_treatment_ZSCORE.txt` the name of the treatment profile contains a typo (lacks a t`). This should be 'Trea**t**ment response: Z-score of IC50'

**Comment by jjgao** [comment]
looks like it's fixed. 

@ritikakundra FYI - it would be a good idea to comment with [closing keyword](https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords) in pull requests or commit messages so that issues get closed automatically.
