### ISSUE TITLE
rename "TCGA, Provisional" to TCGA, Firehose Legacy"

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#887]

**Comment by ecerami** [comment]
Just for some context here, Ben has indicated that we haven't run the Firehose import since the last GDAC run in 2016.  So, we all agreed that "TCGA, Firehose Legacy" is a better name that "TCGA, Provisional".  This applies to all TCGA provisional studies in the data hub,

**Comment by ritikakundra** [comment]
@ecerami @jjgao should we include the date of the last update in meta study also?

**Comment by ritikakundra** [comment]
Checklist:

- [ ] Rename all TCGA provisional meta-study from "TCGA, Provisional" to TCGA, Firehose Legacy in datahub.

- [ ] Import to Internal and public portals

**Comment by jjgao** [comment]
@ritikakundra I think it's a good idea to include the date.
