### ISSUE TITLE
add gene panel for TCGA GBM samples 

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/datahub#903]
TCGA GBM includes samples which were profiled by targeted sequencing of 601 genes, not by whole-exome sequencing. The 2008 publication is entirely targeted sequencing, and those same samples are presumably also present in the larger TCGA GBM studies.

We should add gene panel data for the appropriate samples in these studies:
gbm_tcga_pub
gbm_tcga_pub2013
gbm_tcga
gbm_tcga_pan_can_atlas_2018
lgggbm_tcga_pub

**Comment by ritikakundra** [comment]
@tmazor: @yichaoS is working on adding panel files to all missing targeted studies, this is part of that too.

**Comment by yichaoS** [comment]
@tmazor @ritikakundra gbm_tcga_pub panel added. But seems like gbm_tcga_pub2013 in WGS?

**Comment by tmazor** [comment]
@yichaoS the new data for gbm_tcga_pub2013 was mostly WES but the study also included some of those early samples with targeted sequencing only:

![image](https://user-images.githubusercontent.com/10508276/69256670-d4637600-0b87-11ea-9ff3-b800b05346af.png)
https://www.sciencedirect.com/science/article/pii/S0092867413012087?via%3Dihub

**Comment by yichaoS** [comment]
@tmazor We have all the exome sequencing data for gbm_tcga_pub2013 in portal but only that. I can't find the targeted sequencing data anywhere, so maybe we could just leave it as it is? @jjgao  I created the follow up issue here about the sample case list issue of gbm_tcga_pub2013 here: https://github.com/cBioPortal/datahub/issues/916

**Comment by jjgao** [comment]
let's close this. @tmazor please reopen if you find it's not complete.
