### ISSUE TITLE
gbm_tcga_pub2013 sequence case list is not correct & sample missing

### ISSUE THREAD

**Issue by yichaoS** [cBioPortal/datahub#916]
In publication, 291 samples are exome sequenced, however in our own case list, it's only 257 (due to auto generation by case list tool). 

The paper is here: 
https://www.sciencedirect.com/science/article/pii/S0092867413012087?via%3Dihub

The original supplemental data here: 
https://gdc.cancer.gov/about-data/publications/gbm_2013

The list of exome-sequenced samples are (some seems to be even missing from the cohort)
TCGA-02-0003
TCGA-02-0033
TCGA-02-0047
TCGA-02-0055
TCGA-06-0122
TCGA-06-0124
TCGA-06-0125
TCGA-06-0126
TCGA-06-0128
TCGA-06-0129
TCGA-06-0130
TCGA-06-0137
TCGA-06-0139
TCGA-06-0141
TCGA-06-0142
TCGA-06-0145
TCGA-06-0151
TCGA-06-0152
TCGA-06-0154
TCGA-06-0157
TCGA-06-0158
TCGA-06-0165
TCGA-06-0166
TCGA-06-0167
TCGA-06-0168
TCGA-06-0169
TCGA-06-0171
TCGA-06-0173
TCGA-06-0174
TCGA-06-0178
TCGA-06-0184
TCGA-06-0185
TCGA-06-0188
TCGA-06-0189
TCGA-06-0190
TCGA-06-0195
TCGA-06-0209
TCGA-06-0210
TCGA-06-0211
TCGA-06-0213
TCGA-06-0214
TCGA-06-0216
TCGA-06-0219
TCGA-06-0221
TCGA-06-0237
TCGA-06-0238
TCGA-06-0241
TCGA-06-0644
TCGA-06-0645
TCGA-06-0646
TCGA-06-0648
TCGA-08-0386
TCGA-12-0615
TCGA-12-0616
TCGA-12-0618
TCGA-12-0619
TCGA-02-2470
TCGA-02-2485
TCGA-02-2486
TCGA-06-0192
TCGA-06-0649
TCGA-06-0686
TCGA-06-0744
TCGA-06-0745
TCGA-06-0747
TCGA-06-0749
TCGA-06-0875
TCGA-06-0876
TCGA-06-0877
TCGA-06-0878
TCGA-06-0879
TCGA-06-0881
TCGA-06-0882
TCGA-06-2558
TCGA-06-2559
TCGA-06-2561
TCGA-06-2562
TCGA-06-2563
TCGA-06-2567
TCGA-06-2569
TCGA-12-0692
TCGA-12-0821
TCGA-12-1597
TCGA-12-3649
TCGA-12-3650
TCGA-12-3652
TCGA-12-3653
TCGA-14-0787
TCGA-14-0789
TCGA-14-0790
TCGA-14-0813
TCGA-14-0817
TCGA-14-0871
TCGA-14-1823
TCGA-14-1825
TCGA-14-1829
TCGA-14-2554
TCGA-15-0742
TCGA-16-0846
TCGA-16-0861
TCGA-16-1045
TCGA-19-1390
TCGA-19-2619
TCGA-19-2620
TCGA-19-2623
TCGA-19-2624
TCGA-19-2625
TCGA-19-2629
TCGA-27-1830
TCGA-27-1831
TCGA-27-1832
TCGA-27-1833
TCGA-27-1834
TCGA-27-1836
TCGA-27-1837
TCGA-27-2519
TCGA-27-2521
TCGA-27-2523
TCGA-27-2524
TCGA-27-2526
TCGA-27-2528
TCGA-28-1747
TCGA-28-1753
TCGA-28-2502
TCGA-28-2509
TCGA-28-2513
TCGA-32-1970
TCGA-32-1982
TCGA-32-2632
TCGA-32-2634
TCGA-32-2638
TCGA-41-2571
TCGA-41-2573
TCGA-41-2575
TCGA-41-3392
TCGA-32-4211
TCGA-41-3393
TCGA-12-5295
TCGA-76-6664
TCGA-26-1439
TCGA-32-2491
TCGA-28-2514
TCGA-81-5910
TCGA-19-2631
TCGA-06-0750
TCGA-76-4926
TCGA-32-2495
TCGA-06-5410
TCGA-76-6282
TCGA-76-6283
TCGA-76-4927
TCGA-06-0240
TCGA-06-1804
TCGA-76-6285
TCGA-19-5959
TCGA-06-6694
TCGA-02-2483
TCGA-06-6700
TCGA-06-0119
TCGA-74-6584
TCGA-27-1835
TCGA-14-1395
TCGA-26-5136
TCGA-06-6388
TCGA-76-6280
TCGA-32-4210
TCGA-32-1991
TCGA-41-5651
TCGA-32-4719
TCGA-19-5954
TCGA-26-5139
TCGA-12-5301
TCGA-19-5950
TCGA-76-6191
TCGA-32-2498
TCGA-19-4068
TCGA-32-2615
TCGA-06-5859
TCGA-28-5207
TCGA-15-1444
TCGA-32-1979
TCGA-76-4929
TCGA-14-0740
TCGA-14-4157
TCGA-06-5412
TCGA-41-3915
TCGA-26-5134
TCGA-26-1442
TCGA-14-3476
TCGA-06-5415
TCGA-06-5414
TCGA-14-1450
TCGA-06-2565
TCGA-32-5222
TCGA-74-6575
TCGA-19-5952
TCGA-28-5216
TCGA-32-4208
TCGA-32-4209
TCGA-74-6573
TCGA-76-6193
TCGA-41-2572
TCGA-06-0155
TCGA-76-4925
TCGA-06-6695
TCGA-32-1977
TCGA-14-0862
TCGA-76-6657
TCGA-06-6701
TCGA-76-6192
TCGA-06-0743
TCGA-32-1980
TCGA-32-2494
TCGA-28-2499
TCGA-06-6698
TCGA-06-6693
TCGA-74-6578
TCGA-28-5213
TCGA-19-5955
TCGA-16-1048
TCGA-12-5299
TCGA-14-0786
TCGA-26-5132
TCGA-28-5218
TCGA-76-6656
TCGA-06-5858
TCGA-26-6173
TCGA-87-5896
TCGA-32-1986
TCGA-06-6699
TCGA-32-4213
TCGA-19-1790
TCGA-06-6391
TCGA-41-6646
TCGA-41-4097
TCGA-26-5135
TCGA-28-5211
TCGA-19-5960
TCGA-27-2527
TCGA-27-1838
TCGA-28-5219
TCGA-06-0939
TCGA-28-5204
TCGA-14-1034
TCGA-28-5209
TCGA-27-2518
TCGA-26-6174
TCGA-06-5411
TCGA-76-4935
TCGA-06-0140
TCGA-19-5951
TCGA-19-5958
TCGA-06-2570
TCGA-19-5953
TCGA-06-6697
TCGA-06-5408
TCGA-28-6450
TCGA-76-6286
TCGA-76-6663
TCGA-06-0132
TCGA-28-5208
TCGA-06-2557
TCGA-06-0650
TCGA-74-6577
TCGA-06-6389
TCGA-28-5220
TCGA-06-5417
TCGA-76-4931
TCGA-81-5911
TCGA-76-4928
TCGA-06-5418
TCGA-28-2501
TCGA-06-5856
TCGA-14-0781
TCGA-26-5133
TCGA-28-2510
TCGA-06-1806
TCGA-76-4932
TCGA-28-5215
TCGA-76-6660
TCGA-06-5413
TCGA-14-1456
TCGA-76-6662
TCGA-28-5214
TCGA-19-5947
TCGA-76-6661
TCGA-14-1043
TCGA-76-4934
TCGA-12-0688
TCGA-06-2564
TCGA-06-6390

**Comment by jjgao** [comment]
I think the cases are missing form the whole study, not just case list.
