### ISSUE TITLE
Liu et al. Integrative molecular and clinical modeling of clinical outcomes to PD1 blockade in patients with metastatic melanoma. Nat Med. 2019.

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#927]
https://www.nature.com/articles/s41591-019-0654-5

- [ ] [create an issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [ ] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [ ] Document the curation process, e.g. how and by whom the data was transformed
- [ ] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [ ] Create a pull request to datahub once the data is curated
- [ ] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update the default quick select study list see https://github.com/cBioPortal/cbioportal/issues/5831 (only for studies that are not overlapping with existing ones; only for human tumors, not cell lines)
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

**Comment by yichaoS** [comment]
The author sent us the MAF with the coordinates here: 

[all_muts_12_1_2020_ref_alt_counts_added.txt](https://github.com/cBioPortal/datahub/files/5630038/all_muts_12_1_2020_ref_alt_counts_added.txt)

**Comment by jjgao** [comment]
https://www.cbioportal.org/study/summary?id=mel_dfci_2019
