### ISSUE TITLE
sarc_mskcc: extra samples 

### ISSUE THREAD

**Issue by yichaoS** [cBioPortal/datahub#928]
From the beginning of this study being checked in(https://data.cbioportal.mskcc.org/hg/cbio-portal-data/file/11862becedf3/studies/sarc/mskcc), we have 9 extra samples (than in the publication itself https://www.ncbi.nlm.nih.gov/pubmed/20601955) with expression data and gene matrix info. 

List of sample ID: 
NF225	NF225	SARCNOS	Soft Tissue Sarcoma	 Sarcoma, NOS 
NF92	NF92	SARCNOS	Soft Tissue Sarcoma	 Sarcoma, NOS 
NF90	NF90	SARCNOS	Soft Tissue Sarcoma	 Sarcoma, NOS 
NF84	NF84	SARCNOS	Soft Tissue Sarcoma	 Sarcoma, NOS 
NF180	NF180	SARCNOS	Soft Tissue Sarcoma	 Sarcoma, NOS 
NF95	NF95	SARCNOS	Soft Tissue Sarcoma	 Sarcoma, NOS 
NF119	NF119	SARCNOS	Soft Tissue Sarcoma	 Sarcoma, NOS 
NF117	NF117	SARCNOS	Soft Tissue Sarcoma	 Sarcoma, NOS 
NF115	NF115	SARCNOS	Soft Tissue Sarcoma	 Sarcoma, NOS

**Comment by rmadupuri** [comment]
@ritikakundra @yichaoS, should we remove the extra 9 samples from the study to be consistent with the paper? (I remember we had similar issue with tcga pub studies and removed the samples there).
