### ISSUE TITLE
ccle_2019 data_CNA.txt has duplicated genes with different values

### ISSUE THREAD

**Issue by tmazor** [cBioPortal/datahub#988]
As reported by a user: https://groups.google.com/forum/#!topic/cbioportal/kxxHR9ueMpo

Genes appear to be duplicated in the data_CNA.txt file, and each entry of a gene has different values. After looking at a few genes, it seems that perhaps there is one entry for deletions in a gene, and a second entry for amplifications in that same gene.

**Comment by tmazor** [comment]
@ritikakundra @jjgao any updates on resolving this?

**Comment by ritikakundra** [comment]
@tmazor yes, am about to push a PR out for it.

**Comment by tmazor** [comment]
great, thanks @ritikakundra ! can you let me know when it's live so i can let the user know?

**Comment by ritikakundra** [comment]
@tmazor Sorry, this is done
