### ISSUE TITLE
Rosen et al. TRK Fusions are Enriched in Cancers with Uncommon Histologies and the Absence of Canonical Driver Mutations. CCR. 2019.

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#990]
https://clincancerres.aacrjournals.org/content/early/2019/12/21/1078-0432.CCR-19-3165

The study included a wrong link to internal msk portal: https://cbioportal.mskcc.org/study/summary?id=mixed_ntrk_msk_2019

Please make the changes below (pending agreement from Ezra):

Study id: ntrk_msk_2019
Study name: “Tumors with TRK fusions (MSK, 2019)”
Study desc: “Tumors with TRK fusions based on MSK-IMPACT targeted sequencing”

- [ ] [create an issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [ ] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [ ] Document the curation process, e.g. how and by whom the data was transformed
- [ ] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [ ] Create a pull request to datahub once the data is curated
- [ ] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update the default quick select study list see https://github.com/cBioPortal/cbioportal/issues/5831 (only for studies that are not overlapping with existing ones; only for human tumors, not cell lines)
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

**Comment by ritikakundra** [comment]
Data in the public portal:https://www.cbioportal.org/study/summary?id=ntrk_msk_2019
